[id='ispn_modules']
:context: server
= Using {brandname} in {wildflybrandname} applications

{wildflybrandname} includes {brandname} modules that you can use in {wildflybrandname} applications. You can do this in two ways:

* Include the {brandname} libraries in a {wildflybrandname} application.
+
When you include the {brandname} libraries within an application, the caches are local to the application and cannot be used by other applications. Additionally, the cache  configuration is within the application.

* Use the {brandname} libraries provided by {wildflybrandname}.
+
Using the {brandname} libraries provided by {wildflybrandname} has the following benefits:

** The cache is shared between applications.
** The cache configuration is part of {wildflybrandname} standalone or domain XML files.
** Applications do not include {brandname} libraries, they instead reference the required module from the MANIFEST or jboss-structure.xml configuration files.

The following procedures describe using the {brandname} libraries provided by {wildflybrandname}.


include::{topics}/proc_adding_dependencies_wildfly_modules.adoc[leveloffset=+1]

include::{topics}/proc_configuring-caches-in-jboss.adoc[leveloffset=+1]

include::{topics}/proc_using-cahches-in-jboss-applications.adoc[leveloffset=+1]
// Restore the parent context.
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
