version: 2
updates:
  # main
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    ignore:
      - dependency-name: "io.opentelemetry:*"
      - dependency-name: "io.netty:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "io.quarkus:*"
        update-types: [ "version-update:semver-minor"]
      - dependency-name: "io.vertx:*"
        update-types: [ "version-update:semver-minor" ]
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    groups:
      netty:
        patterns:
          - "io.netty:*"
      quarkus:
        patterns:
          - "io.quarkus:*"
      vertx:
        patterns:
          - "io.vertx:*"
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"

  # 16.0.x Security Updates Only
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    rebase-strategy: disabled
    target-branch: "16.0.x"
    commit-message:
      prefix: "[16.0] "
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    target-branch: "16.0.x"
    commit-message:
      prefix: "[16.0] "
    groups:
      actions:
        patterns:
          - "*"

  # 15.2.x Security Updates Only
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    rebase-strategy: disabled
    target-branch: "15.2.x"
    commit-message:
      prefix: "[15.2] "
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    target-branch: "15.2.x"
    commit-message:
      prefix: "[15.2] "
    groups:
      actions:
        patterns:
          - "*"
