package org.infinispan.server.test.api;

/**
 * Users and Roles generated by the testing driver
 *
 * @see {@link org.infinispan.server.test.core.AbstractInfinispanServerDriver}
 *
 * @author Katia Aresti
 * @since 11
 */
public enum TestUser {
   ADMIN("admin", "strongPassword", "AdminRole"),
   READER("reader", "password", "ReaderRole"),
   WRITER("writer", "somePassword", "WriterRole"),
   SUPERVISOR("supervisor", "lessStrongPassword", "SupervisorRole");


   private final String user;
   private final String password;
   private final String role;

   TestUser(String user, String password, String role) {
      this.user = user;
      this.password = password;
      this.role = role;
   }

   public String getUser() {
      return user;
   }

   public String getPassword() {
      return password;
   }

   public String getRole() {
      return role;
   }
}
