apiVersion: operators.coreos.com/v1
kind: Subscription
metadata:
  name: infinispan
  namespace: {{NAMESPACE}}
spec:
  channel: 2.1.x
  installPlanApproval: Automatic
  name: infinispan
  source: community-operators
  sourceNamespace: openshift-marketplace
