name: Bug Report
description: Report a bug in Infinispan
type: bug
body:
  - type: markdown
    attributes:
      value: |
        **To report an Infinispan security vulnerability, please [send an email to `security@infinispan.org`](mailto:security@infinispan.org) with all the details.**

        :warning: Do **NOT** create a public issue on GitHub for security vulnerabilities. See our [security policy](https://github.com/infinispan/infinispan/security/policy) for more details. :warning:
  - type: markdown
    attributes:
      value: |
        To maximize the chance of your issue being handled in a timely manner, please ensure you have tested that the issue occurs on the absolute latest version of Infinispan. 
        Moreover, providing a minimal canonical sample project that makes it easy to reproduce the issue is a huge help to the community when it comes to understanding, debugging, fixing the problem and testing the fix.
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: >-
        Describe the expected behavior clearly and concisely.
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: >-
        Describe the actual behavior clearly and concisely.
  - type: textarea
    id: how_to_reproduce
    attributes:
      label: How to Reproduce?
      description: >-
        Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific) or attach an archive containing the reproducer to the issue.
      placeholder: |
        Reproducer:

        Steps to reproduce the behavior:
        1.
        2.
        3.
  - type: markdown
    id: environment
    attributes:
      value: |
        ## Environment (Version, JDK, OS, ...)
