package org.infinispan.server.resp;

public interface ExternalizerIds {

    Integer EVENT_LISTENER_FILTER = 2200;
    Integer EVENT_IGNORE_VALUE_CONVERTER = 2201;
    Integer EVENT_LISTENER_CONVERTER = 2202;

    Integer COMPOSED_FILTER_CONVERTER = 2203;
    Integer JSON_GET_FUNCTION = 2204;
    Integer JSON_SET_FUNCTION = 2205;
    Integer JSON_LEN_ARR_FUNCTION = 2206;
    Integer JSON_LEN_STR_FUNCTION = 2207;
    Integer JSON_LEN_OBJ_FUNCTION = 2208;
    Integer JSON_TYPE_FUNCTION = 2209;
    Integer JSON_DEL_FUNCTION = 2210;
    Integer JSON_ARRAY_APPEND_FUNCTION = 2211;
    Integer JSON_TOGGLE_FUNCTION = 2212;
    Integer JSON_OBJKEYS_FUNCTION = 2213;
    Integer JSON_NUM_INCR_BY_FUNCTION = 2214;
    Integer JSON_NUM_MULT_BY_FUNCTION = 2215;
    Integer JSON_ARRINDEX_FUNCTION = 2216;
    Integer JSON_BUCKET = 2217;
    Integer JSON_STRING_APPEND_FUNCTION = 2218;
    Integer JSON_ARRINSERT_FUNCTION = 2219;
    Integer JSON_ARRTRIM_FUNCTION = 2220;
    Integer JSON_CLEAR_FUNCTION = 2221;
    Integer JSON_ARRPOP_FUNCTION = 2222;
    Integer JSON_MERGE_FUNCTION = 2223;
}
