package org.infinispan.server.resp;

import org.infinispan.protostream.SerializationContextInitializer;
import org.infinispan.protostream.annotations.ProtoSchema;
import org.infinispan.protostream.annotations.ProtoSyntax;

@ProtoSchema(
      allowNullFields = true,
      dependsOn = {
            PersistenceContextInitializer.class,
            org.infinispan.marshall.protostream.impl.GlobalContextInitializer.class,
            org.infinispan.server.core.GlobalContextInitializer.class,
      },
      includeClasses = {
            org.infinispan.server.resp.commands.tx.WATCH.TxEventConverterEmpty.class,
            org.infinispan.server.resp.filter.ComposedFilterConverter.class,
            org.infinispan.server.resp.filter.EventListenerConverter.class,
            org.infinispan.server.resp.filter.EventListenerGlobFilter.class,
            org.infinispan.server.resp.filter.EventListenerKeysFilter.class,
            org.infinispan.server.resp.filter.GlobMatchFilterConverter.class,
            org.infinispan.server.resp.filter.RespTypeFilterConverter.class,
            org.infinispan.server.resp.json.JsonArrayAppendFunction.class,
            org.infinispan.server.resp.json.JsonArrindexFunction.class,
            org.infinispan.server.resp.json.JsonArrinsertFunction.class,
            org.infinispan.server.resp.json.JsonArrpopFunction.class,
            org.infinispan.server.resp.json.JsonArrtrimFunction.class,
            org.infinispan.server.resp.json.JsonBucket.class,
            org.infinispan.server.resp.json.JsonClearFunction.class,
            org.infinispan.server.resp.json.JsonDelFunction.class,
            org.infinispan.server.resp.json.JsonGetFunction.class,
            org.infinispan.server.resp.json.JsonLenArrayFunction.class,
            org.infinispan.server.resp.json.JsonLenObjFunction.class,
            org.infinispan.server.resp.json.JsonLenStrFunction.class,
            org.infinispan.server.resp.json.JsonMergeFunction.class,
            org.infinispan.server.resp.json.JsonNumIncrOpFunction.class,
            org.infinispan.server.resp.json.JsonNumMultOpFunction.class,
            org.infinispan.server.resp.json.JsonObjkeysFunction.class,
            org.infinispan.server.resp.json.JsonRespFunction.class,
            org.infinispan.server.resp.json.JsonSetFunction.class,
            org.infinispan.server.resp.json.JsonStringAppendFunction.class,
            org.infinispan.server.resp.json.JsonToggleFunction.class,
            org.infinispan.server.resp.json.JsonTypeFunction.class,
            org.infinispan.server.resp.RespTypes.class,
            org.infinispan.server.resp.json.JsonDebugMemoryFunction.class,
            org.infinispan.server.resp.commands.bloom.BloomFilterReserveFunction.class,
            org.infinispan.server.resp.commands.bloom.BloomFilterInsertFunction.class,
            org.infinispan.server.resp.commands.bloom.BloomFilterExistsFunction.class,
            org.infinispan.server.resp.commands.bloom.BloomFilterCardFunction.class,
            org.infinispan.server.resp.commands.bloom.BloomFilterInfoFunction.class,
            org.infinispan.server.resp.commands.bloom.BloomFilterInfoFunction.BloomFilterInfo.class,
            org.infinispan.server.resp.commands.cuckoo.CuckooFilterReserveFunction.class,
            org.infinispan.server.resp.commands.cuckoo.CuckooFilterInsertFunction.class,
            org.infinispan.server.resp.commands.cuckoo.CuckooFilterExistsFunction.class,
            org.infinispan.server.resp.commands.cuckoo.CuckooFilterCountFunction.class,
            org.infinispan.server.resp.commands.cuckoo.CuckooFilterDelFunction.class,
            org.infinispan.server.resp.commands.cuckoo.CuckooFilterInfoFunction.class,
            org.infinispan.server.resp.commands.cuckoo.CuckooFilterInfoFunction.CuckooFilterInfo.class,
            org.infinispan.server.resp.commands.countmin.CmsInitFunction.class,
            org.infinispan.server.resp.commands.countmin.CmsIncrByFunction.class,
            org.infinispan.server.resp.commands.countmin.CmsQueryFunction.class,
            org.infinispan.server.resp.commands.countmin.CmsInfoFunction.class,
            org.infinispan.server.resp.commands.countmin.CmsInfoFunction.CmsInfo.class,
            org.infinispan.server.resp.commands.countmin.CmsMergeFunction.class,
            org.infinispan.server.resp.commands.bitmap.BitfieldFunction.class,
            org.infinispan.server.resp.commands.bitmap.BitfieldOperation.class,
            org.infinispan.server.resp.commands.bitmap.BitfieldOperation.Type.class,
            org.infinispan.server.resp.commands.bitmap.BitfieldOperation.Overflow.class,
      },
      schemaFileName = "global.resp.proto",
      schemaFilePath = "org/infinispan/erver/resp",
      schemaPackageName = "org.infinispan.global.resp",
      service = false,
      syntax = ProtoSyntax.PROTO3,
      orderedMarshallers = true
)
public interface GlobalContextInitializer extends SerializationContextInitializer { }
