---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames: 
  - "jboss.datagrid-infinispan:type=Cache,name=*,manager=*,component=Statistics"
  - "jboss.datagrid-infinispan:type=Cache,name=*,manager=*,component=Cache"
  - "jboss.datagrid-infinispan:type=Cache,name=*,manager=*,component=ClusterCacheStats"
  - "jboss.datagrid-infinispan:type=Cache,name=*,manager=*,component=StateTransferManager"
rules:
  - pattern: "^jboss.datagrid-infinispan<type=Cache, name=\"(.+)\\(.+\\)\", manager=\"(.+)\", component=Statistics><>(.+):"
    attrNameSnakeCase: true
    name: datagrid_cache_stats
    labels:
      name: $1
      container: $2
      attribute: $3
    help: JMX MBean Statistics
  - pattern: "^jboss.datagrid-infinispan<type=Cache, name=\"(.+)\\(.+\\)\", manager=\"(.+)\", component=Cache><>(.+):"
    attrNameSnakeCase: true
    name: datagrid_cache
    labels:
      name: $1
      container: $2
      attribute: $3
    help: JMX MBean Cache
  - pattern: "^jboss.datagrid-infinispan<type=Cache, name=\"(.+)\\(.+\\)\", manager=\"(.+)\", component=ClusterCacheStats><>(.+):"
    attrNameSnakeCase: true
    name: datagrid_cluster_cache_stats
    labels:
      name: $1
      container: $2
      attribute: $3
    help: JMX MBean ClusterCacheStats
  - pattern: "^jboss.datagrid-infinispan<type=Cache, name=\"(.+)\\(.+\\)\", manager=\"(.+)\", component=StateTransferManager><>(.+):"
    attrNameSnakeCase: true
    name: datagrid_state_transfer_manager
    labels:
      name: $1
      container: $2
      attribute: $3
    help: JMX MBean StateTransferManager
      
