[[sid-68354930]]

==  Project Evaluation FAQs


*  <<sid-68354932>> 


*  <<sid-68354941>> 


*  <<sid-68354933>> 


*  <<sid-68354934>> 


*  <<sid-68354935>> 


*  <<sid-68354936,How come Infinispan's first release is 4.0.0?  This sounds weird!>> 


*  <<sid-68354937>> 


*  <<sid-68354938>> 


*  <<sid-68354939>> 


*  <<sid-68354940>> 

[[sid-68354932]]


=== What is Infinispan?

 Infinispan is an open source data grid platform. It exposes a link:$$http://jcp.org/en/jsr/detail?id=107$$[JSR-107] compatible link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/Cache.html$$[Cache] interface (which in turn extends java.util.Map ) in which you can store objects. While Inﬁnispan can be run in local mode, its real value is in distributed mode where caches cluster together and expose a large memory heap. Distributed mode is more powerful than simple replication since each data entry is spread out only to a ﬁxed number of replicas thus providing resilience to server failures as well as scalability since the work done to store each entry is constant in relation to a cluster size. 

So, why would you use it? Infinispan offers:


*  _Massive heap_ and _high availability_ - If you have 100 blade servers, and each node has 2GB of space to dedicate to a replicated cache, you end up with 2 GB of total data. Every server is just a copy. On the other hand, with a distributed grid - assuming you want 1 copy per data item - you get a 100 GB memory backed virtual heap that is efficiently accessible from anywhere in the grid. If a server fails, the grid simply creates new copies of the lost data, and puts them on other servers. Applications looking for ultimate performance are no longer forced to delegate the majority of their data lookups to a large single database server - the bottleneck that exists in over 80% of enterprise applications!  


*  _Scalability_ - Since data is evenly distributed there is essentially no major limit to the size of the grid, except group communication on the network - which is minimised to just discovery of new nodes. All data access patterns use peer-to-peer communication where nodes directly speak to each other, which scales very well. Infinispan does not require entire infrastructure shutdown to allow scaling up or down. Simply add/remove machines to your cluster without incurring any down-time.  


*  _Data distribution_ - Infinispan uses consistent hash algorithm to determine where keys should be located in the cluster.  Consistent hashing allows for cheap, fast and above all, deterministic location of keys with no need for further metadata or network traffic. The goal of data distribution is to maintain enough copies of state in the cluster so it can be durable and fault tolerant, but not too many copies to prevent Infinispan from being scalable. 


*  _Persistence_ - Inﬁnispan exposes a CacheStore interface, and several high-performance implementations - including JDBC cache stores, ﬁlesystem-based cache stores, Amazon S3 cache stores, etc.  CacheStores can be used for "warm starts", or simply to ensure data in the grid survives complete grid restarts, or even to overﬂow to disk if you really do run out of memory. 


*  _Language bindings_ (PHP, Python, Ruby, C, etc.) - Infinispan offers support for both the popular memcached protocol - with existing clients for almost every popular programming language - as well as an optimised Infinispan-specific protocol called HotRod. This means that Infinispan is not just useful to Java. Any major website or application that wants to take advantage of a fast data grid will be able to do so. 


*  _Management_ - When you start thinking about running a grid on several hundred servers, management is no longer an extra, it becomes a necessity. The preferred way to manage multiple Infinispan instances spread accross different servers is to use link:$$http://rhq.org$$[RHQ] which is JBoss' enterprise management solution. Thanks to RHQ's agent and auto discovery capabilities, monitoring both Cache Manager and Cache instances is a very simple. 


*  _Support for Compute Grids_ - Infinispan 5 adds the ability to pass a Runnable around the grid. This allows you to push complex processing towards the server where data is local, and pull back results using a Future . This map/reduce style paradigm is common in applications where a large amount of data is needed to compute relatively small results. 

[[sid-68354941]]


=== What would I use Infinispan for?

 Infinispan's link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/Cache.html$$[org.infinispan.Cache] is a simple, flat data structure that can optionally include characteristics such as distribution, eviction, link:$$http://en.wikipedia.org/wiki/Java_Transaction_API$$[JTA] compatibility. 

[[sid-68354933]]


=== How is Infinispan related to JBoss Cache?

 Certain design ideas and indeed some code have been borrowed from link:$$http://www.jbosscache.org$$[JBoss Cache] 3.x, however JBoss Cache is in no way a dependency.  Infinispan is a complete, separate and standalone project.  Some may consider this a fork, but the people behind Infinispan and JBoss Cache see it as an evolution, since all future effort will be on Infinispan and not JBoss Cache. 

The current release of JBoss Cache, 3.2.3, is considered stable enough.  No new features will be added to JBoss Cache or POJO Cache, although critical fixes will still be addressed.  Consider both JBoss Cache and POJO Cache to be in maintenance mode.

So, why not just call it JBoss Cache 4?. Several reasons.  Binary and even API compatibility with older JBoss Cache releases is no longer maintained, and the new API is simpler and easier to use.  Also, the internal data structure used is not compatible with JBoss Cache.

[[sid-68354934]]


=== What version of Java does Infinispan need to run? Does Infinispan need an application server to run?

 All that is needed is a Java 6.0 compatible JVM. An application server is _not_ a requirement. 

[[sid-68354935]]


=== Will there be a POJO Cache replacement in Infinispan?

 Yes, and this is called link:$$http://www.hibernate.org/subprojects/ogm.html$$[Hibernate OGM] . 

[[sid-68354936]]


=== How come Infinispan's first release is 4.0.0?  This sounds weird!

We didn't want to release Infinispan as a 1.0, as in all fairness it is not a virgin codebase.  A lot of the code, designs and ideas in Infinispan are from JBoss Cache, and has been tried and tested, proven in high stress environments.  Infinispan should thus be viewed as a mature and stable platform and not a new, experimental one.

[[sid-68354937]]


=== What should I use, JBoss Cache or Infinispan?

If you are starting a new project, by all means use Infinispan.  If you already use JBoss Cache, consider upgrading to Infinispan as this is where most of our focus and efforts will be.  There is a compatibility layer to help people migrate, although we recommend only using this if you (a) absolutely need a tree structure, or (b) only for a short time as a stepping stone.  You will find that Infinispan's Map based API performs much better.  In addition, we plan to provide migration guides and configuration conversion tools.

[[sid-68354938]]


=== Where can I get more information on Infinispan?

 The link:$$http://www.jboss.org/infinispan$$[Infinispan project page] is your best place to start things off, whether you are interested in using Infinispan in your work or are interested in collaborating on and contributing to Infinispan. 

[[sid-68354939]]


=== How is this related to JSR 107, the JCACHE specification?

 link:$$http://jcp.org/en/jsr/detail?id=107$$[JSR 107] is not complete, but Infinispan's primary API is as close as possible to JSR 107's javax.cache.Cache interface.  The goal is once JSR 107 is complete, the org.infinispan.Cache interface would extend javax.cache.Cache .  The key thing to note is that just like javax.cache.Cache , org.infinispan.Cache looks just like a java.util.concurrent.ConcurrentMap which would make migration between JSR 107 compliant data structures simple. 

 link:$$http://community.jboss.org/people/manik$$[Manik Surtani] , who is project lead on Infinispan, and link:$$http://in.relation.to/Bloggers/Pete$$[Pete Muir] are on the JSR 107 expert group. 

[[sid-68354940]]


=== Can I use Infinispan with Hibernate?

Yes, you can combine one or more of these integrations in the same application:


*  _Caching database access_ : Hibernate can cache frequently loaded entities and queries in Infinispan, taking advantage of state of the art eviction algorithms, and clustering if needed but it provides a good performance boost in non-clustered deployments too. See link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737110$$[Using Infinispan as JPA/Hibernate Second Level Cache Provider] for details on how to do this. 


*  _Storing Lucene indexes_ : When using Hibernate Search to provide full-text capabilities to your Hibernate/JPA enabled application, you need to store an Apache Lucene index separately from the database. You can store the index in Infinispan: this is ideal for clustered applications since it's otherwise tricky to share the index with correct locking on shared file systems, but is an interesting option for non-clustered deployments too as it can combine the benefits of in-memory performance with reliability and write-through to cloud storage backends like S3, or the Hibernate database itself. See link:$$http://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#infinispan-directories$$[Infinispan Directory Configuration] in the Hibernate Search reference documentation for the integration details, or learn more about it at <<sid-68355039>> . 


*  _Using Infinispan as a database replacement_ : using the experimental Hibernate Object/Grid Mapper (OGM) you can remove the database and store your entities and relations in the grid directly, interacting with it through the well known JPA(2) interface, with some limitations in the query capabilities. For more details see link:$$http://www.hibernate.org/subprojects/ogm.html$$[Hibernate Object/Grid Mapper (OGM)] . 


*  _Using full-text queries on Infinispan_ : If you liked the powerful full-text and data mining capabilities of Hibernate Search, but don't need JPA or a database, you can use the indexing and query engine only: the Infinispan Query module reuses Hibernate Search internally, depending on some Hibernate libraries but exposing the Search capabilities only. See link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737030$$[Querying Infinispan] . 

