groups:
- name: Cross Site Rules
  rules:
  - alert: Cache Work and Site NYC
    expr: infinispan_x_site_admin_status{cache=\"Work\",site=\"NYC\"} == 0
  - alert: Cache Sessions and Site NYC
    expr: infinispan_x_site_admin_status{cache=\"Sessions\",site=\"NYC\"} == 0