PATCH(1)
========
:doctype: manpage


NAME
----
patch - manages server patches.


DESCRIPTION
-----------
List, describe, install, rollback, and create server patches.

Patches are zip archive files that contain artifacts to upgrade servers and
resolve issues or add new features. Patches can apply target versions to
multiple server installations with different versions.


SYNOPSIS
--------
*patch ls*

*patch install* 'patch-file'

*patch describe* 'patch-file'

*patch rollback*

*patch create* 'patch-file' 'target-server' 'source-server-1' ['source-server-2'...]


PATCH LIST OPTIONS
------------------

*--server*='path/to/server'::
Sets the path to a target server outside the current server home directory.

*-v, --verbose*::
Shows the content of each installed patch, including information about
individual files.


PATCH INSTALL OPTIONS
---------------------

*--dry-run*::
Shows the operations that the patch peforms without applying any changes.

*--server*='path/to/server'::
Sets the path to a target server outside the current server home directory.


PATCH DESCRIBE OPTIONS
----------------------

*-v, --verbose*::
Shows the content of the patch, including information about individual files


PATCH ROLLBACK OPTIONS
----------------------

*--dry-run*::
Shows the operations that the patch peforms without applying any changes.

*--server*='path/to/server'::
Sets the path to a target server outside the current server home directory.


PATCH CREATE OPTIONS
--------------------

*-q, --qualifier*='name'::
Specifies a descriptive qualifier string for the patch; for example, 'one-off for issue nnnn'.


EXAMPLES
--------

`patch ls` +
Lists the patches currently installed on a server in order of installation.

`patch install mypatch.zip` +
Installs "mypatch.zip" on a server in the current directory.

`patch install mypatch.zip --server=/path/to/server/home` +
Installs "mypatch.zip" on a server in a different directory.

`patch describe mypatch.zip` +
Displays the target version and list of source versions for "mypatch.zip".

`patch create mypatch.zip 'target-server' 'source-server-1' ['source-server-2'...]` +
Creates a patch file named "mypatch.zip" that uses the version of the target server and applies to the source server versions.

`patch rollback` +
Rolls back the last patch that was applied to a server and restores the
previous version.
