[[sid-68355130_GettingStartedGuide-DownloadingandinstallingInfinispan]]

==  Downloading and installing Infinispan

To run the Infinispan, you'll need


* Java 1.6


*  Maven 3, if you wish to use the quickstart examples or create a new project using the Infinispan link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737129$$[archetype] 


* the Infinispan distribution zip, if you wish to use Infinispan in server mode, or want to use the jars in an ant project


* the Infinispan Quickstart zip, if you want to follow along with the projects discussed in the guide


[TIP]
==== 
If you already have any of these pieces of software, there is no need to install them again!


==== 


Choose your Java runtime, and follow their installation instructions. For example, you could choose one of:


*  link:$$http://openjdk.java.net/install/$$[OpenJDK] 


*  link:$$http://www.oracle.com/technetwork/java/javase/index-137561.html$$[Oracle Java SE] 


*  link:$$http://download.oracle.com/docs/cd/E15289_01/doc.40/e15065/toc.htm$$[Oracle JRockit] 

 Follow the official Maven installation guide if you don't already have Maven 3 installed. You can check which version of Maven you have installed (if any) by running mvn --version . If you see a version newer than 3.0.0, you are ready to go. 


[TIP]
==== 
You can also deploy the examples using your favorite IDE. We provide instructions for using Eclipse only.


==== 


 Finally, download Infinispan and the Infinispan Quickstart from the link:$$http://jboss.org/infinispan/downloads$$[download page] . 

