=  The Basics

TIP: In this chapter we quickly walk through the basics on contributing; future chapters go into more depth.

== Prequisites
|=============
|Java 1.6|Infinispan is baselined on Java 6.0, and is built and tested using Sun Java 6.0.
|Maven 3|The Infinispan build uses Maven, and we recommend using Maven 3.
| Git _(optional)_ |The Infinispan sources are stored in Git. If you don't wish to install Git, you can download source bundles
|=============


[[sid-68355157_ContributingtoInfinispan-IssueManagementJIRA]]


== Issue Management - JIRA

Infinispan uses JIRA for issue management, hosted on link:$$http://issues.jboss.org/browse/ISPN$$[issues.jboss.org] . You can log in using your normal jboss.org username and password. 

If you need to create a new issue then follow these steps.


. Choose between


*  _Feature Request_ if you want to request an enhancement or new feature for Infinispan 


*  _Bug_ if you have discovered an issue 


*  _Task_ if you wish to request a documentation, sample or process (e.g. build system) enhancement or issue 


.  Then enter a _Summary_ , describing briefly the problem - please try to be descriptive! 


.  You should not set _Priority_ . 


.  Now, enter the version you are reporting an issue against in the _Affects Version_ field, and leave the _Fix Version_ field blank. 


.  In the _Environment_ text area, describe in as much detail as possible your environment (e.g. Java runtime and version, operating system, any network topology which is relevant). 

.  In the _Description_ field enter a detailed description of your problem or request. 

.  If the issue has been discussed on the forums or the mailing list, enter a reference in the _Forum Reference_ field 

.  Finally, hit _Create_ 

[[sid-68355157_ContributingtoInfinispan-VersioningGuidelines]]


==== Versioning Guidelines

[WARNING]
==== 
 Only Infinispan contributors should set the _Fix Version_ field. 


==== 


When setting the _Fix Version_ field for bugs and issues in JIRA, the following guidelines apply: 

Version numbers are defined as MAJOR.MINOR.MICRO.MODIFIER.  For example, 4.1.0.BETA1 would be:


|===============
|MAJOR|4
|MINOR|1
|MICRO|0
|MODIFIER|BETA1

|===============


 If the issue relates to a Task or Feature Request, please ensure that the .FINAL version is included in the Fixed In field.  For example, a new feature should contain 4.1.0.BETA1, 4.1.0.FINAL if it is new for 4.1.0 and was first made public in BETA1.  For example, see link:$$https://issues.jboss.org/browse/ISPN-299$$[ISPN-299] . 

 If the issue relates to a bug which affected a previous FINAL version, then the Fixed In field should also contain the .FINAL version which contains the fix, in addition to any ALPHA, BETA or CR release.  For example, see link:$$https://issues.jboss.org/browse/ISPN-546$$[ISPN-546] . If the issue pertains to a bug in the current release, then the .FINAL version should not be in the Fixed In field.  For example, a bug found in 4.1.0.ALPHA2 (but not in 4.1.0.ALPHA1) should be marked as fixed in 4.1.0.ALPHA3, but not in 4.1.0.FINAL.  For example, see link:$$https://issues.jboss.org/browse/ISPN-416$$[ISPN-416] . 

[[sid-68355157_ContributingtoInfinispan-SourcecontrolGit]]


=== Source control - Git

 Infinispan uses link:$$http://git-scm.com$$[git] , hosted on link:$$http://github.com$$[GitHub] , for version control. You can find the upstream git repository at link:$$https://github.com/infinispan$$[] . To clone the repository: 


----

$ git clone git@github.com:infinispan/infinispan.git

----

or to clone your fork:


----

$ git clone git@github.com:YOUR_GITHB_USERNAME/infinispan.git

----

 For more information, read <<sid-68355164,the Git chapter>> . 

[[sid-68355157_ContributingtoInfinispan-SettingupyourIDE]]


==== Setting up your IDE

Maven supports generating IDE configuration files for easy setup of a project. Tested are Eclipse, IntelliJ IDEA and Netbeans.

Before we import the project, we need to clone the project as described above.

[[sid-68355157_ContributingtoInfinispan-Eclipse]]


==== Eclipse

[[sid-68355157_ContributingtoInfinispan-]]


===== 


.  Install the m2eclipse plugin if you have not already installed it. Eclipse is including it since version "Indigo" 3.7, for older versions follow instructions at link:$$http://eclipse.org/m2e/$$[] . 


.  Import the Infinispan maven project. Select File -&gt; Import in your eclipse workbench. Select the Existing Maven Project importer. 


.TODO InformalFigure image title empty
image::[]


.  Select the root directory of your Infinispan checkout. 


.TODO InformalFigure image title empty
image::[]


. Select Infinispan modules that you want to import.


. Finally, from Infinispan 5.0 onwards, annotation processing is used to allow log messages to be internationalized. This processing can be done directly from Eclipse as part of compilation but it requires some set up:


.  Open the properties for infinispan-core and locate Annotation Processing 


.  Tick Enable project specific settings 


.  Enter target/generated-sources/annotations as the Generated source directory 


.TODO InformalFigure image title empty
image::[]

 Code Formatting. From the menu Window-&gt;Preferences-&gt; select Java -&gt; Code Style -&gt; Formatter. Import link:$$https://raw.github.com/infinispan/infinispan/master/ide-settings/eclipse/formatter.xml$$[formatter.xml] Code template. From the menu Window-&gt;Preferences-&gt; select Java -&gt; Code Style -&gt;  Code Templates. Import link:$$https://raw.github.com/infinispan/infinispan/master/ide-settings/eclipse/codetemplates.xml$$[codetemplates.xml] 

 Some modules use Scala, if you plan contributing to one of these modules it's worth installing the link:$$http://www.scala-lang.org/node/94$$[Scala tools] . 

[[sid-68355157_ContributingtoInfinispan-IntelliJIDEA]]


===== IntelliJ IDEA

[[sid-68355157_ContributingtoInfinispan-Importing]]


===== =Importing


*  When you start IntelliJ, you will be greeted by a screen as shown below: 
.TODO Gliffy image title empty
image::[]

 


*  If you have already obtained a copy of the Infinispan sources via Github (see _'Source Control'_ ), then simply follow: _Import Project -&gt; /directory/to/downloaded/sources_ . IntelliJ will automatically make use of maven to import the project since it will detect a _pom.xml_ file in the base directory. 


*  If you have not obtained the sources already, you can simply use the Git integration provided within IntelliJ 12. Click on _Check out from Version Control -&gt; Github_ . After entering your Github credentials, you will then be prompted to enter the git repository URL along with the location that you want to check out the source code to. 


.TODO InformalFigure image title empty
image::[]

[[sid-68355157_ContributingtoInfinispan-Compilersettings]]


===== =Compiler settings


* From Infinispan 5.0 onwards, annotation processing is used to allow log messages to be internationalized. This processing can be done directly from IntelliJ as part of compilation but it requires some set up:


*  Go to "Preferences/Compiler/Annotation Processor" and click on _Enable annotation processing_ 


*  Add an annotation processor with "Processor FQN Name" as org.jboss.logging.LoggingToolsProcessor 


*  In "Processed Modules", add all modules except the root and the parent modules. 
.TODO Gliffy image title empty
image::[]

 


*  There can sometimes be issues with the generated logging classes on rebuild (particularly when you switch Git branches). If these issues do crop up then simply run _mvn clean install -DskipTests=true_ on the command line to clear them out. 


*  _EXTRA:_ If you are running a multi-core environment (e.g. quad-core or above) then you can follow the instructions on making use of parallelized compilation in IntelliJ 12. Information on how to do this can be found link:$$http://blogs.jetbrains.com/idea/2012/12/intellij-idea-12-compiler-twice-as-fast/$$[here] . 

[[sid-68355157_ContributingtoInfinispan-ScalaPlugin]]


===== =Scala Plugin


*  You will need to download the Scala plugin for IntelliJ as well. This can be done by: _Project Settings -&gt; Plugins -&gt; Browse Repositories_ . Then run a search for 'Scala'. JetBrains themselves are the vendor for this plugin and more information on it can be found link:$$http://confluence.jetbrains.net/display/SCA/Scala+Plugin+for+IntelliJ+IDEA$$[here] . 


.TODO InformalFigure image title empty
image::[]


*  You also have to configure the Scala plugin to use the Scala compiler for Scala files and the Java compiler for Java files. You can do this by going into _Settings -&gt; Compiler -&gt; Scala Compiler_ . Be sure to add the scala compiler bundle as shown in the screenshot below. 


.TODO InformalFigure image title empty
image::[]

[[sid-68355157_ContributingtoInfinispan-x]]


===== =

[[sid-68355157_ContributingtoInfinispan-CodeStyle]]


===== =Code Style


*  You can find the code style .jar file for IntelliJ in the Infinispan source download. It is located in _/path/to/infinispan/home/ide-settings/intellij_ . 

[[sid-68355157_ContributingtoInfinispan-BuildMaven]]


=== Build - Maven

 Infinispan uses link:$$http://maven.apache.org/$$[Maven] for builds. Make sure you have Maven 3 installed, and properly configured. For more information, read link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=4784481$$[the Maven chapter] . 

[[sid-68355157_ContributingtoInfinispan-ContinuousIntegrationTeamCity]]


==== Continuous Integration - TeamCity

 Infinispan link:$$http://www.jetbrains.com/teamcity$$[TeamCity] for continuous integration. TeamCity polls GitHub for updates and runs whenever updates are available. You can check the status of the latest builds link:$$http://ci.infinispan.org/overview.html$$[here] . 

[[sid-68355157_ContributingtoInfinispan-TestingTestNG]]


=== Testing - TestNG

 Infinispan uses TestNG for unit and functional tests, and all Infinispan tests are run in parallel. For more information see <<sid-68355159,the Test Suite chapter>> ; this chapter gives advice on writing tests which can safely execute in parallel. 

[[sid-68355157_ContributingtoInfinispan-CommunicatingwithotherInfinispancontributors]]


=== Communicating with other Infinispan contributors

 Infinispan contributors use a mix of link:$$http://www.jboss.org/infinispan/mailinglists$$[mailings lists] and link:$$http://www.jboss.org/infinispan/community.html$$[IRC] to communicate ideas and designs, with more detailed designs often making their way into link:$$http://community.jboss.org/$$[wiki pages] . 

[[sid-68355157_ContributingtoInfinispan-StyleRequirements]]


=== Style Requirements

 Infinispan uses the link:$$http://en.wikipedia.org/wiki/Indent_style#K.26R_style$$[K&amp;R code style] for all Java source files, with two exceptions: 


* use 3 spaces instead of a tab character for indentations.


* braces start on the same line for class, interface and method declarations as well as code blocks.

 In addition, sure all link:$$http://en.wikipedia.org/wiki/Newline$$[new line characters] used must be LF (UNIX style line feeds). Most good IDEs allow you to set this, regardless of operating system used. 

 All patches or code committed must adhere to this style. Code style settings which can be imported into IntelliJ IDEA and Eclipse are committed in the project sources, in link:$$https://github.com/infinispan/infinispan/blob/master/ide-settings/$$[ide-settings] . 

[[sid-68355157_ContributingtoInfinispan-Spelling]]


==== Spelling

 Ensure correct spelling in code, comments, Javadocs, etc. (use _American English_ spelling). It is recommended that you use a spellchecker plugin for your IDE. 

[[sid-68355157_ContributingtoInfinispan-Licenseheader]]


==== License header

 All source files must have up-to-date license headers as described in link:$$http://community.jboss.org/docs/16352$$[Copyright Ownership and Licenses] . Never remove existing headers or copyrights. 

[[sid-68355157_ContributingtoInfinispan-Checkincomments]]


==== Check-in comments

 Please ensure any commit comments use link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=68355224_InfinispanandGitHub-Comments$$[this format] if related to a task or issue in JIRA. This helps JIRA pick out these checkins and display them on the issue, making it very useful for back/forward porting fixes. If your comment does not follow this format, your commit may not be merged into upstream. 

[[sid-68355157_ContributingtoInfinispan-Configuration]]


=== Configuration

 Infinispan offers both programmatic configuration and XML configuration. For more information read the <<sid-68355165,Configuration>> chapter. 

[[sid-68355157_ContributingtoInfinispan-Logging]]


=== Logging

 Infinispan follows the JBoss logging standards, which can be found link:$$https://community.jboss.org/wiki/LoggingStandards$$[here] . 

 From Infinispan 5.0 onwards, Infinispan uses JBoss Logging to abstract over the logging backend. Infinispan supports localization of log message for categories of INFO or above as explained in link:$$http://community.jboss.org/docs/16738$$[the JBoss Logging guidelines] . As a developer, this means that for each INFO , WARN , ERROR , FATAL message your code emits, you need to modify the Log class in your module and add an explicit method for it with the right annotations. For example: 


----

@LogMessage(level = INFO)
@Message(value = "An informative message: %s - %s", id = 600)
void anInformativeMessage(String param1, String param2);

----

 And then, instead of calling log.info(...) , you call the method, for example log.anInformativeMessage(param1, param2) . If what you're trying to log is an error or similar message and you want an exception to be logged as cause, simply use @Cause annotation, example: 


----

@LogMessage(level = ERROR)
@Message(value = "An error message: %s", id = 600)
void anErrorMessage(String param1, @Cause IllegalStateException e);

----

The last thing to figure out is which id to give to the message. Each module that logs something in production code that could be internationalized has been given an id range, and so the messages should use an available id in the range for the module where the log call resides. Here are the id range assignments per module:

[options="header"]
|===============
|Module name|Id range
|core|1 - 1000
|tree|2001 - 3000
|bdbje cache store|2001 - 3000
|cassandra cache store|3001 - 4000
|hotrod client|4001 - 5000
|server core|5001 - 6000
|server hotrod|6001 - 7000
|cloud cache store|7001 - 8000
|jdbc cache store|8001 - 9000
|jdbm cache store|9001 - 10000
|remote cache store|10001 - 11000
|server memcached|11001 - 12000
|server rest|12001 - 13000
|server websocket|13001 - 14000
|query|14001 - 15000
|lucene directory|15001 - 16000
|rhq plugin|16001 - 17000
|cdi integration|17001 - 18000
| hbase cache store | 18001 - 19000 
| cli interpreter | 19001 - 20000 
| cli client | 20001 - 21000 
|mongodb cache store|21001 - 22000
|jpa cache store|22001 - 23000
|leveldb cache store|23001 - 24000
|couchbase cache store|24001 - 25000

|===============



[NOTE]
==== 
When editing the above table, remember to update the README-i18n.txt file in the project sources!


==== 



[NOTE]
==== 
You will need to enable annotation processing in order to be able to compile Infinispan and have the logger implementation generated.


==== 


