[[sid-68355208]]

==  Upgrading from 5.1 to 5.2

[[sid-68355208_Upgradingfrom5.1to5.2-Declarativeconfiguration]]


=== Declarative configuration

In order to use all of the latest features, make sure you change the namespace declaration at the top of your XML configuration files as follows:


----

<infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:infinispan:config:5.2 http://www.infinispan.org/schemas/infinispan-config-5.2.xsd" xmlns="urn:infinispan:config:5.2">
   ...
</infinispan>

----

[[sid-68355208_Upgradingfrom5.1to5.2-Transaction]]


=== Transaction

 The default transaction enlistment model has changed ( link:$$https://issues.jboss.org/browse/ISPN-1284$$[ISPN-1284] ) from link:$$http://docs.oracle.com/javase/1.4.2/docs/api/javax/transaction/xa/XAResource.html$$[XAResounce] to link:$$http://docs.oracle.com/javaee/5/api/javax/transaction/Synchronization.html$$[Synchronization] . Also now, if the link:$$http://docs.oracle.com/javase/1.4.2/docs/api/javax/transaction/xa/XAResource.html$$[XAResounce] enlistment is used, then link:$$https://docs.jboss.org/author/display/ISPN/Transaction+recovery$$[recovery] is enabled by default. 

In practical terms, if you were using the default values, this should not cause any backward compatibility issues but an increase in performance of about 5-7%. However in order to use the old configuration defaults, you need to configure the following:


----

<transaction useSynchronization="false">
   <recovery enabled="false"/>
</transaction>

----

or the programmatic configuration equivalent:


----

ConfigurationBuilder builder = new ConfigurationBuilder();
builder.transaction().useSynchronization(false).recovery().enabled(false)

----

[[sid-68355208_Upgradingfrom5.1to5.2-CacheLoaderandStoreconfiguration]]


=== Cache Loader and Store configuration

 Cache Loader and Store configuration has changed greatly in Infinispan 5.2. Please refer to the link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737103$$[Cache Loaders and Stores] documentation. 

[[sid-68355208_Upgradingfrom5.1to5.2-VirtualNodes%3ESegments]]


=== Virtual Nodes &gt; Segments

 The concept of Virtual Nodes doesn't exist anymore in Infinispan 5.2 and has been replaced by Segments. Please refer to the link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737115$$[Clustering modes] documentation 

