== Upgrading from 15.1 to 15.2

=== Native Server
The native server and its associated `quay.io/infinispan/server-native` images are no longer provided. User should
use the JVM based server instead as it provides significant performance issues over its native counterpart, without 
compromising on features, and is fully supported.

=== Default Index startup mode is now AUTO

The default used to be `NONE`, meaning that no actions at cache startup time are taken in case
potential index data inconsistencies are detected from the cache configuration.
With `AUTO`, for instance, a purge is automatically triggered if the cache is not persistent while the indexes are.
For complete detail see link:{query_docs}#indexing-configuration_startup-mode[Index startup mode].

=== Server Endpoints
All server endpoints (HotRod, RESP, Memcached & REST) now support a default `max-content-length` of 10 MB for each
request by default. That means if a request is larger than this size it will be rejected by the server. If you
need to increase this limit please set the value explicitly in the server configuration.

