== Upgrading from 13.0 to 14.0

=== Security authorization SPI

`org.infinispan.security.PrincipalRoleMapperContext` is deprecated in 14.0 and replaced by `org.infinispan.security.AuthorizationMapperContext`.

=== Scattered cache deprecation

The scattered cache mode is deprecated in 14.0 and will be removed in 16.0.


=== Cross Site Replication

==== Asynchronous backup strategy logging

By default, the asynchronous backup strategy logs exceptions that occur on remote sites.
To disable exceptions for async backup operations, set `failure-policy="IGNORE"` in your configuration as follows:

[source,xml,options="nowrap",subs=attributes+]
----
<backup site="NYC" strategy="ASYNC" failure-policy="IGNORE" />
----

=== Store properties

Store provided properties are no longer allowed to override store explicit configuration.

For example the below configuration would set the read only configuration of the store to true.

[source,xml,options="nowrap",subs=attributes+]
----
<persistence>
  <file-store>
    <index path="testCache/index" />
    <data path="testCache/data" />
    <property name="readOnly">true</property>
  </file-store>
</persistence>
----

Now the readOnly property is only provided to the store itself and does not affect the store explicit configuration.
The same configuration should be changed to the following instead.

[source,xml,options="nowrap",subs=attributes+]
----
<persistence>
  <file-store read-only="true">
    <index path="testCache/index" />
    <data path="testCache/data" />
  </file-store>
</persistence>
----

=== Fetch Persistent State Remove

The store property named fetch-persistent-state has been deprecated and removed from xml configuration.
Instead, the first configured non-shared store that allows for bulk loading will be used for state transfer of entries.
This reduces configuration complexity and does not allow for a configuration that could lose data due to not
transferring entries stored in a store.

NOTE: This change has no effect for shared stores

=== RocksDB store

The RocksDB cache store is no longer included by default with the server.
You must install both the {brandname} RocksDB module and the RocksDB native library using the CLI:

[source,shell,options="nowrap",subs=attributes+]
----
[disconnected]> install org.infinispan:infinispan-cachestore-rocksdb:{ispn_version}
[disconnected]> install org.rocksdb:rocksdbjni:{rocksdbversion}
----

=== JDBC Store database versions configuration deprecated

Previously, it was possible to specify the database major and minor versions when configuring the database parameters.
These two options are now deprecated and ignored as they are always retrieved from the JDBC metadata directly.
This affects all three of the JDBC based stores (string-keyed-jdbc-store, table-jdbc-store and query-jdbc-store).

=== Micrometer Metrics

Microprofile metrics are no longer supported, available output metrics are now Prometheus and OpenMetrics.

The implementation relies on Micrometer library, for more information see
the link:../server/server.html#configuring-metrics_statistics-jmx[Configuring Infinispan metrics].

=== Jakarta EE compatible jars available

{brandname} now distributes Jakarta EE based jars.
This is in addition to the javax compatible jars.

Some modules that have Jakarta based jars are the following (note there are quite a few more, these are some prime examples)

* infinispan-commons
* infinispan-core
* infinispan-multimap
* infinispan-query
* infinispan-client-hotrod
* infinispan-api

If your application requires using the jakarta instead of javax namespace all you need to do is to append your dependencies with `-jakarta`.

[source,xml,options="nowrap",subs=attributes+]
----
<dependency>
   <groupId>org.infinispan</groupId>
   <artifactId>infinispan-client-hotrod-jakarta</artifactId>
</dependency>
----

=== Hibernate 6.0 2LC Update

Hibernate 6.0 is now supported and is the only implementation supported moving forward.
If Hibernate 5.3 support is needed, you must use an older version of Infinispan.

=== JPAStore has been removed

The JPAStore has been removed in Infinispan 14.0.
It is suggested instead to use the new SQL Table or Query Stores that were added in Infinispan 13.0.

=== Query API

==== {brandname} native annotations

This release introduces new indexing annotations: `@Indexed`, `@Basic`, `@Decimal`, `@Keyword`, `@Text`, and `@Embedded`.
Each of the annotations supports a set of attributes that you can use to further describe how the entity is indexed.

These new annotations replaced Hibernate Search annotations which means that you are no longer required to annotate your Java classes with the `@ProtoDoc` annotation for remote caches.
Any annotations will be copied as comments to the generated `.proto` files.

The following table summarizes the mapping of fields between Hibernate Search 5 (HS5) annotations and {brandname} native annotations:

[%header,cols=4*]
|===
| HS5 annotations | Indexing attributes| {brandname} native annotations| Description

| `@Field(index=Index.YES)` | `searchable` | `@Basic`, `@Decimal`, `@Keyword`, `@Text` |Fields previously marked as indexed are now searchable.

| `@Field(store = Store.YES)` | `projectable = true` | `@Basic`, `@Decimal`, `@Keyword`, `@Text`| Fields previously marked as stored are now projectable.

| type `String && @Field(analyze = Analyze.YES)` | `analyzer = "<definition>"`| `@Text`| String fields that were marked with analyzer definitions remain being analyzed during indexing.

| `@Field(analyze = Analyze.NO) && (@Field(store = Store.YES) OR @Field(sortable = Sortable.YES))` | `sortable = true` | `@Basic`, `@Decimal`, `@Keyword`| Fields that were not analyzed but were either stored in the index or marked as sortable are now considered sortable.

| N/A | `aggregable = true`| `@Basic`, `@Decimal`, `@Keyword`| Performing aggregation operations using the Hibernate 5 Search annotations was not possible.

| N/A | `normalizer = "lowercase"`| `@Keyword`| Mapping fields that were analyzed or normalized is not possible due to the potential data loss in the process.
|===

=== Query efficiency

The default for maximum results returned by a query that was present in Infinispan 12.1.5.Final and earlier versions has been restored.
You can now change the default limit by setting the `default-max-results` cache property.
The default value of default-max-results is 100.
Limiting the number of results returned by a query significantly improves performance of queries that do not have an explicit limit set.

=== The (undocumented) server filesystem-realm has been removed

The `filesystem-realm`, an experimental feature which has never been documented, has been removed.

