== Upgrading from 9.3 to 9.4

=== Client/Server changes

==== Compatibility mode deprecation

Compatibility mode has been deprecated and will be removed in the next {brandname} version.

To use a cache from multiple endpoints, it is recommended to store data in binary format and to configure the MediaType for keys and values.


If storing data as unmarshalled objects is still desired, the equivalent of compatibility mode is to configure keys and values to store object content:

[source,xml]
----
<encoding>
   <key media-type="application/x-java-object"/>
   <value media-type="application/x-java-object"/>
</encoding>
----

==== Memcached storage

For better interoperability between endpoints, the Memcached server no longer stores keys as `java.lang.String`, but as UTF-8 `byte[]`.

If using memcached, it is recommended to run a rolling upgrade from 9.3 to store data in the new format, or reload the data in the cache.

==== Scripts Response

Distributed scripts with text-based data type no longer return `null` when the result from each server is null.
The response is now a JSON array with each individual result, for example `"[null, null]"`

==== WebSocket endpoint removal
The WebSocket endpoint has been unmaintained for several years. It has been removed.

==== Hot Rod client connection pool properties
Since the Hot Rod client was overhauled in 9.2, the way the connection pool configuration is handled has changed.
Infinispan 9.4 introduces a new naming scheme for the connection pool properties which deprecates the old _commons-pool_
names. For a complete reference of the available configuration options for the properties file please refer to
link:../../apidocs/org/infinispan/client/hotrod/configuration/package-summary.html#package.description[remote client configuration] javadoc.

==== Server thread pools
The threads that handle the child Netty event loops have been renamed from *-ServerWorker to *-ServerIO

=== Persistence Changes

==== Shared and Passivation

A store cannot be configured as both shared and having passivation enabled.
Doing so can cause data inconsistencies as there is no way to synchronize
data between all the various nodes. As such this configuration will now
cause a startup exception. Please update your configuration as appropriate.

=== Query changes

==== AffinityIndexManager

The default number of shards is down to `4`, it was previously equals to the number of segments in the cache.

