== Server templates

The internal server templates have been removed.

== Upgrading from 14.0 to 15.0

=== Deprecations, removals and moved classes

==== Moved

* The `org.infinispan.util.TimeoutException` has been moved to `org.infinispan.commons.TimeoutException`
* `org.infinispan.util.concurrent.IsolationLevel` has been moved to `org.infinispan.configuration.cache.IsolationLevel`

==== Removed

* All: Parsing of configuration files with schema < 10.0
* Commons: `Start.priority` and `Stop.priority`
* Core: `AdvancedCache.with(ClassLoader)`, `AdvancedCache.getEvictionManager()`, `AdvancedCache.getAsyncInterceptorChain()`, `AdvancedCache.getComponentRegistry()`
* Core: `AnyScopeComponentFactory.construct(Class)`
* Core: `Cache.getListeners()`
* Core: `ConfigurationBuilder.classLoader()`, `ConfigurationBuilder.customInterceptors()`
* Core: `DataRehashedEvent.getUnionConsistentHash()`
* Core: `EmbeddedCacheManager.getListeners()`, `EmbeddedCacheManager.getTransport()`, `EmbeddedCacheManager.removeCache(String)`, `EmbeddedCacheManager.getGlobalComponentRegistry()`
* Core: `FlagAffectedCommand.setFlags`, `FlagAffedctedCommand.addFlags`, `FlagAffectedCommand.hasFlag`
* Core: `IntCacheStream.filterKeySegments(Set<Integer>)`
* Core: `JMXStatisticsConfiguration`
* Core: `GlobalConfiguration.DEFAULT_MARSHALL_VERSION`
* Core; `LocalizedCacheTopology.getDistributionForSegment(int)`
* Core: `NamedComponentFactory`
* Core: `PersistenceUtil.loadAndStoreInDataContainer`
* Core: `TopologyChangedEvent.getConsistentHashAtStart()` and `TopologyChangedEvent.getConsistentHashAtEnd()`
* Core: `Transport.invokeRemotely()` `Transport.waitForView()` `Transport.backupRemotely()` `AbstractTransport`
* Core: `ValueMatcher.nonExistentEntryCanMatch`
* Core: `WriteCommand.updateStatusFromRemoteResponse`
* Core: state transfer pool
* Counters: `SyncStrongCounter` and `SyncWeakCounter`
* Hot Rod client: `org.infinispan.client.hotrod.marshall.ProtoStreamMarshaller`
* Server and clients: keystore certificate password
* RocksDB Store: expiry queue size
* Remote Store: transport factory and maxIdle


=== Metrics

The JGroups and cross-site metrics name changed when `names-as-tags` is set to `true`,
where the cluster's name and the site's name are no longer present in the metrics name but as a tag.

As an example, when you set `names-as-tags` to `false`, metrics are named based on the channel, resulting in multiple metrics for the same purpose:

[source]
----
# TYPE vendor_jgroups_xsite_frag4_get_number_of_sent_fragments gauge
# HELP vendor_jgroups_xsite_frag4_get_number_of_sent_fragments Number of sent fragments
vendor_jgroups_xsite_frag4_get_number_of_sent_fragments{cluster="xsite",node="..."} 0.0
# TYPE vendor_jgroups_cluster_frag4_get_number_of_sent_fragments gauge
# HELP vendor_jgroups_cluster_frag4_get_number_of_sent_fragments Number of sent fragments
vendor_jgroups_cluster_frag4_get_number_of_sent_fragments{cluster="cluster",node="..."} 2.0
----

When you set `names-as-tags` to `true`, metrics are simplified, and cluster and site names appear as tags:

[source]
----
# TYPE vendor_jgroups_frag4_get_number_of_sent_fragments gauge
# HELP vendor_jgroups_frag4_get_number_of_sent_fragments Number of sent fragments
vendor_jgroups_frag4_get_number_of_sent_fragments{cache_manager="default",cluster="xsite",node="..."} 0.0
vendor_jgroups_frag4_get_number_of_sent_fragments{cache_manager="default",cluster="cluster",node="..."} 2.0
----

=== SecurityManager

Aligning with the deprecation for removal of the `SecurityManager` since JDK 17, integration with a
`SecurityManager` is no longer supported.

=== Jakarta and Java EE
* Infinispan has been updated to use `jakarta.*` packages only.
* If you require the legacy `javax.*` packages, you should utilise Infinispan 14.0.x.
* The transitional `*-jakarta` jars, which included both `jakarta.*` and `javax.*` packages, have been removed.

=== Removals

* The Kryo and Protostuff marshallers have been removed.
* Extended Statistics module have been removed.
* JCache support.
* Spring 5.x and Spring Boot 2.x support.
* Wildfly modules are no longer provided.

=== Hot Rod client defaults
{brandname} introduced changes to the properties of the Hot Rod client.

.`ssl_hostname_validation`
A new property, `ssl_hostname_validation` with a default value of `true`.
This property enables TLS hostname validation based on RFC 2818 rules.
Additionally, setting the `sni_host_name` is now required when hostname validation is enabled.

.Default property changes

[cols="2,1,1"]
|===
|Property |{brandname} 15 |Previous versions

| `connect_timeout`
| *2000 ms / 2 seconds*
| 60000 ms / 60 seconds

| `socket_timeout`
| *2000 ms / 2 seconds*
| 60000 ms / 60 seconds

| `max_retries`
| *3*
| 10

| `min_evictable_idle_time`
| *180000 ms / 3 minutes*
| 1800000 ms / 30 minutes

| `sasl_mechanism`
| *SCRAM-SHA-256*
| SCRAM-SHA-512
|===

=== RESP Endpoint

* Default expiration may be applied to the cache configuration used by the RESP endpoint

=== Search

==== Indexing

* The `property` attribute has been removed.

* The `auto-config` attribute has been removed.

* The `index` attribute has been removed.

=== Indexing annotations

* The support for the old Hibernate Search 5 annotations have been removed

* `@ProtoDoc`, no longer required since 14.0, is now deprecated

=== Security

The principal role mapper now applies only to groups instead of both groups and user principals.
Use the `cache-manager.security.authorization.group-only-mapping=false` configuration to use the old behavior.

=== Scattered cache removal

The scattered cache mode have been removed. Use Distributed caches instead.

=== Global State

Infinispan will now refuse to start if a dangling lock file is found in the persistent global state, indicating
an unclean shutdown. The behavior can be changed by configuring the global state `unclean-shutdown-action` setting.

=== Persistence
The default `availability-interval` has been increased to 30 seconds. The previous default was 1 second.

==== SoftIndexFileStore

The index segment configuration is no longer used and instead the number of segments is determined solely by the number of cache segments.

=== RESP endpoint

The RESP endpoint cache now requires the key storage media type to be
application/octet-stream.

=== Client listeners remove events

Client listeners remove events will now be propagated even if the remove did not remove a value.
This is required to properly support new changes around the new `includeOldValue` method on `CacheEventConverter`.
NOTE: Remote events do not include any values by default

=== NearCache SPI

Due to inconsistency issues with concurrent updates the NearCache SPI needed to be updated to have concurrent
based methods to prevent an issue where a stale entry may have been saved in the near cache.
For more information please see link:https://issues.jboss.org/browse/ISPN-13612[ISPN-13612]

