== Upgrading from 11.x or 12.0 to 12.1

  If you are upgrading from 11.x to 12.1, you should also review the 11.0 to 12.0 upgrade notes.

=== Upgrading Deployments with Single File Cache Store Persistence

When upgrading Infinispan to 12.1, caches that include a `SingleFileStore` persistence configuration can encounter an issue that leads to data corruption.

This issue affects upgrades to Infinispan 12.1.0.Final through 12.1.4.Final only.
As of Infinispan 12.1.5.Final this issue no longer occurs during upgrade.

If you have already upgraded from 11.x to 12.1, you should do the following as soon as possible:

. Back up any `$ISPN_HOME/server/data/*.dat` files.
. Upgrade to Infinispan 12.1.5.Final or later.

After successful upgrade, Infinispan recovers any corrupted data and restores the Single File Store on first start.

.Cross-site replication state transfer

For caches that backup to other clusters via cross-site replication, you should perform a state transfer after upgrading to 12.1.

From the Infinispan CLI use the `site push-site-state` command as follows:

[source,options="nowrap",subs=attributes+]
----
[//containers/default]> site push-site-state --cache=cacheName --site=NYC
----


=== JGroups configuration changes

==== Message bundler
The default JGroups bundler has changed from
"no-bundler" (a thread sending a message writes it to the TCP socket or sends the UDP datagram directly) to
"transfer-queue" (a thread sending a message only adds the message to a queue, and a separate
bundler thread groups the messages in "batches" then sends the batches).

=== Encoding

* `org.infinispan.commons.dataconversion.Encoder` has been deprecated and will be removed in a future version.

=== Authorization

A new `CREATE` permission has been introduced, with the following effects:
* users now require the `CREATE` permission to be able to create/remove caches/counters/locks instead of the `ADMIN` permission
* it supersedes the internal `___schema_manager` role, which has now been deprecated. It is required in order to add/remove schemas.
* it supersedes the internal `___script_manager` role, which has now been deprecated. It is required in order to add/remove scripts.

==== Server

Authorization is now enabled out-of-the-box in the default server configuration.
Authorization only applies to "global" operations (administrative and management), so normal cache usage is unaffected.
You can revert to the previous behavior by removing the `<authorization>` element from the `<cache-container>` configuration.

The default logging configuration now includes an audit logging which is disabled by default.

=== Server Trust Store

The trust store configuration is now part of the server identity to allow client certificate validation
without requiring authentication. Adding a `truststore-realm` will reference the identity's trust store.

[source,xml]
----
<!-- 12.0 -->
<security-realm name="default">
   <server-identities>
      <ssl>
         <keystore path="server.pfx"
                   keystore-password="password" alias="server"/>
      </ssl>
   </server-identities>
   <truststore-realm path="trust.pfx" password="secret"/>
</security-realm>
----

[source,xml]
----
<!-- 12.1 -->
<security-realm name="default">
   <server-identities>
      <ssl>
         <keystore path="server.pfx"
                   keystore-password="password" alias="server"/>
         <truststore path="trust.pfx" password="secret"/>
      </ssl>
   </server-identities>
   <truststore-realm/>
</security-realm>
----


