== Upgrading from 9.2 to 9.3

=== AdvancedCacheLoader changes
The `AdvancedCacheLoader` SPI has been enhanced to provide an alternative method to process and instead allows reactive streams based `publishKeys` and `publishEntries` methods which provide benefits in performance, threading and ease of use. Note this change will only affect you if you wish take advantage of it in any custom CacheLoaders you may have implemented.

=== Partition Handling Configuration
In 9.3 the default `MergePolicy` is now `MergePolicy.NONE`, opposed to `MergePolicy.PREFERRED_ALWAYS`.

=== Stat Changes
The stat changes introduced in 9.1 have been reverted, so average values for read, write, and removals are once again returned
as milliseconds.

=== Event log changes
Several new event log messages have been added, and one message has been removed (ISPN100013).

=== Max Idle Expiration Changes
The max idle entry expiration information is sent between owners in the cluster. However when an entry expires via max idle on a given node, this was not replicated (only removing it locally). Max idle has been enhanced to now expire an entry across the entire cluster, instead of per node. This includes ensuring that max idle expiration is applied across all owners (meaning if another node has accessed the entry within the given time it will prevent that entry from expiring on other nodes that did not have an access).

Max idle in a transactional clustered cache does not remove expired entries on access (although it will not be returned). These entries are only removed via the expiration reaper.

Iteration in a clustered cache will still show entries that are expired via maxIdle to ensure good performance, but could be removed at any point due to expiration reaper.

=== WildFly Modules
The {brandname} WildFly modules are now located in the `system/add-ons/{moduleprefix}` dir as per the
link:https://developer.jboss.org/wiki%20/LayeredDistributionsAndModulePathOrganization[WildFly module conventions].

=== Deserialization Allow list

Deserialization of content sent by clients to the server are no longer allowed by default.
This applies to JSON, XML, and marshalled `byte[]` that, depending on the cache configuration, will cause the server
to convert it to Java Objects either to store it or to perform any operation that cannot be done on a `byte[]` directly.

The deserialization needs to be enabled using system properties, ether by class name or regular expressions:

[source]
----
// Comma separated list of fully qualified class names
-Dinfinispan.deserialization.allowlist.classes=java.time.Instant,com.myclass.Entity

// Regex expression
-Dinfinispan.deserialization.allowlist.regexps=.*
----

