[id='eviction_strategies_{context}']
[[eviction_strategies]]
= Eviction Strategies

`NONE`::
Eviction is not enabled and it is assumed that the user will not invoke evict directly
on the cache. If passivation is enabled this will cause aa warning message to be
emitted. This is the default strategy.

`MANUAL`::
This strategy is just like <b>NONE</b> except that it asssumes the user will be
invoking evict directly. This way if passivation is enabled no warning message
is logged.

`REMOVE`::
This strategy will actually evict "old" entries to make room for incoming ones.

Eviction is handled by link:https://github.com/ben-manes/caffeine[Caffeine] utilizing
the TinyLFU algorithm with an additional admission window.  This was chosen as
provides high hit rate while also requiring low memory overhead.  This provides a
better hit ratio than LRU while also requiring less memory than LIRS.

`EXCEPTION`::
This strategy actually prevents new entries from being created by throwing
a `ContainerFullException`. This strategy only works with transactional caches
that always run with 2 phase commit, that is no 1 phase commit or synchronization
optimizations allowed.
