name: Create Jira Ticket
description: Create Jira Ticket

inputs:
  token:
    description: 'The Jira bearer token used to authenticate'
    required: true
  project:
    description: 'The name of the Jira Projec to create the issue for'
    required: true
  summary:
    description: 'The Jira summary'
    required: true
  type:
    description: 'The type of Jira to create'
    required: true
  description:
    description: 'The Jira description'
  pullRequest:
    description: 'The url of a Pull Request to be added to the Jira ticket'

runs:
  using: "composite"
  steps:
    - name: Create Jira Ticket
      shell: bash
      run: |
        BASE_URL=https://issues.redhat.com
        API_URL=${BASE_URL}/rest/api/2/

        cat << EOF > headers
        Authorization: Bearer ${{ inputs.token }}
        Content-Type: application/json
        EOF

        PROJECT=$(curl -H @headers $API_URL/project/${{ inputs.project }})
        PROJECT_ID=$(echo ${PROJECT} | jq -r .id)
        ISSUE_TYPE_ID=$(echo ${PROJECT} | jq -r '.issueTypes[] | select(.name=="${{ inputs.type }}").id')

        cat << EOF > create-jira.json
        {
          "fields": {
            "project": {
              "id": "${PROJECT_ID}"
            },
            "summary": "${{ inputs.summary }}",
            "description": "${{ inputs.description }}",
            "customfield_12310220": "${{ inputs.pullRequest }}",
            "issuetype": {
              "id": "${ISSUE_TYPE_ID}"
            }
          }
        }
        EOF

        JIRA_KEY=$(curl -H @headers --data @create-jira.json $API_URL/issue | jq -r .key)
        echo "JIRA_TICKET_URL=${BASE_URL}/browse/${JIRA_KEY}" >> $GITHUB_ENV
