BACKUP(1)
========
:doctype: manpage


NAME
----
backup - manage container backup creation and restoration.


SYNOPSIS
--------
*backup create* ['OPTIONS']

*backup delete* ['OPTIONS'] `BACKUP_NAME`

*backup get* ['OPTIONS'] `BACKUP_NAME`

*backup ls*

*backup restore* ['OPTIONS'] `BACKUP_PATH`


BACKUP CREATE OPTIONS
---------------------
*-d, --dir*='PATH'::
Specifies a directory on the server to create and store the backup archive.

*-n, --name*='NAME'::
Defines a name for the backup archive.

*--caches*='cache1,cache2,...'::
Lists caches to back up. Use '*' to back up all caches.

*--cache-configs*='config1,config2,...'::
Lists cache configurations to back up. Use '*' to back up all cache configurations.

*--counters*='counter1,counter2,...'::
Lists of counters to back up. Use '*' to back up all counters.

*--proto-schemas*='schema1,schema2,...'::
Lists Protobuf schemas to back up. Use '*' to back up all schemas.

*--scripts*='script1,script2,...'::
Lists scripts to back up. Use '*' to back up all scripts.


BACKUP GET OPTIONS
------------------
*--no-content*::
Does not download content. The command returns only when the backup operation is complete.


BACKUP RESTORE OPTIONS
----------------------
*-u, --upload*::
Defines the path to a local backup archive that is uploaded to the server.

*--caches*='cache1,cache2,...'::
Lists caches to restore. Use '*' to restore all caches from the backup archive.

*--cache-configs*='config1,config2,...'::
Lists cache configurations to restore. Use '*' to restore all cache configurations from the backup archive.

*--counters*='counter1,counter2,...'::
Lists counters to restore. Use '*' to restore all counters from the backup archive.

*--proto-schemas*='schema1,schema2,...'::
Lists Protobuf schemas to restore. Use '*' to restore all schemas from the backup archive.

*--scripts*='script1,script2,...'::
Lists scripts to restore. Use '*' to restore all scripts from the backup archive.


EXAMPLES
--------
`backup create -n example-backup` +
Initiates a backup of all container content with name `example-backup`.

`backup create -d /some/server/dir` +
Initiates a backup of all container content and stores it on the server at path `/some/server/dir`.

`backup create --caches=* --cache-configs=*` +
Initiates a backup that contains only cache and cache configuration resources.

`backup create --proto-schemas=schema1,schema2` +
Initiates a backup that contains the named schema resources only.

`backup ls` +
Lists all backups available on the server.

`backup get example-backup` +
Downloads the `example-backup` archive from the server. If the backup operation is in progress, the command waits for it to complete.

`backup restore /some/path/on/the/server` +
Restores all content from a backup archive on the server.

`backup restore -u /some/local/path` +
Restores all content from a local backup archive that is uploaded to the server.

`backup restore /some/path/on/the/server --caches=*` +
Restores only cache content from a backup archive on the server.

`backup restore /some/path/on/the/server --proto-schemas=schema1,schema2` +
Restores only the named schema resources from a backup archive on the server.

`backup delete example-backup` +
Deletes the `example-backup` archive from the server.


SEE ALSO
--------
drop(1)
