SITE(1)
=======
:doctype: manpage


NAME
----
site - manages backup sites and performs cross-site replication operations.


SYNOPSIS
--------
*site status* ['OPTIONS']

*site bring-online* ['OPTIONS']

*site take-offline* ['OPTIONS']

*site push-site-state* ['OPTIONS']

*site cancel-push-state* ['OPTIONS']

*site cancel-receive-state* ['OPTIONS']

*site push-site-status* ['OPTIONS']


OPTIONS
-------
*-c, --cache*='CACHE_NAME'::
Specifies a cache. Defaults to the currently selected cache.

*-s, --site*='SITE_NAME'::
Specifies a site.


EXAMPLES
--------
`site status -s SITE_A` +
Returns the status for `SITE_A`.

`site bring-online --cache=mycache --site=SITE_A` +
Brings the `mycache` cache online at `SITE_A`.

`site take-offline --cache=mycache --site=SITE_B` +
Takes the `mycache` cache offline at `SITE_B`.

`site push-site-state --site=SITE_B` +
Push the state of all caches to the backup site `SITE_B`.

`site push-site-status --site=SITE_B` +
Displays the current status of the push to the backup site `SITE_B`.

`site cancel-push-state --site=SITE_B` +
Cancels the operation to push state to the backup site `SITE_B`.

`site cancel-receive-state --site=SITE_A` +
Cancels the operation to receive state from a remote site.
