SITE(1)
=======
:doctype: manpage


NAME
----
site - manages backup locations and performs cross-site replication operations.


SYNOPSIS
--------
*site status* ['OPTIONS']

*site bring-online* ['OPTIONS']

*site take-offline* ['OPTIONS']

*site push-site-state* ['OPTIONS']

*site cancel-push-state* ['OPTIONS']

*site cancel-receive-state* ['OPTIONS']

*site push-site-status* ['OPTIONS']


OPTIONS
-------
*--cache*='CACHE_NAME'::
Specifies a cache.

*--site*='SITE_NAME'::
Specifies a backup location.


EXAMPLES
--------
`site status --cache=mycache` +
Returns the status of all backup locations for `mycache`.

`site status --cache=mycache --site=NYC` +
Returns the status of `NYC` for `mycache`.

`site bring-online --cache=mycache --site=NYC` +
Brings the site `NYC` online for `mycache`.

`site take-offline --cache=mycache --site=NYC` +
Takes the site `NYC` offline for `mycache`.

`site push-site-state --cache=mycache --site=NYC` +
Backs up caches to remote backup locations.

`site push-site-status --cache=mycache` +
Displays the status of the operation to backup `mycache`.

`site cancel-push-state --cache=mycache --site=NYC` +
Cancels the operation to backup `mycache` to `NYC`.

`site cancel-receive-state --cache=mycache --site=NYC` +
Cancels the operation to receive state from `NYC`.

`site clear-push-state-status --cache=myCache` +
Clears the status of the push state operation for `mycache`.
