[[sid-68355196]]

==  Hot Rod

 _Hot Rod_ is the name of Infinispan's custom TCP client/server protocol which was created in order to overcome the deficiencies of other client/server protocols such as Memcached. HotRod, as opposed to other protocols, has the ability of handling failover on an Infinispan server cluster that undergoes a topology change. To achieve this, the Hot Rod regularly informs the clients of the cluster topology. 

Hot Rod enables clients to do smart routing of requests in partitioned, or distributed, Infinispan server clusters. This means that Hot Rod clients can determine the partition in which a key is located and communicate directly with the server that contains the key. This is made possible by Infinispan servers sending the cluster topology to clients, and the clients using the same consistent hash as the servers.

[[sid-68355196_HotRod-Moreresources]]


=== More resources


*  Information about the <<sid-68355113,first version>> of the protocol 


*  link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737146$$[Starting a Hot Rod server] 


*  link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737142$$[Hot Rod client libraries] 

