[[command_line_interface]]
= Command-Line Interface (CLI)
{brandname} offers a simple Command-Line Interface (CLI) with which it is possible to interact with the data within the caches and with most of the internal components (e.g. transactions, cross-site backups, rolling upgrades).

The CLI is built out of two elements: a server-side module and the  client command tool. The server-side module (`infinispan-cli-server-$VERSION.jar`) provides  the actual interpreter for the commands and needs to be included alongside your application. {brandname} Server includes CLI support out of the box.

Currently the server (and the  client) use the JMX protocol to communicate, but in a future release we  plan to support other communication protocols (in particular our own Hot Rod).

The CLI offers both an interactive and a batch mode. To invoke the client, run the
ifndef::productized[]
_bin/ispn-cli.[sh|bat]_ script.
endif::productized[]
ifdef::productized[]
_bin/cli.[sh|bat]_ script.
endif::productized[]

The following is a list of command-line switches which affect how the CLI can be started:

----
include::cli_examples/switches.adoc[]
----

* JMX over RMI is the traditional way in which JMX clients connect to MBeanServers. Please refer to the link:http://docs.oracle.com/javase/6/docs/technotes/guides/management/agent.html[JDK Monitoring and Management] documentation for details on how to configure the process to be monitored

* JMX over JBoss Remoting is the protocol of choice when your {brandname} application is running within WildFly or EAP.

The connection to the application can also be initiated from within the CLI using the connect command.

----
include::cli_examples/connect.adoc[]
----

The CLI prompt will show the active connection information, including the currently selected CacheManager. Initially no cache is selected so, before performing any cache operations, one must be selected. For this the _cache_ command is used. The CLI supports tab-completion for all commands and options and for most parameters where it makes sense to do so. Therefore typing _cache_ and pressing TAB will show a list of active caches:

----
include::cli_examples/caches_active.adoc[]
----

Pressing TAB at an empty prompt will show the list of all available commands:

----
include::cli_examples/available_commands.adoc[]
----

The CLI is based on link:https://github.com/aeshell/aesh[Æsh] and therefore offers many keyboard shortcuts to navigate and search the history of commands, to manipulate the cursor at the prompt, including both Emacs and VI modes of operation.

== Commands
=== abort
The _abort_ command is used to abort a running batch initiated by the _start_ command

----
include::cli_examples/command_abort.adoc[]
----

==== begin
The _begin_ command starts a transaction. In order for this command to work, the cache(s) on which the subsequent operations are invoked must have transactions enabled.

----
include::cli_examples/command_begin.adoc[]
----

==== cache
The _cache_ command selects the cache to use as default for all subsequent operations. If it is invoked without parameters it shows the currently selected cache.

----
include::cli_examples/command_cache.adoc[]
----

==== clearcache
The _clearcache_ command clears a cache from all content.

----
include::cli_examples/command_clearcache.adoc[]
----

==== commit
The _commit_ command commits an ongoing transaction

----
include::cli_examples/command_commit.adoc[]
----

==== container
The _container_ command selects the default container (cache manager). Invoked without parameters it lists all available containers

----
include::cli_examples/command_container.adoc[]
----

==== create
The _create_ command creates a new cache based on the configuration of an existing cache definition

----
include::cli_examples/command_create.adoc[]
----

==== deny
When authorization is enabled and the role mapper has been configured to be the ClusterRoleMapper, principal to role mappings are stored within the cluster registry (a replicated cache available to all nodes).
The _deny_ command can be used to deny roles previously assigned to a principal:

----
include::cli_examples/command_deny.adoc[]
----

==== disconnect
The _disconnect_ command disconnects the currently active connection allowing the CLI to connect to another instance.

----
include::cli_examples/command_deny.adoc[]
----

==== encoding
The _encoding_ command is used to set a default codec to use when reading/writing entries from/to a cache. When invoked without arguments it shows the currently selected codec. This command is useful since currently remote protocols such as HotRod and Memcached wrap keys and values in specialized structures.

----
include::cli_examples/command_encoding.adoc[]
----

==== end
The _end_ command is used to successfully end a running batch initiated by the _start_ command

----
include::cli_examples/command_end.adoc[]
----

==== evict
The _evict_ command is used to evict from the cache the entry associated with a specific key.

----
include::cli_examples/command_evict.adoc[]
----

==== get
The _get_ command is used to show the value associated to a specified key. For primitive types and Strings, the _get_ command will simply print the default representation. For other objects, a JSON representation of the object will be printed.

----
include::cli_examples/command_get.adoc[]
----

==== grant
When authorization is enabled and the role mapper has been configured to be the ClusterRoleMapper, principal to role mappings are stored within the cluster registry (a replicated cache available to all nodes).
The _grant_ command can be used to grant new roles to a principal:

----
include::cli_examples/command_grant.adoc[]
----

==== info
The _info_ command is used to show the configuration of the currently selected cache or container.

----
include::cli_examples/command_info.adoc[]
----

==== locate
The _locate_ command shows the physical location of a specified entry in a distributed cluster.

----
include::cli_examples/command_locate.adoc[]
----

==== put
The _put_ command inserts an entry in the cache. If the cache previously contained a mapping for the key, the old value is replaced by the specified value. The user can control the type of data that the CLI will use to store the key and value.

----
include::cli_examples/command_put.adoc[]
----

The put command can optionally specify a lifespan and a maximum idle time.

----
include::cli_examples/put_expire_maxidle.adoc[]
----

==== replace
The _replace_ command replaces an existing entry in the cache. If an old value is specified, then the replacement happens only if the value in the cache coincides.

----
include::cli_examples/command_replace.adoc[]
----

==== roles
When authorization is enabled and the role mapper has been configured to be the ClusterRoleMapper, principal to role mappings are stored within the cluster registry (a replicated cache available to all nodes).
The _roles_ command can be used to list the roles associated to a specific user, or to all users if one is not given:

----
include::cli_examples/command_roles.adoc[]
----

==== rollback
The _rollback_ command rolls back an ongoing transaction

----
include::cli_examples/command_rollback.adoc[]
----

==== site
The _site_ command performs operations related to the administration of cross-site replication. It can be used to obtain information related to the status of a site and to change the status (online/offline)

----
include::cli_examples/command_site.adoc[]
----

==== start
The _start_ command initiates a batch of operations.

----
include::cli_examples/command_start.adoc[]
----

==== stats
The _stats_ command displays statistics about a cache

----
include::cli_examples/command_stats.adoc[]
----

==== upgrade
The _upgrade_ command performs operations used during the rolling upgrade procedure.

----
include::cli_examples/command_upgrade.adoc[]
----

==== version
The _version_ command displays version information about both the CLI client and the server

----
include::cli_examples/command_version.adoc[]
----

[[data_types]]
=== Data Types

The CLI understands the following types:


*  string strings can either be quoted between single (') or double (") quotes, or left unquoted. In this case it must not contain spaces, punctuation and cannot begin with a number  e.g. 'a string', key001


*  int an integer is identified by a sequence of decimal digits, e.g. 256


*  long a long is identified by a sequence of decimal digits suffixed by 'l', e.g. 1000l


* double


** a double precision number is identified by a floating point number(with optional exponent part) and an optional 'd' suffix, e.g.3.14


* float


** a single precision number is identified by a floating point number(with optional exponent part) and an 'f' suffix, e.g. 10.3f


*  boolean a boolean is represented either by the keywords true and false


*  UUID a UUID is represented by its canonical form XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX


*  JSON serialized Java classes can be represented using JSON notation, e.g. {"package.MyClass":{"i":5,"x":null,"b":true}}. Please note that the specified class must be available to the CacheManager's class loader.

=== Time Values
A time value is an integer number followed by time unit suffix: days (d), hours (h), minutes (m), seconds (s), milliseconds (ms).
