[id='cross-site-automatic-offline_{context}']
= Factors that take backup locations offline automatically

{brandname} can take backup locations offline when remote sites become unavailable.
This prevents {brandname} nodes from continuously attempting to replicate data to offline backup locations, which results in error messages and consumes resources.
There are different factors you can configure for {brandname} to take backup locations offline.

[discrete]
== Timeout values

Backup configurations include timeout values for operations to replicate data.
If operations do not complete before the timeout occurs, {brandname} records them as failures.

In the following example, operations to replicate data to NYC are recorded as failures if they do not complete after 10 seconds:

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/xsite_backup_timeout.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/xsite_backup_timeout.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/xsite_backup_timeout.yaml[]
----

[discrete]
== Number of failures

You can specify the number of **consecutive** failures that can occur before
backup locations go offline.

In the following example, if a cluster attempts to replicate data to NYC and five consecutive operations fail, NYC automatically goes offline:

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/xsite_backup_number_failures.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/xsite_backup_number_failures.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/xsite_backup_number_failures.yaml[]
----

[discrete]
== Time to wait

You can also specify how long to wait before taking sites offline when backup operations fail.
If a backup request succeeds before the wait time runs out, {brandname} does not take the site offline.

[TIP]
====
Set a negative or zero value for number of failures to use only a minimum time to wait to take backup locations offline.

[source,xml,options="nowrap",subs=attributes+]
----
<take-offline after-failures="-1" min-wait="10000"/>
----
====

In the following example, if a cluster attempts to replicate data to NYC and there are more than five consecutive failures and 15 seconds elapse after the first failed operation, NYC automatically goes offline:

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/xsite_backup_time_wait.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/xsite_backup_time_wait.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/xsite_backup_time_wait.yaml[]
----
