= {brandname} Server Endpoints

Here's a brief summary of the available server endpoints.

* *Hot Rod Server Module*: This module is an implementation of the Hot Rod binary protocol backed by {brandname} which allows clients to do dynamic load balancing, failover, and smart routing.
 ** A link:http://www.infinispan.org/hotrod-clients[variety of clients] exist for this protocol.
 ** If you're clients are running Java, this should be your defacto server module choice because it allows for dynamic load balancing and failover. This means that Hot Rod clients can dynamically detect changes in the topology of Hot Rod servers as long as these are clustered. When new nodes join or leave, clients update their Hot Rod server topology view. Also, when Hot Rod servers are configured with distribution, clients can detect where a particular key resides and can route requests smartly.
 ** Load balancing and failover are dynamically provided by Hot Rod client implementations using information provided by the server.

* *REST Server Module*: The REST server, which is distributed as a WAR file, can be deployed in any servlet container to allow {brandname} to be accessed via a RESTful HTTP interface.
 ** To connect to it, you can use any HTTP client. There are many different client implementations available for many different languages and systems.
 ** This module is particularly recommended for those environments where the HTTP port is the only access method allowed between clients and servers.
 ** Clients wanting to load balance or failover between different {brandname} REST servers can do so using any standard HTTP load balancer such as link:http://www.jboss.org/mod_cluster[mod_cluster] . It's worth noting, these load balancers maintain a static view of the servers in the backend and if a new one was to be added, it requires manual updates of the load balancer.

* *Memcached Server Module*: This module is an implementation of the link:http://github.com/memcached/memcached/blob/master/doc/protocol.txt[Memcached text protocol] backed by {brandname}.
 ** To connect to it, you can use any of the link:http://code.google.com/p/memcached/wiki/Clients[existing Memcached clients] which are diverse.
 ** As opposed to Memcached servers, {brandname} based Memcached servers can actually be clustered and can replicate or distribute data using consistent hash algorithms around the cluster. This module is particularly of interest to those users that want to provide failover capabilities to the data stored in Memcached servers.
 ** In terms of load balancing and failover, there are a few clients that can load balance or failover given a static list of server addresses (perl's Cache::Memcached for example) but any server addition or removal would require manual intervention.
