[id='single_port']
= {brandname} Protocol Handling
{brandname} servers use a router connector to expose multiple protocols over
the same TCP port, `11222`. Using a single port for multiple protocols
simplifies configuration and management and increases security by reducing the
attack surface for unauthorized users.

{brandname} servers handle HTTP/1.1, HTTP/2, and Hot Rod protocol requests via
port `11222` as follows:

HTTP/1.1 upgrade headers::
Client requests can include the `HTTP/1.1 upgrade` header field to initiate
HTTP/1.1 connections with {brandname} servers. Client applications can then
send the `Upgrade: protocol` header field, where `protocol` is a {brandname}
server endpoint.

Application-Layer Protocol Negotiation (ALPN)/Transport Layer Security (TLS)::
Client applications specify Server Name Indication (SNI) mappings for
{brandname} server endpoints to negotiate protocols in a secure manner.

Automatic Hot Rod detection::
Client requests that include Hot Rod headers automatically route to Hot Rod
endpoints if the single port router configuration includes Hot Rod.
