[id='data-set-size_{context}']
= How to calculate the size of your data set

Planning a {brandname} deployment involves calculating the size of your data set then figuring out the correct number of nodes and amount of RAM to hold the data set.

You can roughly estimate the total size of your data set with this formula:

ifdef::backend-html5[stem:[D_{\text{set}} = N_{\text{entries}} \times (S_{\text{key}} + S_{\text{value}} + O_{\text{memory}})]]
ifdef::backend-pdf[`D(set) = N(entries) * (S(key) + S(value) + O(memory))`]

Where:

ifdef::backend-html5[]
* stem:[D_{\text{set}}] is the data set size
* stem:[N_{\text{entries}}] is the number of entries
* stem:[S_{\text{key}}] is the average key size
* stem:[S_{\text{value}}] is the average value size
* stem:[O_{\text{memory}}] is the memory overhead per entry
endif::[]
ifdef::backend-pdf[]
* `D(set)` is the data set size
* `N(entries)` is the number of entries
* `S(key)` is the average key size
* `S(value)` is the average value size
* `O(memory)` is the memory overhead per entry
endif::[]

[NOTE]
====
With remote caches you need to calculate key sizes and value sizes in their marshalled forms.
====

[discrete]
== Data set size in distributed caches

Distributed caches require some additional calculation to determine the data set size.

In normal operating conditions, distributed caches store a number of copies for each key/value entry that is equal to the `Number of owners` that you configure.
During cluster rebalancing operations, some entries have an extra copy, so you should calculate `Number of owners + 1` to allow for that scenario.

You can use the following formula to adjust the estimate of your data set size for distributed caches:

ifdef::backend-html5[stem:[D_{\text{dist}} = D_{\text{set}} \times (N_{\text{owners}} + 1)]]
ifdef::backend-pdf[`D(dist) = D(set) * (N(owners) + 1)`]

.Calculating available memory for distributed caches

Distributed caches allow you to increase the data set size either by adding more nodes or by increasing the amount of available memory per node.

ifdef::backend-html5[stem:[D_{\text{dist}} \leq M_{\text{node}} \times N_{\text{min}}]]
ifdef::backend-pdf[`D(dist) <= M(node) * N(min)`]

.Adjusting for node loss tolerance

Even if you plan to have a fixed number of nodes in the cluster, you should take into account the fact that not all nodes will be in the cluster all the time.
Distributed caches tolerate the loss of `Number of owners - 1` nodes without losing data so you can allocate that many extra node in addition to the minimum number of nodes that you need to fit your data set.

ifdef::backend-html5[stem:[N_{\text{planned}} = N_{\text{min}} + N_{\text{owners}} - 1]]
ifdef::backend-pdf[`N(planned) = N(min) + N(owners) - 1`]

ifdef::backend-html5[stem:[D_{\text{dist}} \leq M_{\text{node}} \times (N_{\text{planned}} - N_{\text{owners}} + 1)]]
ifdef::backend-pdf[`D(dist) <= M(node) * (N(planned) - N(owners) + 1)`]

For example, you plan to store one million entries that are 10KB each in size and configure three owners per entry for availability.
If you plan to allocate 4GB of RAM for each node in the cluster, you can then use the following formula to determine the number of nodes that you need for your data set:

ifdef::backend-html5[stem:[D_{\text{set}} = 1{,}000{,}000 \times 10\text{KB} = 10\text{GB}]]
ifdef::backend-pdf[`D(set) = 1,000,000 * 10KB = 10GB`]

ifdef::backend-html5[stem:[D_{\text{dist}} = (3 + 1) \times 10\text{GB} = 40\text{GB}]]
ifdef::backend-pdf[`D(dist) = (3 + 1) * 10GB = 40GB`]

ifdef::backend-html5[stem:[40\text{GB} \leq 4\text{GB} \times N_{\text{min}}]]
ifdef::backend-pdf[`40GB <= 4GB * N(min)`]

ifdef::backend-html5[stem:[N_{\text{min}} \geq \frac{40\text{GB}}{4\text{GB}} = 10]]
ifdef::backend-pdf[`N(min) >= 40GB / 4GB = 10`]

ifdef::backend-html5[stem:[N_{\text{planned}} = 10 + 3 - 1 = 12]]
ifdef::backend-pdf[`N(planned) = 10 + 3 - 1 = 12`]
