[id='server_directory_structure-{context}']
= {brandname} Server Filesystem
{brandname} Server uses the following folders on the host filesystem under `{server_home}`:

[source,options="nowrap",subs=attributes+]
----
├── bin
├── boot
├── docs
├── lib
├── server
└── static
----

== `server` folder

Besides resources in the `docs` folder, the only folder you need to interact with is the `server` folder.

[TIP]
====
See the _Server README_ for descriptions of the other folders in your `{server_home}` directory.

The _Server README_ also describes system properties you can use to customize the {brandname} Server filesystem.
====

You can create multiple nodes under the same `{server_home}` directory, but each {brandname} Server instance must have its own `server` folder.
For example, the filesystem for a cluster of 5 nodes could be as follows:

[source,options="nowrap",subs=attributes+]
----
├── bin
├── boot
├── docs
├── lib
├── server
├── server1
├── server2
├── server3
├── server4
└── static
----

Each `server*` folder should contain the following subdirectories:

[source,options="nowrap",subs=attributes+]
----
├── server
│   ├── conf
│   ├── data
│   ├── lib
│   └── log
----

== `server/conf` folder
Holds `infinispan.xml` configuration files for a {brandname} Server instance.

{brandname} separates configuration into two layers:

Dynamic:: Create mutable cache configurations for data scalability. +
{brandname} Server permanently saves the caches you create at runtime along with the cluster state that is distributed across nodes.
Each joining node receives a complete cluster state that {brandname} Server synchronizes across all nodes whenever changes occur.
Static:: Add configuration to `infinispan.xml` for underlying server mechanisms such as cluster transport, security, and shared datasources.

== `server/data` folder
Provides internal storage that {brandname} Server uses to maintain cluster state.

[IMPORTANT]
====
Users should never directly delete or modify content in `server/data`.

Modifying files such as `caches.xml` while the server is running can cause corruption.
Deleting content can result in an incorrect state, which means clusters cannot restart after shutdown.
====

== `server/lib` folder
Contains extension `JAR` files for custom filters, custom event listeners, JDBC drivers, custom `ServerTask` implementations, and so on.

== `server/log` folder
Holds {brandname} Server log files.

.Reference

* link:{runtime_readme}[{brandname} Server README]
* link:#logs[Working with {brandname} Server Logs]
ifdef::productized[]
* link:https://access.redhat.com/solutions/5455731[What is stored in the <server>/data directory used by a RHDG server] (:RedHat: Knowledgebase)
endif::productized[]
