= Hot Rod
Hot Rod is a binary TCP client-server protocol designed to provide faster data
access and improved performance in comparison to text-based protocols.

{brandname} provides Hot Rod client libraries in Java, C++, C#, Node.js and other programming languages.

.Topology state transfer

{brandname} uses topology caches to provide clients with cluster views.
Topology caches contain entries that map internal JGroups transport addresses
to exposed Hot Rod endpoints.

When client send requests, {brandname} servers compare the topology ID in
request headers with the topology ID from the cache. {brandname} servers send
new topology views if client have older topology IDs.

Cluster topology views allow Hot Rod clients to immediately detect when nodes
join and leave, which enables dynamic load balancing and failover.

In distributed cache modes, the consistent hashing algorithm also makes it
possible to route Hot Rod client requests directly to primary owners.

.Reference

//Community
ifdef::community[]
* link:../hotrod_java/hotrod_java.html[{brandname} Hot Rod Server]
* link:http://www.infinispan.org/hotrod-clients[Hot Rod client implementations]
endif::community[]
