[id='file-stores_{context}']
= File-based cache stores

File-based cache stores provide persistent storage on the local host filesystem where {brandname} is running. 

The following types of file-based cache stores exist in {brandname}:
* Shared, where cache entries persist after a cluster restart operation. Examples include SQL, JDBC, and so on. 
* Non-shared, where cache entries persist after a cluster restart operation, but in certain situations data loss might occur where individual nodes are restarted and the non-shared store contains stale key entries.  

File-based cache stores should always be unique to each {brandname} instance.
If you want to use the same persistent across a cluster, configure shared storage, such as a JDBC string-based cache store.

The following limitations exist with how a non-shared store interacts in a clustered environment: 

* If you do not gracefully shutdown a cache, only the last node remains active and it must store all the cache's data. In-memory and eviction limitations might impact the amount of data a node can store. To prevent this issue, restart the last active node before you restart any of the other nodes. 
* A node in a cluster might store the current state of a running rebalancing operation. After you restart the cluster, the rebalancing operation remains active and it does not perform checks on nodes that rejoin the cluster. This can lead to corrupted data or data loss for a cache. You can prevent this issue by configuring the non-shared store with `purge=false`.

[IMPORTANT]
====
To retain data during clustered cache restarts, use a shared store. Using a non-shared store in a clustered cache environment might lead to data loss, especially in instances where you configured the store with  `purge-on-startup=false`. Consider only using a non-shared store for cluster shutdown operations. 

// Downstream content
ifdef::downstream[]
See, link:https://access.redhat.com/solutions/1249463[How an unshared `CacheStore` behave in a RHDG clustered environment?] ({RedHat} Customer Portal).
endif::downstream[]
====

[WARNING]
====
Never use filesystem-based cache stores on shared file systems, such as an NFS or Samba share, because they do not provide file locking capabilities and data corruption can occur.

Additionally if you attempt to use transactional caches with shared file systems, unrecoverable failures can happen when writing to files during the commit phase.
====