= Server Group
A server group is set of server instances that will be managed and configured as one.
In a managed domain each application server instance is a member of a server group.
Even if the group only has a single server, the server is still a member of a group.
It is the responsibility of the Domain Controller and the Host Controllers to ensure that all servers in a server group have a consistent configuration.
They should all be configured with the same profile and they should have the same deployment content deployed.
To keep things simple, ensure that all the nodes that you want to belong to an {brandname} cluster are configured as servers of one server group.

The domain can have multiple server groups, i.e. multiple {brandname} clusters.
Different server groups can be configured with different profiles and deployments; for example in a domain with different {brandname} Server clusters ﻿providing different services.
Different server groups can also run the same profile and have the same deployments.

An example server group definition is as follows:

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_group.xml[]
----
