[id='session-externalization_{context}']
= Session externalization

{brandname} can provide external caches for applications built on {quarkusbrandname}, {wildflybrandname}, {tomcatbrandname}, and Spring.
These external caches store HTTP sessions and other data independently of the application layer.

Externalizing sessions to {brandname} gives you the following benefits:

Elasticity:: Eliminate the need for rebalancing operations when scaling applications.
Smaller memory footprints:: Storing session data in external caches reduces overall memory requirements for applications.

.Session externalization
[plantuml, target=session-externalization-topology, format=svg, align=center, subs="attributes+"]
....
@startuml
skinparam defaultFontName sans-serif
skinparam shadowing false

skinparam componentStyle rectangle

[Application servers] as Apps

package "{brandname} cluster" {
  node "Server 1\n{brandname}" as S1
  node "Server 2\n{brandname}" as S2
  node "Server N\n{brandname}" as SN
}

Apps <--> S1 : read/write sessions and other data
Apps <--> S2
Apps <--> SN
@enduml
....
