[[cache_configuration]]
= Configuration
{brandname} offers both declarative and programmatic configuration.

[[cache_configuration_declarative]]
==  Configuring caches declaratively

Declarative configuration comes in a form of XML document that adheres to a provided {brandname} configuration XML
link:http://www.infinispan.org/schemas/infinispan-config-{infinispanversion}.xsd[schema].

Every aspect of {brandname} that can be configured declaratively can also be configured programmatically.
In fact, declarative configuration, behind the scenes, invokes the programmatic configuration API as the XML configuration file is being processed.
One can even use a combination of these approaches.
For example, you can read static XML configuration files and at runtime programmatically tune that same configuration.
Or you can use a certain static configuration defined in XML as a starting point or template for defining additional configurations in runtime.

There are two main configuration abstractions in {brandname}: `global` and `cache`.

.Global configuration
Global configuration defines global settings shared among all cache instances created by a single link:{javadocroot}/org/infinispan/manager/EmbeddedCacheManager.html[EmbeddedCacheManager].
Shared resources like thread pools, serialization/marshalling settings, transport and network settings, JMX domains are all part of global configuration.

.Cache configuration
Cache configuration is specific to the actual caching domain itself: it specifies eviction, locking, transaction, clustering, persistence etc.
You can specify as many named cache configurations as you need. One of these caches can be indicated as the `default` cache,
which is the cache returned by the `CacheManager.getCache()` API, whereas other named caches are retrieved via the `CacheManager.getCache(String name)` API.

Whenever they are specified, named caches inherit settings from the default cache while additional behavior can be specified or overridden.
{brandname} also provides a very flexible inheritance mechanism, where you can define a hierarchy of configuration templates,
allowing multiple caches to share the same settings, or overriding specific parameters as necessary.

NOTE: Embedded and Server configuration use different schemas, but we strive to maintain them as compatible as possible so that you
can easily migrate between the two.


One of the major goals of {brandname} is to aim for zero configuration.
A simple XML configuration file containing nothing more than a single infinispan element is enough to get you started.
The configuration file listed below provides sensible defaults and is perfectly valid.

.infinispan.xml
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/infinispan.xml[]
----

However, that would only give you the most basic, local mode, non-clustered cache manager with no caches.
Non-basic configurations are very likely to use customized global and default cache elements.

Declarative configuration is the most common approach to configuring {brandname} cache instances.
In order to read XML configuration files one would typically construct an instance of DefaultCacheManager by pointing to an XML file containing {brandname} configuration.
Once the configuration file is read you can obtain reference to the default cache instance.

[source,java]
----
include::code_examples/DefaultCacheManagerXML.java[]
----

or any other named instance specified in `my-config-file.xml`.

[source,java]
----
include::code_examples/GetSomeNamedCache.java[]
----

The name of the default cache is defined in the `<cache-container>` element of the XML configuration file, and additional
caches can be configured using the `<local-cache>`,`<distributed-cache>`,`<invalidation-cache>` or `<replicated-cache>` elements.

The following example shows the simplest possible configuration for each of the cache types supported by {brandname}:

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/simple_config_cache_types.xml[]
----

[[cache_configuration_templates]]
=== Cache configuration templates

As mentioned above, {brandname} supports the notion of _configuration templates_. These are full or partial configuration
declarations which can be shared among multiple caches or as the basis for more complex configurations.

The following example shows how a configuration named `local-template` is used to define a cache named `local`.

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/local_template_config.xml[]
----

Templates can inherit from previously defined templates, augmenting and/or overriding some or all of the configuration elements:

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/config_template_inherit.xml[]
----

In the above example, `base-template` defines a local cache with a specific _expiration_ configuration. The `extended-template`
configuration inherits from `base-template`, overriding just a single parameter of the _expiration_ element (all other
attributes are inherited) and adds a _memory_ element. Finally, two caches are defined: `local` which uses the `base-template`
configuration and `local-bounded` which uses the `extended-template` configuration.

WARNING: Be aware that for multi-valued elements (such as `properties`) the inheritance is additive, i.e. the child configuration will be the result of merging the properties from the parent and its own.

[[cache_configuration_wildcards]]
=== Cache configuration wildcards

An alternative way to apply templates to caches is to use wildcards in the template name, e.g. `basecache*`. Any cache whose name matches the template wildcard will inherit that configuration.

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/config_template_wildcard.xml[]
----

Above, caches `basecache-1` and `basecache-2` will use the `basecache*` configuration. The configuration will also
be applied when retrieving undefined caches programmatically.

NOTE: If a cache name matches multiple wildcards, i.e. it is ambiguous, an exception will be thrown.

[[cache_configuration_xinclude]]
==== XInclude support

The configuration parser supports link:https://www.w3.org/TR/xinclude/[XInclude] which means you can split your XML configuration across multiple files:

.infinispan.xml
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/config_xinclude.xml[]
----

.included.xml
[source,xml,options="nowrap",subs=attributes+]
----
<local-cache name="cache-1"/>
----

NOTE: the parser supports a minimal subset of the XInclude spec (no support for XPointer, fallback, text processing and content negotiation).

[[cache_configuration_declarative_ref]]
=== Declarative configuration reference

For more details on the declarative configuration schema, refer to the link:{configdocroot}[configuration reference].
If you are using XML editing tools for configuration writing you can use the provided {brandname} link:http://infinispan.org/schemas/infinispan-config-{infinispanversion}.xsd[schema] to assist you.

[[cache_configuration_programmatic]]
==  Configuring caches programmatically
Programmatic {brandname} configuration is centered around the CacheManager and ConfigurationBuilder API.
Although every single aspect of {brandname} configuration could be set programmatically, the most usual approach is to create a starting point in a form of XML configuration file and then in runtime, if needed, programmatically tune a specific configuration to suit the use case best.

[source,java]
----
include::code_examples/DefaultCacheManagerXML.java[]
----

Let's assume that a new synchronously replicated cache is to be configured programmatically.
First, a fresh instance of Configuration object is created using ConfigurationBuilder helper object, and the cache mode is set to synchronous replication.
Finally, the configuration is defined/registered with a manager.

[source,java]
----
include::code_examples/ConfigRegisterManager.java[]
----

The default cache configuration (or any other cache configuration) can be used as a starting point for creation of a new cache.
For example, lets say that `infinispan-config-file.xml` specifies a replicated cache as a default and that a distributed cache is desired with a specific L1 lifespan while at the same time retaining all other aspects of a default cache.
Therefore, the starting point would be to read an instance of a default Configuration object and use `ConfigurationBuilder` to construct and modify cache mode and L1 lifespan on a new `Configuration` object. As a final step the configuration is defined/registered with a manager.

[source,java]
----
include::code_examples/ConfigDefaultRegisterManager.java[]
----

As long as the base configuration is the default named cache, the previous code works perfectly fine. However, other times the base configuration might be another named cache. So, how can new configurations be defined based on other defined caches? Take the previous example and imagine that instead of taking the default cache as base, a named cache called "replicatedCache" is used as base. The code would look something like this:

[source,java]
----
include::code_examples/ConfigReplicatedRegisterManager.java[]
----

Refer to link:{javadocroot}/org/infinispan/manager/CacheManager.html[CacheManager] , link:{javadocroot}/org/infinispan/configuration/cache/ConfigurationBuilder.html[ConfigurationBuilder] , link:{javadocroot}/org/infinispan/configuration/cache/Configuration.html[Configuration] , and link:{javadocroot}/org/infinispan/configuration/global/GlobalConfiguration.html[GlobalConfiguration] javadocs for more details.

[[cache_configuration_programmatic_api]]
=== ConfigurationBuilder Programmatic Configuration API
While the above paragraph shows how to combine declarative and programmatic configuration, starting from an XML configuration is completely optional.
The ConfigurationBuilder fluent interface style allows for easier to write and more readable programmatic configuration.
This approach can be used for both the global and the cache level configuration.
GlobalConfiguration objects are constructed using GlobalConfigurationBuilder while Configuration objects are built using ConfigurationBuilder.
Let's look at some examples on configuring both global and cache level options with this API:

=== Enabling JMX MBeans and statistics
Sometimes you might also want to enable collection of link:{javadocroot}/jmxComponents.html[global JMX statistics]
at cache manager level or get information about the transport. To enable global JMX statistics simply do:

[source,java]
----
include::code_examples/EnableJmxStats.java[]
----

Please note that by not enabling (or by explicitly disabling) global JMX statistics your are just turning off statistics
collection. The corresponding MBean is still registered and can be used to manage the cache manager in general, but the
statistics attributes do not return meaningful values.

Further options at the global JMX statistics level allows you to configure the cache manager name which comes handy when you have multiple cache managers running on the same system, or how to locate the JMX MBean Server:

[source,java]
----
include::code_examples/MBeanServerLookup.java[]
----

=== Configuring the thread pools

Some of the {brandname} features are powered by a group of the thread pool executors which can also be tweaked at this global level. For example:

[source,java]
----
include::code_examples/ConfigThreadPools.java[]
----

You can not only configure global, cache manager level, options, but you can also configure cache level options such as the cluster mode:

[source,java]
----
include::code_examples/ConfigClustering.java[]
----

Or you can configure eviction and expiration settings:

[source,java]
----
include::code_examples/ConfigExpiration.java[]
----

=== Configuring transactions and locking

An application might also want to interact with an {brandname} cache within the boundaries of JTA and to do that you need to configure the transaction layer and optionally tweak the locking settings. When interacting with transactional caches, you might want to enable recovery to deal with transactions that finished with an heuristic outcome and if you do that, you will often want to enable JMX management and statistics gathering too:

[source,java]
----
include::code_examples/ConfigTransactionsLocking.java[]
----

=== Configuring cache stores

Configuring {brandname} with chained cache stores is simple too:

[source,java]
----
include::code_examples/ConfigCacheStores.java[]
----

[[cache_configuration_programmatic_advanced]]
=== Advanced programmatic configuration

The fluent configuration can also be used to configure more advanced or exotic options, such as advanced externalizers:

[source,java]
----
include::code_examples/ConfigExternalizers.java[]
----

Or, add custom interceptors:

[source,java]
----
include::code_examples/ConfigCustomInterceptors.java[]
----

For information on the individual configuration options, please check the link:{configdocroot}[configuration guide].

[[cache_configuration_migration]]
==  Configuration Migration Tools
The configuration format of {brandname} has changed since schema version 6.0 in order to align the embedded schema with the one used
by the server. For this reason, when upgrading to schema 7.x or later, you should use the configuration converter included in the
_all_ distribution. Simply invoke it from the command-line passing the old configuration file as the first parameter and the name
of the converted file as the second parameter.

.Unix/Linux/macOS:
`bin/config-converter.sh oldconfig.xml newconfig.xml`

.Windows:
`bin\config-converter.bat oldconfig.xml newconfig.xml`

TIP: If you wish to help write conversion tools from other caching systems, please contact link:https://lists.jboss.org/mailman/listinfo/infinispan-dev[infinispan-dev].
