ifndef::productized[]
= {brandname} modules for WildFly / EAP

WARNING: The {brandname} modules have been deprecated and will be removed in a future release.

As the {brandname} modules shipped with link:http://wildfly.org/[WildFly] / link:https://www.redhat.com/en/technologies/jboss-middleware/application-platform[EAP] are tailored to its internal usage, it is recommend to install separate modules
if you want to use {brandname} in your application that is deployed to WildFly / EAP. By installing these modules, it is possible to deploy user applications without packaging the {brandname} JARs within the deployments (WARs, EARs, etc), thus minimizing their size.
Also, there will be no conflict with WildFly / EAP's internal modules since the slot will be different.
endif::productized[]

ifdef::productized[]
= {brandname} modules for EAP

WARNING: The {brandname} modules have been deprecated and will be removed in a future release.

As the {brandname} modules shipped with link:https://www.redhat.com/en/technologies/jboss-middleware/application-platform[EAP] are tailored to its internal usage, it is recommend to install separate modules if you want to use {brandname} in your application that is deployed to EAP. By installing these modules, it is possible to deploy user applications without packaging the {brandname} JARs within the deployments (WARs, EARs, etc), thus minimizing their size.
Also, there will be no conflict with EAP's internal modules since the slot will be different.
endif::productized[]

[[modules_installation_section]]
== Installation
ifndef::productized[]
The modules for WildFly / EAP are available in the link:http://infinispan.org/download/[downloads] section of our site.
After extracting the zip, copy the contents of the `modules` directory to the `WILDFLY_HOME/modules` directory, so that
for example the {brandname} core module would be under `WILDFLY_HOME/modules/system/add-ons/{moduleprefix}/org/infinispan/core`.
endif::productized[]

ifdef::productized[]
The modules for EAP are available from the link:https://access.redhat.com/downloads/[Red Hat Customer Portal].

After extracting the zip, copy the contents of the `modules` directory to the `${EAP_HOME}/modules` directory. For example, the {brandname} core module should be under `${EAP_HOME}/modules/system/add-ons/{moduleprefix}/org/infinispan/core`.
endif::productized[]

== Application Dependencies

The {brandname} functionality is packaged as a single module, `org.infinispan`. In order to use {brandname} functionality in your application, add the follow to the manifest:

.MANIFEST.MF
[source,subs=attributes]
----
Manifest-Version: 1.0
Dependencies: org.infinispan:{infinispanslot} services
----

If you are using Maven to build your application, mark the {brandname} dependencies as _provided_ and configure your artifact archiver to generate the appropriate MANIFEST.MF file:

.pom.xml
[source,xml,options="nowrap",subs=attributes+]
----
include::dependencies_maven/eap_dependencies.xml[]
----

