[[marshalling]]
= Marshalling

Marshalling is the process of converting Java objects into a binary format that can be transferred over the wire or stored to disk.
Unmarshalling is the reverse process whereby data read from a binary format is transformed back into Java objects.
{brandname} uses marshalling/unmarshalling to:

* Transform data so that it can be sent to other {brandname} nodes in a cluster.
* Transform data so that it can be stored in underlying cache stores.
* Store data in {brandname} in a binary format to provide lazy deserialization capabilities.

{brandname} handles marshalling for all internal types. Users only need to be concerned with the marshalling
of the Java objects that they will store in the cache.

== Marshaller Implementations
[[protostream_cm_config]]
=== ProtoStream (Default)
The default marshaller for {brandname} is link:#protostream[ProtoStream], which marshalls data as link:https://developers.google.com/protocol-buffers[Protocol Buffers].
This is a platform independent format that utilises schemas to provide a structured representation of your Java objects
that can evolve over time but also maintain backwards compatibility".

{brandname} directly integrates with the ProtoStream library by allowing users to configure implementations of the ProtoStream
SerializationContextInitializer interface. These implementations are then used to initialise the various SerializationContexts used by
{brandname} for marshalling, allowing custom user objects to be marshalled for storage and cluster communication.
More details on how to generate/implement your own SerializationContextInitailizers can be found link:#protostream_usage[here].

SerializationContextInitailizers can be configured as follows:

.Programmatic procedure

[source,java]
----
include::code_examples/ProtoStreamMarshaller.java[]
----

.Declarative procedure

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/protostream_marshaller.xml[]
----


[[java_serialization_marshaller]]
=== Java Serialization Marshaller
Java serialization can also be used to marshall your objects. The only requirements are that your Java objects implement
the link:https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html[Serializable] interface, the
link:{javadocroot}/org/infinispan/commons/marshall/JavaSerializationMarshaller.html[JavaSerializationMarshaller] is specified
and that your objects are added to the serialization white list as part of the global configuration. For example,
to utilise Java serialization with all classes in package "org.infinispan.example.*" and the class "org.infinispan.concrete.SomeClass"
in the white list configure the CacheManager as follows:

.Programmatic procedure

[source,java]
----
include::code_examples/SerializationMarshaller.java[]
----

.Declarative procedure

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/serialization_marshaller.xml[]
----


=== JBoss Marshalling
JBoss Marshalling is a Serialization based marshalling library which was the default marshaller in past versions of {brandname}.
It's possible to still utilise this library, however it's necessary to first add the `infinipsan-jboss-marshalling` dependency
to the classpath. Then to configure the marshaller to be the `JBossUserMarshaller` as follows:

.Programmatic procedure

[source,java]
----
include::code_examples/JBossUserMarshaller.java[]
----

.Declarative procedure

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/jboss_user_marshaller.xml[]
----


[IMPORTANT]
====
JBoss Marshalling is deprecated and planned for removal in a future version of {brandname}.
====

[WARNING]
====
{brandname} ignores implementations of the link:{javadocroot}/org/infinispan/commons/marshall/AdvancedExternalizer.html[AdvancedExternalizer]
interface when persisting data unless you configure JBoss marshalling. However, this interface is also deprecated and planned for removal.
====

=== Custom Implementation
You can provide custom marshaller classes with the link:{javadocroot}/org/infinispan/commons/marshall/Marshaller.html[Marshaller interface].
For example:

.Programmatic procedure

[source,java]
----
include::code_examples/CustomMarshaller.java[]
----

.Declarative procedure

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/custom_marshaller.xml[]
----


TIP: It's possible custom marshaller implementations to access a configured white list via the
link:{javadocroot}/org/infinispan/commons/marshall/Marshaller.html#initialize(org.infinispan.commons.configuration.ClassWhiteList)
method, which is called during startup.

[[store_as_binary]]
== Store As Binary
Store as binary enables data to be stored in its serialized form. This can be useful to achieve lazy deserialization, which is the mechanism by which {brandname} by which serialization and deserialization of objects is deferred till the point in time in which they are used and needed. This typically means that any deserialization happens using the thread context class loader of the invocation that requires deserialization, and is an effective mechanism to provide classloader isolation. By default lazy deserialization is disabled but if you want to enable it, you can do it like this:

.Programmatic procedure

[source,java]
----
include::code_examples/StorageTypeBinary.java[]
----

.Declarative procedure
* Via XML at the Cache level, either under `<*-cache />` element:

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/memory_binary.xml[]
----

=== Equality Considerations

When using lazy deserialization/storing as binary, keys and values are wrapped as link:{javadocroot}/org/infinispan/commons/marshall/[WrappedBytes].
It is this wrapper class that transparently takes care of serialization and deserialization on demand, and internally may have a reference to the object itself being wrapped, or the serialized, byte array representation of this object.

This has a particular effect on the behavior of equality.
The equals() method of this class will either compare binary representations (byte arrays) or delegate to the wrapped object instance's equals() method, depending on whether both instances being compared are in serialized or deserialized form at the time of comparison.
If one of the instances being compared is in one form and the other in another form, then one instance is either serialized or deserialized.

This will affect the way keys stored in the cache will work, when `storeAsBinary` is used, since comparisons happen on the key which will be wrapped by a MarshalledValue. Implementers of equals() methods on their keys need to be aware of the behavior of equality comparison, when a key is wrapped as a MarshalledValue, as detailed above.

=== Store-by-value via defensive copying
The configuration `storeAsBinary` offers the possibility to enable defensive copying, which allows for store-by-value like behaviour.

{brandname} marshalls objects the moment they're stored, hence changes made to object references are not stored in the cache, not even for local caches. This provides store-by-value like behaviour. Enabling `storeAsBinary` can be achieved:

.Programmatic procedure

[source,java]
----
include::code_examples/StoreAsBinary.java[]
----

.Declarative procedure
*  Via XML at the Cache level, either under `<*-cache />` or `<default />` elements:

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/store_as_binary.xml[]
----
