[[jdbc_cache_store]]
= JDBC String based Cache Store
A cache store which relies on the provided JDBC driver to load/store values in the underlying database.

Each key in the cache is stored in its own row in the database. In order to store each key in its own row, this store relies
on a (pluggable) bijection that maps the each key to a String object. The bijection is defined by the Key2StringMapper interface.
{brandname}s ships a default implementation (smartly named DefaultTwoWayKey2StringMapper) that knows how to handle primitive types.

[NOTE]
====
By default {brandname} shares are not stored, meaning that all nodes in the cluster will write to the underlying store upon each update.
If you wish for an operation to only be written to the underlying database once, you must configure the JDBC store to be shared.
====

//Exclude segmentation from productized docs.
ifndef::productized[]
[NOTE]
====
The JDBC string-based cache store does not support segmentation. Support will
be available in a future release.
====
endif::productized[]

== Connection management (pooling)
In order to obtain a connection to the database the JDBC cache store relies on a link:{javadocroot}/org/infinispan/persistence/jdbc/connectionfactory/ConnectionFactory.html[ConnectionFactory]
implementation. The connection factory is specified programmatically using one of the connectionPool(), dataSource()
or simpleConnection() methods on the JdbcStringBasedStoreConfigurationBuilder class or declaratively using one of the
`<connectionPool />`, `<dataSource />` or `<simpleConnection />` elements.

{brandname} ships with three ConnectionFactory implementations:


* link:{javadocroot}/org/infinispan/persistence/jdbc/configuration/PooledConnectionFactoryConfigurationBuilder.html[PooledConnectionFactoryConfigurationBuilder]
is a factory based on link:https://agroal.github.io/[Agroal], which is configured via the PooledConnectionFactoryConfiguration or
by specifying a properties file via `PooledConnectionFactoryConfiguration.propertyFile`. Properties must be specified with
the prefix "org.infinispan.agroal.". An example `agroal.properties` file is shown below:

[source,properties]
----
org.infinispan.agroal.metricsEnabled=false

org.infinispan.agroal.minSize=10
org.infinispan.agroal.maxSize=100
org.infinispan.agroal.initialSize=20
org.infinispan.agroal.acquisitionTimeout_s=1
org.infinispan.agroal.validationTimeout_m=1
org.infinispan.agroal.leakTimeout_s=10
org.infinispan.agroal.reapTimeout_m=10

org.infinispan.agroal.metricsEnabled=false
org.infinispan.agroal.autoCommit=true
org.infinispan.agroal.jdbcTransactionIsolation=READ_COMMITTED
org.infinispan.agroal.jdbcUrl=jdbc:h2:mem:PooledConnectionFactoryTest;DB_CLOSE_DELAY=-1
org.infinispan.agroal.driverClassName=org.h2.Driver.class
org.infinispan.agroal.principal=sa
org.infinispan.agroal.credential=sa
----

*  link:{javadocroot}/org/infinispan/persistence/jdbc/configuration/ManagedConnectionFactoryConfigurationBuilder.html[ManagedConnectionFactoryConfigurationBuilder]
is a connection factory that can be used within managed environments, such as application servers. It knows how to look
into the JNDI tree at a certain location (configurable) and delegate connection management to the DataSource.

*  link:{javadocroot}/org/infinispan/persistence/jdbc/configuration/SimpleConnectionFactoryConfigurationBuilder.html[SimpleConnectionFactoryConfigurationBuilder]
is a factory implementation that will create database connection on a per invocation basis. Not recommended in production.

The `PooledConnectionFactory` is generally recommended for stand-alone deployments (i.e. not running within AS or servlet container).
`ManagedConnectionFactory` can be used when running in a managed environment where a `DataSource` is present, so that
connection pooling is performed within the `DataSource`.

== Sample configurations

Below is a sample configuration for the link:{javadocroot}/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.html[JdbcStringBasedStore].
For detailed description of all the parameters used refer to the link:{javadocroot}/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.html[JdbcStringBasedStore].

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/persistence_example_jdbc.xml[]
----

[source,java]
----
include::code_examples/PersistenceJdbcStringBasedStore.java[]
----

Finally, below is an example of a JDBC cache store with a managed connection factory, which is chosen implicitly by specifying a datasource JNDI location:

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/persistence_example_ds_jndi.xml[]
----

[source,java]
----
include::code_examples/PersistenceDatasourceJndi.java[]
----

.Apache Derby users
NOTE: If you're connecting to an Apache Derby database, make sure you set dataColumnType to BLOB: `<data-column name="DATA_COLUMN" type="BLOB"/>`
