[id='configuring_server_logs_cli-{context}']
= Changing {brandname} Server Logging Configuration at Runtime

Use the command line interface to change the logging configuration of {brandname} servers at runtime.
Use this functionality to temporarily make modifications to the logging configuration, for example while investigating a problem.

.Note
Modifying the logging configuration via the CLI is a runtime-only operation:

* any changes will not be persisted to the `log4j2.xml` file.
Restarting any individual server or the entire cluster will cause the logging configuration to be reset to that defined in the `log4j2.xml` file.
* the changes only apply to the nodes that are present in the cluster at invocation time.
Any nodes that are started after the modifications will be using their default logging configuration.


.Listing appenders
List all appenders defined on the server:

----
[//containers/default]> logging list-appenders
----

The above command will return:

[source,json,options="nowrap",subs=attributes+]
----
{
  "STDOUT" : {
    "name" : "STDOUT"
  },
  "JSON-FILE" : {
    "name" : "JSON-FILE"
  },
  "HR-ACCESS-FILE" : {
    "name" : "HR-ACCESS-FILE"
  },
  "FILE" : {
    "name" : "FILE"
  },
  "REST-ACCESS-FILE" : {
    "name" : "REST-ACCESS-FILE"
  }
}
----

.Listing loggers
List all logger configurations defined on the server:

----
[//containers/default]> logging list-loggers
----

The above command will return:

[source,json,options="nowrap",subs=attributes+]
----
[ {
  "name" : "",
  "level" : "INFO",
  "appenders" : [ "STDOUT", "FILE" ]
}, {
  "name" : "org.infinispan.HOTROD_ACCESS_LOG",
  "level" : "INFO",
  "appenders" : [ "HR-ACCESS-FILE" ]
}, {
  "name" : "com.arjuna",
  "level" : "WARN",
  "appenders" : [ ]
}, {
  "name" : "org.infinispan.REST_ACCESS_LOG",
  "level" : "INFO",
  "appenders" : [ "REST-ACCESS-FILE" ]
} ]
----

.Adding/modifying loggers
You can add/modify logger configurations via the `set` subcommand, by specifying the logger name and the level.

For example, the following command will set the logging level for the `org.infinispan` package to `DEBUG`.
----
[//containers/default]> logging set --level=DEBUG org.infinispan
----

.Removing loggers
You can remove existing logger configurations via the `remove` subcommand.

For example, the following command will remove the `org.infinispan` logger configuration, meaning that the root configuration will be used instead:
----
[//containers/default]> logging remove org.infinispan
----
