[id='configuring-cluster-role-mapper_{context}']
= Configuring the cluster role mapper

The cluster role mapper maintains a dynamic mapping between principals and roles, by storing it in the cluster registry.
You can manipulate these mappings using either the CLI or the REST API.
By default, the mapping is performed using a strict string equivalence between principal names and roles. It is possible to configure the cluster role mapper to apply transformation to the principal name before performing a lookup.

.Procedure

. Open your {brandname} configuration for editing.
. Specify a name rewriter for the cluster role mapper as part of the security authorization in the Cache Manager configuration.
. Save the changes to your configuration.

== Cluster role mapper name rewriters

Principal names may have different forms, depending on the security realm type:

* Properties and Token realms may return simple strings
* Trust and LDAP realms may return X.500-style distinguished names
* Kerberos realms may return `user@domain`-style names

Names can be normalized to a common form using one of the following transformers.



=== Case Principal Transformer

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/cluster_role_mapper_rewrite_case.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/cluster_role_mapper_rewrite_case.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/cluster_role_mapper_rewrite_case.yaml[]
----

=== Regex Principal Transformer

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/cluster_role_mapper_rewrite_regex.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/cluster_role_mapper_rewrite_regex.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/cluster_role_mapper_rewrite_regex.yaml[]
----

[role="_additional-resources"]
.Additional resources
* link:{configdocroot}[{brandname} configuration schema reference]
