[id='update-index-schema_{context}']
= Updating index schema
Update index schema operation lets you acquire additional schema changes without downtime.
When the schema changes don't affect the existing schema model, you can update the index schema without removing and recreating previously indexed data.
Updating index schema is much faster than rebuilding the index but you can update schema only when your changes does not affect existing index schema.

[IMPORTANT]
====
When you change definitions of indexed types or analyzers or when you delete them, you must rebuild the index.
====

.Procedure

* Update index schema for a given cache:
** Call the `updateIndexSchema()` method to programmatically update the index schema from a Hot Rod Java client:
+
[source,java]
----
remoteCacheManager.administration().updateIndexSchema("MyCache");
----
+
[TIP]
====
For remote caches, you can update schema from the {brandname} Console or using the link:{rest_docs}#rest_v2_query_updateIndexSchema[REST API].
====

.Additional resources
* link:{query_docs}#rebuilding-indexes_{context}[Rebuilding indexes]
