[id='configure_off_heap-{context}']
= Using Off-Heap Memory
Configure {brandname} to store cache entries in native memory outside the JVM
heap space.

.Procedure

. Create a configuration for any type of cache.
. Store cache entries in off-heap memory.
+
* Declaratively: Add the `storage="OFF_HEAP"` attribute to the `memory` element.
* Programmatically: Call the `storage(OFF_HEAP)` method in the `MemoryConfigurationBuilder` class.
+
. Configure eviction to limit the amount of off-heap memory that the cache can use. You can use eviction based on total number of entries (`max-count`) or maximum amount of memory (`max-size`).
. Configure any binary encoding for cache entries. For optimal results, use the `application/x-protostream` MediaType to store entries in Protobuf format.
. Create caches that use the configuration.

.Declarative cache configuration

[source,xml,options="nowrap"]
----
include::config_examples/max_size_offheap.xml[]
----

.Programmatic cache configuration

[source,java,options="nowrap"]
----
include::code_examples/MaxCountOffHeap.java[]
----

* link:{configdocroot}[{brandname} Configuration Schema Reference]
* link:{javadocroot}/org/infinispan/configuration/cache/MemoryConfigurationBuilder.html[org.infinispan.configuration.cache.MemoryConfigurationBuilder]
