= Verifying {brandname} Cluster Discovery
{brandname} servers running on the same network discover each other with the `MPING` protocol.

This procedure shows you how to use {brandname} server command arguments to
start two instances on the same host and verify that the cluster view forms.

.Prerequisites
Start a {brandname} server.

.Procedure

. Install and run a new {brandname} server instance.
.. Open a terminal in `{server_home}`.
.. Copy the root directory to `server2`.
+
[source,options="nowrap",subs=attributes+]
----
$ cp -r server server2
----
+
. Specify a port offset and the location of the `server2` root directory.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/start_server2.adoc[]
----

.Verification

Running servers return the following messages when new servers join clusters:

[source,options="nowrap",subs=attributes+]
----
INFO  [org.infinispan.CLUSTER] (jgroups-11,<server_hostname>)
ISPN000094: Received new cluster view for channel cluster:
[<server_hostname>|3] (2) [<server_hostname>, <server2_hostname>]
INFO  [org.infinispan.CLUSTER] (jgroups-11,<server_hostname>)
ISPN100000: Node <server2_hostname> joined the cluster
----

Servers return the following messages when they join clusters:

[source,options="nowrap",subs=attributes+]
----
INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (main)
ISPN000078: Starting JGroups channel cluster
INFO  [org.infinispan.CLUSTER] (main)
ISPN000094: Received new cluster view for channel cluster:
[<server_hostname>|3] (2) [<server_hostname>, <server2_hostname>]
----

.Reference
link:{runtime_readme}[{brandname} Server README] describes command line
arguments for the `server` script.
