[id='bringing-backup-locations-offline-online_{context}']
= Bringing backup locations offline and online

Take backup locations offline manually and bring them back online.

.Prerequisites

* Create a CLI connection to {brandname}.

.Procedure

. Check if backup locations are online or offline with the [command]`site status` command:
+
[source,options="nowrap",subs=attributes+]
----
site status --cache=cacheName --site=NYC
----
+
[NOTE]
====
`--site` is an optional argument. If not set, the CLI returns all backup
locations.
====
+
[TIP]
====
Use the `--all-caches` option to get the backup location status for all caches.
====

. Manage backup locations as follows:
+
* Bring backup locations online with the [command]`bring-online` command:
+
[source,options="nowrap",subs=attributes+]
----
site bring-online --cache=customers --site=NYC
----
+
* Take backup locations offline with the [command]`take-offline` command:
+
[source,options="nowrap",subs=attributes+]
----
site take-offline --cache=customers --site=NYC
----

[TIP]
====
Use the `--all-caches` option to bring a backup location online, or take a backup location offline, for all caches.
====

For more information and examples, run the [command]`help site` command.
