[id='configuring-metrics_{context}']
= Enabling {brandname} tracing

{brandname} generates tracing spans that are compatible with the OpenTelemetry open standard.
At the time of writing tracing is defined at global level (once for all caches) passing the following system properties to the Infinispan server:

.tracing.properties
[source,options="nowrap",subs=attributes+]
----
include::properties/tracing.properties[]
----
<1> Globally enables the tracing.
<2> The OTLP (OpenTelemetry protocol) exporter is the recommended format to export tracing data.
<3> Specify here service name. The default name is `Infinispan Server`.
<4> Specify here the OpenTelemetry collector endpoint
====

.Procedure

* Use `-D<property-name>=<property-value>` arguments to set tracing system properties as required.

For our case.

* Pass the following system properties to {brandname} Server at startup:
+
[source,options="nowrap",subs=attributes+]
----
bin/server.sh -Dinfinispan.tracing.enabled=true -Dotel.traces.exporter=otlp -Dotel.service.name=my-infinispan-server -Dotel.exporter.otlp.endpoint=http://otlp-collector-host:4317
----
====

[NOTE]
====
To see more configuration options you can have a look at link:https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md[OpenTelemetry SDK Autoconfigure].
====
