[id='configuring-sql-cache-stores-query_{context}']
= Configuring SQL query stores

Add SQL query cache stores so {brandname} can preload your caches from database tables.

.Prerequisites

* Provide {brandname} with Protobuf schema that describe any composite keys and values in your database tables.
+
{brandname} recommends annotating your Java classes and creating serialization context initializers.
* Remote caches: Copy database drivers to the `server/lib` directory in your {brandname} Server installation.
* Embedded caches: Add the `infinispan-cachestore-sql` dependency to your `pom` file and make sure database drivers are on your application classpath.
+
[source,xml,options="nowrap",subs=attributes+]
----
include::dependencies_maven/persistence_sql_store.xml[]
----

.Procedure

. Create a SQL cache store configuration in one of the following ways:
+
* Declaratively, add the `persistence` element or field then add `query-jdbc-store` with the following schema namespace:
+
[source,xml,options="nowrap",subs=attributes+]
----
xmlns="urn:infinispan:config:store:sql:{schemaversion}"
----
+
* Programmatically, add the following methods to your `ConfigurationBuilder`:
+
[source,xml,options="nowrap",subs=attributes+]
----
persistence().addStore(QueriesJdbcStoreConfigurationBuilder.class)
----

. Specify the dialect of the database with either the `dialect` attribute or the `dialect()` method.
. Configure any properties for the SQL cache store as appropriate.
+
For example, specify if the cache store is shared between multiple cache instances with either the `shared` attribute or the `shared()` method.
+
If you want your SQL queries to update and delete entries, add the `read-only="false"` attribute or the `.ignoreModifications(false)` method to allow modifications to persistent storage.
+
. Add a JDBC connection factory so that {brandname} can connect to the database.
. Specify the SQL query for loading data with either the `queries` element or the `queries()` method.
.. Add `SELECT`, `SELECT ALL`, and `SIZE` clauses to your query.
.. Add `DELETE`, `DELETE ALL`, and `UPSERT` clauses if the cache store allows modifications.
+
* `SELECT`, `SELECT ALL` must return the same columns.
* `DELETE` must take the same parameters as `SELECT`.
* `UPSERT` must take the same named parameters as those returned by `SELECT` and `SELECT ALL`.
. Configure a Protobuf schema if database tables contain composite keys or values.
.. Add the `schema` element or the `.schemaJdbcConfigurationBuilder()` method and specify parameters for your Protobuf schema.
.. Set the `embedded-key="true"` attribute or `.embeddedKey(true)` method if values also contain keys.

[discrete]
== SQL query store configuration

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/persistence_sql_query.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/persistence_sql_query.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/persistence_sql_query.yaml[]
----

.ConfigurationBuilder
[source,java,options="nowrap",subs=attributes+,role="secondary"]
----
include::code_examples/PersistenceSqlQuery.java[]
----

[role="_additional-resources"]
.Additional resources
* link:{config_docs}#jdbc-connection-factories_persistence[JDBC connection factories]
