[id='configuring-global-persistent-location_{context}']
= Configuring Global Persistent Location

{brandname} preserves global state so that it can restore cluster topology and cached data after restart.
If you enable global state in your {brandname} configuration, you should also configure a suitable location for {brandname} to persist global state.

Global state is enabled by default with {brandname} Server, which persists cluster state to the `{server_home}/server/data` directory so it can perform graceful shutdowns.
You do not need to configure a global persistent location for {brandname} Server deployments in most cases.

For embedded caches, {brandname} defaults to the `user.dir` system property as the global persistent location, which is generally the directory where your application starts.
If your embedded caches are clustered then you should enable global state as a best practice so you can always restore cluster topology.
You should also configure a sensible global persistent location that is unique to each {brandname} node in the cluster.

.Procedure

. Enable global state in one of the following ways:
+
* Add the `global-state` element to your {brandname} configuration.
* Call the `globalState().enable()` methods in the `GlobalConfigurationBuilder` API.
+
. Specify a global persistent location.
+
* If the global persistent location is unique to each {brandname} instance, specify the `persistent-location` element or call the `persistentLocation()` method.
* If the global persistent location is available to all {brandname} instances, specify the `shared-persistent-location` element or call the `sharedPersistentLocation(String)` method on the `GlobalStateConfigurationBuilder`.
+
.. Set a value for `path` to define the persistent location for global state.
+
[TIP]
====
If you plan to use a file-based cache store for persistence, you can specify a directory on the host filesystem as the path.
====
+
.. Set a value for `relative-to` to configure the directory to which the path is relative.

.Declarative
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::config_examples/global_persistent_location.xml[]
----

.Programmatic
[source,java,options="nowrap",subs=attributes+,role="secondary"]
----
include::code_examples/GlobalPersistentLocation.java[]
----

[role="_additional-resources"]
.Additional resources
* link:{configdocroot}[{brandname} configuration schema]
* link:{javadocroot}/org/infinispan/configuration/global/GlobalStateConfiguration.html[org.infinispan.configuration.global.GlobalStateConfiguration]
