[id='setting-up-credential-keystores_{context}']
= Setting up credential keystores

Create keystores that encrypt credential for {brandname} Server access.

A credential keystore contains at least one alias that is associated with an encrypted password.
After you create a keystore, you specify the alias in a connection configuration such as a database connection pool.
{brandname} Server then decrypts the password for that alias from the keystore when the service attempts authentication.

You can create as many credential keystores with as many aliases as required.

.Procedure

. Open a terminal in `{server_home}`.
. Create a keystore and add credentials to it with the [command]`credentials` command.
+
[TIP]
====
By default, keystores are of type PKCS12.
Run [command]`help credentials` for details on changing keystore defaults.
====
+
The following example shows how to create a keystore that contains an alias of "dbpassword" for the password "changeme".
When you create a keystore you also specify a password for the keystore with the `-p` argument.
+
Linux::
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/credentials_nix.adoc[]
----
+
Microsoft Windows::
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/credentials_win.adoc[]
----
+
. Check that the alias is added to the keystore.
+
[source,options="nowrap",subs=attributes+]
----
$ bin/cli.sh credentials ls -p "secret1234!"
dbpassword
----
+
. Configure {brandname} to use the credential keystore.
.. Specify the name and location of the credential keystore in the `credential-stores` configuration.
.. Provide the credential keystore and alias in the `credential-reference` configuration.
+
[TIP]
====
Attributes in the `credential-reference` configuration are optional.

* `store` is required only if you have multiple keystores.
* `alias` is required only if the keystore contains multiple aliases.
====

You can also use a password located in another credential store as the master password for a new credential store.
While a credentials keystore provides a way to store encrypted passwords outside the configuration files, it still requires a clear-text password in order to be accessed. It is possible to use password masking or externalization to provide an added layer of security.


== Externalizing and masking credential keystore passwords

Instead of providing your credential store’s master password in the clear, you can choose to provide that password using a pseudo credential store. You have the following options:

=== External command

External command using `java.lang.Runtime#exec(java.lang.String)`. If parameters are needed, they are supplied using a space-separated list of strings. An external command refers to any executable from the operating system, for example a shell script or an executable binary. The password is read from the standard output of the executed command.

[discrete]
=== External command credentials

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/server_command_credentials.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/server_command_credentials.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/server_command_credentials.yaml[]
----

=== MASK

Masked password using PBE, or Password Based Encryption. It must be in the following format, which includes the SALT and ITERATION values: `MASKED_VALUE;SALT;ITERATION`

Example

`0ipwVedEfNuWyG2rijJTFE;pepper99;100`

You can use the CLI to create masked passwords:

[source,options="nowrap",subs=attributes+]
----
$ bin/cli.sh credentials mask -i 100 -s pepper99 mysecret
0ipwVedEfNuWyG2rijJTFE;pepper99;100
----

[discrete]
=== Masked credentials

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/masked_credentials.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/masked_credentials.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/masked_credentials.yaml[]
----

