[id='hotrod_near_cache']
= Configuring Near Caching
Hot Rod Java clients can keep local caches that store recently used data, which
significantly increases performance of `get()` and `getVersioned()` operations
because the data is local to the client.

When you enable near caching with Hot Rod Java clients, calls to `get()` or
`getVersioned()` calls populate the near cache when entries are retrieved from
servers. When entries are updated or removed on the server-side, entries in the
near cache are invalidated. If keys are requested after they are invalidated,
clients must fetch the keys from the server again.

You can also configure the number of entries that can near caches can contain.
When the maximum is reached, near-cached entries are evicted.

.Near cache considerations

[IMPORTANT]
====
Do not use maximum idle expiration with near caches because near-cache reads do
not propagate the last access time for entries.
====

* Near caches are cleared when clients failover to different servers when using clustered cache modes.

* You should always configure the maximum number of entries that can reside in
the near cache. Unbounded near caches require you to keep the size of the near
cache within the boundaries of the client JVM.

* Near cache invalidation messages can degrade performance of write operations

.Procedure

. Set the near cache mode to `INVALIDATED` in the client configuration.
. Define the size of the near cache by specifying the maximum number of entries.

[source,java]
----
import org.infinispan.client.hotrod.configuration.ConfigurationBuilder;
import org.infinispan.client.hotrod.configuration.NearCacheMode;
...

// Bounded invalidated near cache
ConfigurationBuilder bounded = new ConfigurationBuilder();
bounded.nearCache()
  .mode(NearCacheMode.INVALIDATED)
  .maxEntries(100);

// Unbounded invalidated near cache
ConfigurationBuilder unbounded = new ConfigurationBuilder();
unbounded.nearCache()
  .mode(NearCacheMode.INVALIDATED)
  .maxEntries(-1);
----

[TIP]
====
Use `cacheNamePattern()` to define a regular expression to match caches for
which you want to enable near caching. Because the configuration is shared for
all caches from the `RemoteCacheManager`, this lets you enable near-caching for
only the caches that match the regular expression.
====

[source,java]
----
// Bounded invalidated near cache with pattern matching
ConfigurationBuilder bounded = new ConfigurationBuilder();
bounded.nearCache()
  .mode(NearCacheMode.INVALIDATED)
  .maxEntries(100)
  // Enable near-cache only for caches whose name starts with 'near'
  .cacheNamePattern("near.*");
----
