[id='configuring-server-keystores_{context}']
= Configuring {brandname} Server Keystores
Add keystores to {brandname} Server and configure it to present SSL/TLS certificates that verify its identity to clients.
If a security realm contains TLS/SSL identities, it encrypts any connections to {brandname} Server endpoints that use that security realm.

.Prerequisites

* Create a keystore that contains certificates, or certificate chains, for {brandname} Server.

{brandname} Server supports the following keystore formats: JKS, JCEKS, PKCS12/PFX and PEM.
BKS, BCFKS, and UBER are also supported if the https://www.bouncycastle.org/[Bouncy Castle] library is present.

[IMPORTANT]
====
In production environments, server certificates should be signed by a trusted Certificate Authority, either Root or Intermediate CA.
====

.Procedure

. Add the keystore that contains SSL/TLS identities for {brandname} Server to the `{server_home}/server/conf` directory.
. Add a `server-identities` definition to the {brandname} Server security realm.
. Specify the keystore file name with the `path` attribute.
. Provide the keystore password and certificate alias with the `keystore-password` and `alias` attributes.

.{brandname} Server keystore configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::xml/server_ssl_identity_truststore.xml[]
----

[NOTE]
====
PEM files can be used as keystores provided they contain a private key in PKCS#1 or PKCS#8 format and one
or more certificates. These keystores should be configured with an empty password: `password=""`.
====

.Next steps

Configure clients with a trust store so they can verify SSL/TLS identities for {brandname} Server.

[role="_additional-resources"]
.Additional resources
* link:{hotrod_docs}#configuring-hotrod-encryption_hotrod-client-configuration[Configuring Hot Rod client encryption]
