[id='jgroups_authentication']
= Configuring JGroups Authentication
Configure JGroups authentication to restrict {brandname} cluster membership.
When joining or merging, nodes must authenticate with the cluster.

.Procedure

* Add the SASL mechanism to your JGroups configuration before the `GMS`
protocol, as in the following example:

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/jgroups_sasl_auth.xml[]
----

The preceding example uses `DIGEST-MD5` so that each node must declare valid
credentials when joining a {brandname} cluster.

Within the cluster, coordinator nodes act as SASL servers. All other nodes act
as SASL clients. For this reason you need two different `CallbackHandlers`, a
+server_callback_handler_class+ for the coordinator and a
+client_callback_handler_class+ for the other nodes.

.Cluster authorization

To implement node authorization, configure the server callback handler to throw
an exception as in the following example:

[source,java]
----
public class AuthorizingServerCallbackHandler implements CallbackHandler {

    @Override
    public void handle(Callback[] callbacks) throws IOException, UnsupportedCallbackException {
        for (Callback callback : callbacks) {
            ...
            if (callback instanceof AuthorizeCallback) {
                AuthorizeCallback acb = (AuthorizeCallback) callback;
                UserProfile user = UserManager.loadUser(acb.getAuthenticationID());
                if (!user.hasRole("myclusterrole")) {
                    throw new SecurityException("Unauthorized node " +user);
                }
            }
            ...
        }
    }
}
----
