[id='configuring-server-endpoints_{context}']
= Configuring {brandname} Server endpoints

Control how the different server endpoints bind to sockets and use security realm configuration.

.Prerequisites

* Add socket bindings and security realms to your {brandname} Server configuration.

.Procedure

. Open your {brandname} Server configuration for editing.
. Wrap multiple `endpoint` configurations with the `endpoints` element.
. Specify the socket binding that the endpoint uses with the `socket-binding` attribute.
. Specify the security realm that the endpoint uses with the `security-realm` attribute.
. Disable administrator access with the `admin="false"` attribute, if required.
+
With this configuration users cannot access {brandname} Console or the Command Line Interface (CLI) from the endpoint.
. Save the changes to your configuration.

[NOTE]
====
{brandname} Server must be configured with at least one endpoint which has a REST connector with administrative
capabilities.
====


[discrete]
== Multiple endpoint configuration

The following {brandname} Server configuration creates endpoints on separate socket bindings with dedicated security realms
and disabling administrative access on the `public` endpoint:

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/server_endpoints_custom.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/server_endpoints_custom.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/server_endpoints_custom.yaml[]
----

[role="_additional-resources"]
.Additional resources
* link:{server_docs}#server-interfaces[Network interfaces and socket bindings]
