[id='downloading_servers-{context}']
= Downloading Server Distributions
The {brandname} server distribution is an archive of Java libraries (`JAR` files), configuration files, and a `data` directory.

.Procedure
//Community
ifdef::community[]
. Download {brandname} {infinispanversion} Server from link:{download_url}[{brandname} downloads].
. Run the `sha1sum` command with the server download archive as the argument, for example:
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/sha_ispn_server.adoc[]
----
+
. Compare with the `SHA-1` checksum value on the {brandname} downloads page.
endif::community[]
//Downstream
ifdef::downstream[]
. Access the {portal}.
. Download {FullProductName} {ProductVersion} Server from the link:{download_url}[software downloads section].
. Run the `md5sum` or `sha256sum` command with the server download archive as the argument, for example:
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/sha_rhdg_server.adoc[]
----
+
. Compare with the `MD5` or `SHA-256` checksum value on the {brandname} *Software Details* page.
endif::downstream[]

.Reference

//Community
ifdef::community[]
The {brandname} Server README, available in the distribution, provides example commands for running the server, describes folders in the `{server_home}` directory, and lists system properties you can use to customize the filesystem.
endif::community[]
//Downstream
ifdef::downstream[]
* link:{runtime_readme}[{brandname} Server README] describes the contents of the server distribution.
endif::downstream[]
