[id='configure_eviction_size-{context}']
= Configuring the Maximum Amount of Memory for {brandname} Caches
Limit the size of the data container for cache entries to a maximum amount of
memory. Performing eviction based on the maximum amount of memory requires you
to use a binary-based storage format for the data container.

.Procedure

. Configure your {brandname} cache to use a storage format that supports binary encoding.
+
[NOTE]
====
To guarantee the format that {brandname} uses to store your data, you should
always specify an encoding for caches.

Alternatively, you can define a global marshaller with the `serialization`
element in a declarative configuration or by calling the `serialization()` 
method in the `GlobalConfigurationBuilder` class. In this case, {brandname}
encodes entries as the MediaType for the global marshaller.
====
+
. Configure the maximum amount of memory, in bytes, that caches can use before
{brandname} performs eviction.
+
* Declaratively: Set the `max-size` attribute.
* Programmatically: Use the `maxSize()` method.
+
. Optionally specify a byte unit of measurement. The default is B (bytes). Refer to the configuration schema for supported units.
. Configure an eviction strategy to control how {brandname} removes entries.
+
* Declaratively: Set the `when-full` attribute.
* Programmatically: Use the `whenFull()` method.


.Declarative example

[source,xml,options="nowrap"]
----
<local-cache name="off_heap_binary">
  <encoding media-type="application/x-protostream"/>
  <memory max-size="1.5GB" when-full="REMOVE"/>
</local-cache>
----

.Programmatic example

[source,java,options="nowrap"]
----
ConfigurationBuilder cfg = new ConfigurationBuilder();

cfg
  .encoding()
    .mediaType("application/x-protostream")
  .memory()
    .maxSize("1.5GB")
    .whenFull("REMOVE")
  .build());
----

.Reference

* link:{configdocroot}[{brandname} Configuration Schema Reference]
* link:{javadocroot}/org/infinispan/configuration/cache/EncodingConfiguration.html[org.infinispan.configuration.cache.EncodingConfiguration]
* link:{javadocroot}/org/infinispan/configuration/cache/MemoryConfigurationBuilder.html[org.infinispan.configuration.cache.MemoryConfigurationBuilder]
* link:{dev_docs}#encoding_media_type[MediaType Configuration]
