[id='generating_protostream_sci-{context}']
= Generating Serialization Context Initializers
{brandname} provides a `protostream-processor` artifact processes Java annotations in your classes at compile time to generate Protobuf schemas, marshallers, and a concrete implementation of the `SerializationContextInitializer` interface.

[NOTE]
====
By default, implementation names are the annotated class name with an "Impl" suffix.
====

.Prerequisites

* Add the `protostream-processor` dependency to your `pom.xml`.
+
[source,xml]
----
include::dependencies_maven/protostream-processor.xml[]
----

.Procedure

. Annotate the Java objects that you want to marshall with `@ProtoField` and `@ProtoFactory`.
+
[source,java]
.Author.java
----
include::code_examples/Author.java[]
----
+
[source,java]
.Book.java
----
include::code_examples/Book.java[]
----
+
. If necessary, create an adaptor class for any external, third-party Java object classes and add the `@ProtoAdaptor` annotation.
+
[source,java]
----
include::code_examples/ProtoAdaptor.java[]
----
+
. Define an interface that extends `SerializationContextInitializer`.
. Annotate the interface with `@AutoProtoSchemaBuilder` so that {brandname} automatically registers your `SerializationContextInitializer` implementation.
+
[source,java]
----
include::code_examples/LibraryInitializer.java[]
----
+
<1> Names the generated `.proto` schema file.
<2> Sets the path under `target/classes` where the schema file is generated.

.Reference

* link:#manually_registering_sci-marshalling[Manually Registering Serialization Context Initializers]
