[id='manually_registering_sci-{context}']
= Manually Registering Serialization Context Initializers
If you prefer, you can disable automatic registration of `SerializationContextInitializer` implementations and then register them manually.

[NOTE]
====
Manually registering `SerializationContextInitializer` implementations disables automatic registration.
If you manually register one `SerializationContextInitializer` implementation, you must register all other implementations for them to take effect.
====

.Procedure

. Set a value of `false` for the `AutoProtoSchemaBuilder.service` annotation.
+
[source,java]
----
@AutoProtoSchemaBuilder(
      includeClasses = SomeClass.class,
      ...
      service = false
)
----
+
. Manually register `SerializationContextInitializer` implementations either programmatically or declaratively, as in the following examples:

.Programmatic configuration

[source,java]
----
include::code_examples/ProtoStreamMarshaller.java[]
----

.Declarative configuration

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/protostream_marshaller.xml[]
----
