[id='enable_jmx']
= Enabling and Configuring JMX
You can enable JMX with {brandname} servers to collect statistics and perform
administrative operations.

Start the server with the following properties: `-Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false`

[NOTE]
====
You can enable JMX without enabling statistics if you want to use management
operations only. In this case, {brandname} provides `0` values for all
statistics.
====

.Procedure

* Enable JMX declaratively or programmatically.

.Declaratively

[source,xml,options="nowrap",subs=attributes+]
----
<cache-container>
  <jmx enabled="true" /> <1>
</cache-container>
----

.Programmatically

[source,java]
----
GlobalConfiguration globalConfig = new GlobalConfigurationBuilder()
  .jmx().enable() <1>
  .build();
----

<1> registers {brandname} JMX MBeans.

.JMX Java Client
In order to retrieve or do operations in the server you can create your own Java Client:
[source,java]
----
String host = "127.0.0.1";
Integer jmxPort = 9999;
JMXServiceURL url = new JMXServiceURL(String.format("service:jmx:rmi:///jndi/rmi://%s:%d/jmxrmi", host, jmxPort));
JMXConnector jmxConnector = JMXConnectorFactory.connect(url);
MBeanServerConnection connection =  jmxConnector.getMBeanServerConnection();
----

.Reference

* link:#enable_statistics[Enabling {brandname} Statistics]
