[id='enabling-jmx-port_{context}']
= Enabling JMX remote ports
Provide unique remote JMX ports to expose {brandname} MBeans through connections in JMXServiceURL format.

//Server Guide
ifdef::remote_caches[]
[NOTE]
====
{brandname} Server does not expose JMX remotely via the single port endpoint.
If you want to remotely access {brandname} Server via JMX you must enable a remote port.
====
endif::remote_caches[]

.Procedure

Start the server with JMX remoting enabled using one of the supported ways:

* Using the `--jmx` option. This will enable JMX remoting on port `9999` without SSL and requiring authentication
to the default security realm. Users authenticating to JMX should have either the `controlRole` (for read/write access)
or the `monitorRole` (for read-only access). Users not belonging to either of those roles will not be able to access
any JMX resources. If there is no default security realm, access will always be denied.
+
[source,options="nowrap",subs=attributes+]
----
bin/server.sh --jmx 9999
----

* Using any of the standard JMX remoting system properties {brandname} at startup. Refer to the https://docs.oracle.com/en/java/javase/11/management/monitoring-and-management-using-jmx-technology.html#GUID-F08985BB-629A-4FBF-A0CB-8762DF7590E0[JDK Monitoring and Management using JMX technology] guide for details.
+
[source,options="nowrap",subs=attributes+]
----
bin/server.sh -Dcom.sun.management.jmxremote.port=9999
----
