[id='creating-users_{context}']
= Creating {brandname} users

Add credentials to authenticate with {brandname} Server deployments through Hot Rod and REST endpoints.
Before you can access the {brandname} Console or perform cache operations you must create at least one user with the {brandname} command line interface (CLI).

[TIP]
====
{brandname} enforces security authorization with role-based access control (RBAC).
Create an `admin` user the first time you add credentials to gain full `ADMIN` permissions to your {brandname} deployment.
====

.Prerequisites

* Download and install {brandname} Server.

.Procedure

. Open a terminal in `{server_home}`.
. Create an `admin` user, belonging to the `admin` group with the [command]`user create` command.
+
[source,sh,options="nowrap",subs=attributes+]
----
include::cmd_examples/user_tool_nix.adoc[]
----
+
[TIP]
====
Run [command]`help user` from a CLI session to get complete command details.
====

.Verification

Open `user.properties` and confirm the user exists.

[source,options="nowrap",subs=attributes+]
----
cat server/conf/users.properties

admin=scram-sha-1\:BYGcIAwvf6b...
----

[NOTE]
====
Adding credentials to a properties realm with the CLI updates the local property realm files on the server instance where you run the command. 
You must manually synchronize property realm credentials across all nodes in the cluster.

The same limitation applies to user groups and role assignments. 
Changes to users, groups, and roles are not automatically distributed across the cluster.

Changes to a properties realm do not take effect until the server reloads the updated configuration. 
After reloading the server, flush security realm caches across the cluster:

[source,options="nowrap",subs=attributes+]
----
server aclcache flush
----
====
