[id='cli-set-topology-caches_{context}']
= Set a Stable Topology

By default, after a cluster shutdown, {brandname} waits for all nodes to join the cluster and restore the topology.
However, we offer a CLI command to mark the current topology stable for a specific cache.

[IMPORTANT]
====
The command does not operate on internal caches. There will be a loss of functionality for caches requiring access to the internal caches with missing members. For example, users will be unable to upload schemas to the internal cache for Protobuf schemas when there are missing nodes. Script execution and upload, and distributed locks are similarly affected.
====

.Procedure

. Create a CLI connection to {brandname}.
. Do one of the following:
+
* Set the current topology as stable for the given cache.
+
[source,options="nowrap",subs=attributes+]
----
topology set-stable cacheName
----
+
* If the number of nodes missing from the current topology is more than or equal to the number of owners, the force flag is necessary to confirm the operation.
+
[source,options="nowrap",subs=attributes+]
----
topology set-stable cacheName -f
----
+
If all the caches do not have the same number of owners, `numOwners`, then only some caches are affected. You can examine only the caches with a different number of owners and set the topology as stable for those caches. Note that the command only sets the topology for a single cache.  
+
[IMPORTANT]
====
If you use the force flag, you might lose data.
====

For more information about the [command]`topology set-stable` command, run [command]`topology set-stable -h`.
