[id='configuring-cli-startup_{context}']
= Setting {brandname} CLI Properties and Persistent Storage
Configure {brandname} CLI startup operations and customize the location for persistent storage.

.Prerequisites

Create at least one {brandname} user.

.Procedure

. Optionally set a custom path to the {brandname} CLI storage directory in one of the following ways:
+
* Using the `cli.dir` system property:
+
[source,options="nowrap",subs=attributes+]
----
$ bin/cli.sh -Dcli.dir=/path/to/cli/storage ...
----
+
* Using the `ISPN_CLI_DIR` environment variable:
+
[source,options="nowrap",subs=attributes+]
----
export ISPN_CLI_DIR=/path/to/cli/storage
$ bin/cli.sh ...
----
+
. Set values for configuration properties with the [command]`config set` command.
+
For example, set the `autoconnect-url` property so that the CLI automatically connects to that URL.
+
[NOTE]
====
For remote connections, specify the URL and provide credentials:

* `http[s]://<username>:<password>@<hostname>:<port>` for basic authentication.
* `http[s]://<token>@<hostname>:<port>` for OAuth authentication.
====
+
[source,bash,options="nowrap",subs=attributes+]
----
$ bin/cli.sh config set autoconnect-url http://<username>:<password>@<hostname>:11222
----
+
. Verify configuration properties with the [command]`config get` command.
+
[TIP]
====
Run [command]`help config` to review available configuration properties and get example usage.
====
