[id='dec_authz_config-{context}']
= Declaratively Configuring Authorization
Configure authorization in your `infinispan.xml` file.

.Procedure

. Enable the global authorization in the `cache-container` that automatically defines a set of default roles, permissions and a role mapper.
. Configure authorization for caches to restrict access based on user roles.

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/cache_authorization_implicit.xml[]
----

The above configuration will enable the following authorization features:

* ClusterRoleMapper
* a set of predefined roles:
** `admin`: a superuser role which has all the available permissions.
** `application`: a role which can access and manipulate the contents of resources (caches, counters) but cannot create or remove them.
** `deployer`: a role similar to `application` but which can also create and remove resources (caches, counters, schemas, scripts).
** `observer`: a role which has read-only access to the system.

.Reference

* link:{configdocroot}[{brandname} Configuration Schema Reference]
