[id='property-security-realms_{context}']
= Property realms
Property realms use property files to define users and groups.

* `users.properties` contains {brandname} user credentials.
Passwords can be pre-digested with the `DIGEST-MD5` and `DIGEST` authentication mechanisms.
* `groups.properties` associates users with roles and permissions.

[NOTE]
====
You can avoid authentication issues that relate to a property file by using the {brandname} CLI to enter the correct security realm name to the file. 
You can find the correct security realm name of your {brandname} Server by opening the `infinispan.xml` file and navigating to the `<security-realm name>` property. 
When you copy a property file from one {brandname} Server to another, make sure that the security realm name appropriates to the correct authentication mechanism for the target endpoint.
====

.users.properties
[source,options="nowrap",subs=attributes+]
----
include::properties/server_users.properties[]
----

.groups.properties
[source,options="nowrap",subs=attributes+]
----
include::properties/server_groups.properties[]
----

[discrete]
== Property realm configuration

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/server_properties_realm.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/server_properties_realm.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/server_properties_realm.yaml[]
----
