[id='cache-modes_{context}']
= Cache modes

[TIP]
====
{brandname} cache managers can create and control multiple caches that use
different modes. For example, you can use the same cache manager for local
caches, distributes caches, and caches with invalidation mode.
====

Local:: {brandname} runs as a single node and never replicates read or write operations on cache entries.

Replicated:: {brandname} replicates all cache entries on all nodes in a cluster and performs local read operations only.

Distributed:: {brandname} replicates cache entries on a subset of nodes in a cluster and assigns entries to fixed owner nodes. +
{brandname} requests read operations from owner nodes to ensure it returns the correct value.

Invalidation:: {brandname} evicts stale data from all nodes whenever operations modify entries in the cache. {brandname} performs local read operations only.

Scattered:: {brandname} stores cache entries across a subset of nodes. +
By default {brandname} assigns a primary owner and a backup owner to each cache entry in scattered caches. +
{brandname} assigns primary owners in the same way as with distributed caches, while backup owners are always the nodes that initiate the write operations. +
{brandname} requests read operations from at least one owner node to ensure it returns the correct value.
