[id='data_transcoding']
= Transcoders and Data Conversion
{brandname} uses `org.infinispan.commons.dataconversion.Transcoder` to convert
data between MediaType formats.

[source,java]
----
include::code_examples/Transcoder.java[]
----

[id='mediatype_override']
== Converting Data on Demand
You can deploy and run custom code on {brandname}, such as tasks, listeners,
and merge policies. Custom code on {brandname} can directly access data but
must also interoperate with clients that access the same data through different
endpoints. For example, you can create tasks that handle custom objects while
Hot Rod clients read and write data in binary format.

In this case, you can configure `application/x-protostream` as the cache
encoding to store data in binary format then configure your custom code to
perform cache operations using a different MediaType.

For example:

[source,java]
----
include::code_examples/EncodeMediaTypeOverride.java[]
----

Will return the value in JSON format:

[source,json]
----
{
   "_type":"org.infinispan.sample.Person",
   "name":"John",
   "surname":"Doe"
}
----

== Installing Transcoders in Embedded Deployments
{brandname} Server includes transcoders by default. However, when running
{brandname} as a library, you must add the following to your project:

[source,options="nowrap"]
----
org.infinispan:infinispan-server-core
----
