= Endpoint Connectors
You configure {brandname} server endpoints with connector declarations that
specify socket bindings, authentication mechanisms, and encryption
configuration.

The default endpoint connector configuration is as follows:

[source,xml,options="nowrap",subs=attributes+]
----
include::xml/endpoints_connectors.xml[]
----

* `endpoints` contains endpoint connector declarations and defines global
configuration for endpoints such as default socket bindings, security realms,
and whether clients must present valid TLS certificates.
* `<hotrod-connector/>` declares a Hot Rod connector.
* `<rest-connector/>` declares a REST connector.
* `<memcached-connector socket-binding="memcached"/>` declares a Memcached
connector that uses the memcached socket binding.

Declaring an empty `<endpoints/>` element implicitly enables the Hot Rod and REST connectors.

It is possible to have multiple `endpoints` bound to different sockets.
These can use different security realms and offer different authentication and encryption configurations.
The following configuration enables two endpoints on distinct socket bindings, each one with a dedicated security realm.
Additionally, the `public` endpoint disables administrative features, such as the console and CLI.

[source,xml,options="nowrap",subs=attributes+]
----
include::xml/endpoints_connectors_multiple.xml[]
----

.Reference

link:{configdocroot}[urn:infinispan:server] schema provides all available
endpoint configuration.
