[id='endpoint-connectors_{context}']
= Endpoint connectors
Connectors configure Hot Rod and REST endpoints to use socket bindings and security realms.

.Default endpoint configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::xml/server_endpoints_default.xml[]
----

[%autowidth,cols="1,1",stripes=even]
|===
|Configuration element or attribute |Description

|`endpoints`
|Wraps endpoint connector configuration.

|`endpoint`
|Declares a {brandname} Server endpoint that configures Hot Rod and REST connectors to use a socket binding and security realm.

|`hotrod-connector`
|Includes the Hot Rod endpoint in the `endpoint` configuration.

|`rest-connector`
|Includes the REST endpoint in the `endpoint` configuration.

|`resp-connector`
|Includes the RESP endpoint in the `endpoint` configuration.

|`memcached-connector`
|Includes the Memcached endpoint in the `endpoint` configuration.
|===

== Endpoint request limits

Each of the endpoints support a configuration option to limit request sizes. If the client sends a request
larger than this configured size the request may be met with an exception or even forcibly closing the client
connection.

These are all configured via the element `max-content-length`. This is configured in bytes and allows for a String
value with a size prefix (e.g. 128KB, 10MB, 1.5GB). Note this size is the entire request size and is not limited
to a single key or value.

.HotRod, RESP & Memcached endpoints

[source,xml,options="nowrap",subs=attributes+]
----
include::xml/server_endpoints_limits_hotrod_resp_memcached.xml[]
----

.REST endpoint

[source,xml,options="nowrap",subs=attributes+]
----
include::xml/server_endpoints_limits_rest.xml[]
----

[role="_additional-resources"]
.Additional resources
* link:../../configuration-schema/index.html[{brandname} schema reference]
