[id='embedded-custom-beans_{context}']
= Cache Manager Configuration Beans

You can customize the Cache Manager with the following configuration beans:

* `InfinispanGlobalConfigurer`
* `InfinispanCacheConfigurer`
* `Configuration`
* `InfinispanConfigurationCustomizer` deprecated in Spring Boot 3, removed in Spring Boot 4
* `InfinispanGlobalConfigurationCustomizer`

[IMPORTANT]
====
In Spring Boot 4, we removed the default cache `default` that could be
customized with the `InfinispanConfigurationCustomizer`.
Use `InfinispanCacheConfigurer` instead and define `default`.
[source,java,options="nowrap"]
----
include::code_examples/InfinispanCacheConfigurerDefault.java[]
----
====

[NOTE]
====
You can create one `InfinispanGlobalConfigurer` bean only.
However you can create multiple configurations with the other beans.
====

.InfinispanCacheConfigurer Bean

[source,java,options="nowrap"]
----
include::code_examples/InfinispanCacheConfigurer.java[]
----

.Configuration Bean

Link the bean name to the cache that it configures, as follows:

[source,java,options="nowrap"]
----
include::code_examples/CacheConfigurationBean.java[]
----

.Customizer Beans

[source,java,options="nowrap"]
----
include::code_examples/ConfigurationCustomizerBean.java[]
----
