[id='property_realm-{context}']
= Property Realms
Property realms use property files to define users and groups.

`users.properties` maps usernames to passwords in plain-text format. Passwords
can also be pre-digested if you use the `DIGEST-MD5` SASL mechanism or `Digest`
HTTP mechanism.

[source,options="nowrap",subs=attributes+]
----
include::config_examples/server_users.properties[]
----

`groups.properties` maps users to roles.

[source,options="nowrap",subs=attributes+]
----
include::config_examples/server_groups.properties[]
----

.Property realm configuration

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_properties_realm.xml[]
----

<1> Defines groups as roles for {brandname} server authorization.
<2> Specifies the `users.properties` file.
<3> Specifies that the file is relative to the `$ISPN_HOME/server/conf` directory.
<4> Specifies that the passwords in `users.properties` are in plain-text format.
<5> Specifies the `groups.properties` file.

.Supported authentication mechanisms

Property realms support the following authentication mechanisms:

* **SASL:** `PLAIN`, `+DIGEST-*+`, and `+SCRAM-*+`
* **HTTP (REST):** `Basic` and `Digest`
