[id='jmx_xsite-{context}']
= JMX MBeans for Cross-Site Replication
{brandname} provides JMX MBeans for cross-site replication that let you gather
statistics and perform remote operations.

The `org.infinispan:type=Cache` component provides the following JMX MBeans:

* `XSiteAdmin` exposes cross-site operations that apply to specific cache instances.
* `StateTransferManager` provides statistics for state transfer operations.
* `RpcManager` provides statistics about network requests for cross-site replication.
* `AsyncXSiteStatistics` provides statistics for asynchronous cross-site replication, including queue size and number of conflicts.

The `org.infinispan:type=CacheManager` component includes the following JMX MBean:

* `GlobalXSiteAdminOperations` exposes cross-site operations that apply to all caches in a cache container.

For details about JMX MBeans along with descriptions of available operations
and statistics, see the _{brandname} JMX Components_ documentation.

.Reference

link:{javadocroot}/jmxComponents.html[{brandname} JMX Components]
