[id='endpoint-connectors_{context}']
= Endpoint connectors
Connectors configure Hot Rod and REST endpoints to use socket bindings and security realms.

.Default endpoint configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::xml/server_endpoints_default.xml[]
----

[%autowidth,cols="1,1",stripes=even]
|===
|Configuration element or attribute |Description

|`endpoints`
|Wraps endpoint connector configuration.

|`endpoint`
|Declares a {brandname} Server endpoint that configures Hot Rod and REST connectors to use a socket binding and security realm.

|`hotrod-connector`
|Includes the Hot Rod endpoint in the `endpoint` configuration.

|`rest-connector`
|Includes the REST endpoint in the `endpoint` configuration.

|`resp-connector`
|Includes the RESP endpoint in the `endpoint` configuration.

|`memcached-connector`
|Includes the Memcached endpoint in the `endpoint` configuration.
|===

== Endpoint request limits

Endpoints, by default, impose a `10MB` limit on request sizes. 
If the client sends a request larger than the limit, the request may be met with an exception or the connection may be forcibly closed.
The limit is configured via the `max-content-length` attributed. This is expressed in bytes and allows for a string
value with a size suffix (e.g. 128KB, 10MB, 1.5GB). Note that this is the size of the entire request and is not limited to a single key or value.

.Hot Rod, RESP & Memcached endpoints

[source,xml,options="nowrap",subs=attributes+]
----
include::xml/server_endpoints_limits_hotrod_resp_memcached.xml[]
----

.REST endpoint

[source,xml,options="nowrap",subs=attributes+]
----
include::xml/server_endpoints_limits_rest.xml[]
----

[role="_additional-resources"]
.Additional resources
* link:../../configuration-schema/index.html[{brandname} schema reference]
