As in the case of link:{hotrod_docs}#propagation-hotrod-client-tracing[the HotRod client] in order to enable the tracing propagation,
a tracing is supposed to be set up on both client side and on {brandname} Server.

To configure OpenTelemetry tracing on the {brandname} server
see link:{server_docs}#opentelemetry-tracing[the {brandname} Server documentation].

Unlike the case of the HotRod client, in order to propagate The OpenTelemetry tracing spans to the {brandname} spans
it is necessary to do a little extra work to set on each REST invocation the trace context.

.Procedure

. Use the `io.opentelemetry.api.trace.propagation.W3CTraceContextPropagator` to extract the current tracing context.
. The extraction will produce a context map.
. Pass the context map in the header of the REST call

[source,java]
----
include::code_examples/RESTTracingPropagation.java[]
----

After that any tracing span generated by the client application that produce will be correlated
with the dependent Infinispan server spans.