[id='quick_start']
= {brandname} requirements

It's easy to get started with {brandname}. All you need is Java, dependency
management tooling, and either the {brandname} server or core libraries.

== Software Requirements

To run {brandname}, you'll need:

* Java 11 JDK at a minimum. {brandname} but also works with JDK 17, 18 and 19.
* Maven 3.2 or later. {brandname} also works with Gradle and Ivy.

== JDK
Choose your Java runtime and follow their installation instructions. For example, you could choose:

*  link:http://openjdk.java.net/install/[OpenJDK]
*  link:http://www.java.com/en/download/manual.jsp[Oracle Java SE]

== Maven

Run `mvn --version` to check your current Maven version. If you have Maven 3.2
or later, you are ready to go.

If you need to install Maven, visit link:https://maven.apache.org/install.html[https://maven.apache.org/install.html].

== Getting {brandname}

You can:

* Download the {brandname} Server distribution. Visit the link:https://infinispan.org/download/[Download {brandname}] page to get the latest stable release.
* Pull the link:https://quay.io/repository/infinispan/server?tab=tags[{brandname} image].
* Add the `infinispan-core` artifact to your `pom.xml` and use {brandname} directly in your project.

== {brandname} simple tutorials

See different capabilities in action with just a few simple steps.
Clone the repository:

----
git clone git@github.com:infinispan/infinispan-simple-tutorials.git
----
