[id='server_endpoint_auth-{context}']
= {brandname} Server Authentication
{brandname} servers automatically configure authentication mechanisms based on
the security realm that you assign to endpoints.

.SASL Authentication Mechanisms

The following SASL authentication mechanisms apply to Hot Rod endpoints:

|===
|Security Realm |SASL Authentication Mechanism

|Property Realms and LDAP Realms
|SCRAM-+*+, DIGEST-+*+, CRAM-MD5

|Token Realms
|OAUTHBEARER

|Trust Realms
|EXTERNAL

|Kerberos Identities
|GSSAPI, GS2-KRB5

|SSL/TLS Identities
|PLAIN
|===


.HTTP Authentication Mechanisms

The following HTTP authentication mechanisms apply to REST endpoints:

|===
|Security Realm |HTTP Authentication Mechanism

|Property Realms and LDAP Realms
|DIGEST

|Token Realms
|BEARER_TOKEN

|Trust Realms
|CLIENT_CERT

|Kerberos Identities
|SPNEGO

|SSL/TLS Identities
|BASIC
|===

.Default Configuration

{brandname} servers provide a security realm named "default" that uses a
property realm with plain text credentials defined in `{server_home}/server/
conf/users.properties`, as shown in the following snippet:

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/server_authentication.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/server_authentication.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/server_authentication.yaml[]
----

The `endpoints` configuration assigns the "default" security realm to the Hot
Rod and REST connectors, as follows:

.XML
[source,xml,options="nowrap",subs=attributes+,role="primary"]
----
include::xml/server_authentication_endpoints.xml[]
----

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::json/server_authentication_endpoints.json[]
----

.YAML
[source,yaml,options="nowrap",subs=attributes+,role="secondary"]
----
include::yaml/server_authentication_endpoints.yaml[]
----

As a result of the preceding configuration, {brandname} servers require
authentication with a mechanism that the property realm supports.
