[id='rest_v2_cache_manager_site_status_{context}']
= Getting status of backup locations

Retrieve the status of all backup locations with `GET`
requests.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/container/x-site/backups/
----

{brandname} responds with status in JSON format, as in the following example:

[source,json,options="nowrap",subs=attributes+]
----
include::json/xsite_backup_status.json[]
----

.Returned Status
|===
|Value |Description

|`online`
| All caches in the local cluster have the backup location with `online` status.

|`offline`
| All caches in the local cluster have the backup location with `offline` status.

|`mixed`
| Some caches in the local cluster have the backup location with `online` status while others have the backup location with `offline` status.
The response indicates status for each cache.
|===

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/container/x-site/backups/{site}
----

Returns the status for a single backup location.

[id='rest_v2_cache_manager_take_offline_{context}']
= Taking backup locations offline

Take backup locations offline with the `?action=take-offline` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/container/x-site/backups/{siteName}?action=take-offline
----

[id='rest_v2_cache_manager_bring_online_{context}']
= Bringing backup locations online

Bring backup locations online with the `?action=bring-online` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/container/x-site/backups/{siteName}?action=bring-online
----

[id='rest_v2_cache_manager_start_push_{context}']
= Starting state transfer

Push state of all caches to remote sites with the `?action=start-push-state` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/container/x-site/backups/{siteName}?action=start-push-state
----

[id='rest_v2_cache_manager_cancel_push_{context}']
= Canceling state transfer

Cancel ongoing state transfer operations with the `?action=cancel-push-state` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/container/x-site/backups/{siteName}?action=cancel-push-state
----
