= Unsupported Features

This section details features of the Memcached text protocol that are currently not supported by the {brandname} based Memcached implementation.

== Individual Statistics

There are differences between the original Memcached implementation, which is C/C++ based, and the {brandname} implementation, which is Java based. There are some general purpose statistics that are not supported. For these unsupported statistics, {brandname} Memcached server always returns `0`.

.Unsupported statistics

*  pointer_size
*  rusage_user
*  rusage_system
*  bytes
*  curr_connections
*  total_connections
*  connection_structures
*  auth_cmds
*  auth_errors
*  limit_maxbytes
*  threads
*  conn_yields
*  reclaimed

.Statistic settings

Statistics setting is not supported. 

.Settings with Arguments Parameter

{brandname} Memcached server does not support passing any arguments to the `stats` command. If any parameters are passed, the {brandname} Memcached server responds with  `CLIENT_ERROR` .

.Delete Hold Time Parameter

As Memcached no longer honors the optional hold time parameter for the delete command, the {brandname} based Memcached server does not implement the feature.

.Verbosity Command

The verbosity command is not supported because {brandname} logging cannot be simplified to defining the logging level alone.

.Meta protocol

The Memcached meta protocol, introduced in Memcached 1.6, is not supported.
