= Unsupported Features

This section details features of the Memcached text protocol that are currently not supported by the {brandname} based Memcached implementation.

== Individual Stats

There are differences in the nature of the original memcached implementation, which is C/C\+\+ based, and the {brandname} implementation which is Java based. There are some general purpose statistics that are not supported. For these unsupported stats, {brandname} Memcached server always returns 0.

.Unsupported statistics

*  pointer_size
*  rusage_user
*  rusage_system
*  bytes
*  curr_connections
*  total_connections
*  connection_structures
*  auth_cmds
*  auth_errors
*  limit_maxbytes
*  threads
*  conn_yields
*  reclaimed

== Statistic Settings

The statistics setting section of the text protocol has not been implemented due to its volatility.

== Settings with Arguments Parameter

Since the arguments that can be sent to the Memcached server are not documented, {brandname} Memcached server does not support passing any arguments to the stats command. If any parameters are passed, the {brandname} Memcached server will respond with a `CLIENT_ERROR` .

== Delete Hold Time Parameter

Memcached no longer honors the optional hold time parameter for the delete command. The {brandname} based Memcached server does not implement the feature.

== Verbosity Command

The verbosity command is not supported since {brandname} logging cannot be simplified to defining the logging level alone.

== Meta protocol

The Memcached meta protocol was introduced in 1.6. {brandname}'s connector doesn't support it yet.
