[id='rest_v2_sync_data']

= Connecting Source Clusters

Connect a target cluster to the source cluster with:

[source,options="nowrap",subs=attributes+]
----
POST /v2/caches/{cacheName}?action=connect-source
----

You must provide a `remote-store` definition in JSON format as the body:

.JSON
[source,json,options="nowrap",subs=attributes+,role="secondary"]
----
include::config_examples/remote-store.json[]
----

Several elements are optional such as `security`, `async-executor` and `connection-pool`.
The configuration must contain minimally the cache name, the `raw-values` set to `false` and the
host/ip of the single port in the source cluster. For details about the `remote-store` configuration,
consult the link:https://infinispan.org/schemas/infinispan-cachestore-remote-config-12.0.xsd[XSD Schema].

If the operation successfully completes, the service returns 204 (No Content).

= Synchronizing Data
Synchronize data from a source cluster to a target cluster with `POST` requests
and the `?action=sync-data` parameter:

[source,options="nowrap",subs=attributes+]
----
POST /v2/caches/{cacheName}?action=sync-data
----

When the operation completes, {brandname} responds with the total number of
entries copied to the target cluster.

[id='rest_v2_disconnect_source']
= Disconnecting Source Clusters
After you synchronize data to target clusters, disconnect from the source
cluster with `POST` requests and the `?action=disconnect-source` parameter:

[source,options="nowrap",subs=attributes+]
----
POST /v2/caches/{cacheName}?action=disconnect-source
----

If the operation successfully completes, the service returns `204 (No Content)`.
