[id='full-text-search_{context}']
= Full-text queries

You can perform full-text searches with the Ickle query language.

Full-text predicates have one of the following forms, and any form may be followed by a `^` and an integer boost factor:

[source,sql,title="Full-Text Predicate in Ickle"]
----
<analyzed field> : '<term or phrase>' [~distance]
<analyzed field> : [<lower bound> to <upper bound>]
<analyzed field> : /regular expression/
----

The following railroad diagram illustrates the syntax of a full-text predicate:

[syntrax, fulltext-predicate-syntax, format=svg]
....
line(
  '/analyzed field', ':',
choice(line('\'', '/term', '\'', opt(line('~', '/distance'))),
line('[', '/bound', opt('to', '/bound'), ']'),
line('//','/regular expression', '//'))
)
....

== Fuzzy queries

To execute a fuzzy query add `~` along with an integer, representing the distance from the term used, after the term.
For instance

[source,sql,title="Fuzzy Queries in Ickle"]
----
FROM sample_bank_account.Transaction WHERE description : 'cofee'~2
----

== Range queries

To execute a range query define the given boundaries within a pair of square brackets or curly braces, as seen in the following example:

[source,sql,title="Range queries with Ickle"]
----
FROM sample_bank_account.Transaction WHERE amount : [20 to 50]
----

== Phrase queries

A group of words can be searched by surrounding them in quotation marks, as seen in the following example:

[source,sql,title="Phrase queries with Ickle"]
----
FROM sample_bank_account.Transaction WHERE description : 'bus fare'
----

== Proximity queries

To execute a proximity query, finding two terms within a specific distance, add a `~` along with the distance after the phrase.
For instance, the following example will find the words canceling and fee provided they are not more than 3 words apart:

[source,sql,title="Proximity queries with Ickle"]
----
FROM sample_bank_account.Transaction WHERE description : 'canceling fee'~3
----

== Wildcard queries

To search for "text" or "test", use the `?` single-character wildcard search:

[source,sql,title="Single-character wildcard queries with Ickle"]
----
FROM sample_bank_account.Transaction where description : 'te?t'
----

To search for "test", "tests", or "tester", use the `*` multi-character wildcard search:

[source,sql,title="Multi-character wildcard queries with Ickle"]
----
FROM sample_bank_account.Transaction where description : 'test*'
----

== Regular expression queries

Regular expression queries can be performed by specifying a pattern between `/`. Ickle uses Lucene’s regular expression syntax, so to search for the words `moat` or `boat` the following could be used:

[source,sql,title="Regular Expression queries with Ickle"]
----
FROM sample_library.Book  where title : /[mb]oat/
----

== Boosting queries

Terms can be boosted by adding a `^` after the term to increase their relevance in a given query, the higher the boost factor the more relevant the term will be. For instance to search for titles containing beer and wine with a higher relevance on beer, by a factor of 3, the following could be used:

[source,sql,title="Boosting queries with Ickle"]
----
FROM sample_library.Book WHERE title : beer^3 OR wine
----
