= CLI Resources
The {brandname} CLI exposes different resources to:

* create, modify, and manage local or clustered caches.
* perform administrative operations for {brandname} clusters.

.Cache Resources
----
[//containers/default]> ls
caches
counters
configurations
schemas
tasks
----

`caches`::
{brandname} cache instances. The default cache container is empty. Use the CLI to create caches from templates or `infinispan.xml` files.
`counters`::
`Strong` or `Weak` counters that record the count of objects.
`configurations`::
{brandname} configurations.
`schemas`::
Protocol Buffers (Protobuf) schemas that structure data in the cache.
`tasks`::
Remote tasks creating and managing {brandname} cache definitions.

.Cluster Resources
----
[hostname@cluster/]> ls
containers
cluster
server
----

`containers`::
Cache containers on the {brandname} cluster.
`cluster`::
Lists {brandname} Servers joined to the cluster.
//dnaro: need to ask. think server is wip.
`server`::
Resources for managing and monitoring {brandname} Servers.
