[id='rest_v2_cache_manager_site_status']
= Getting Status of Backup Locations
Retrieve the status of all backup locations from Cache Managers with `GET`
requests.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/
----

{brandname} responds with status in JSON format, as in the following example:

[source,json,options="nowrap",subs=attributes+]
----
include::json_examples/xsite_backup_status.json[]
----

.Returned Status

|===
|Value |Description

|`online`
| All nodes in the local cluster have a cross-site view with the backup location.

|`offline`
| No nodes in the local cluster have a cross-site view with the backup location.

|`mixed`
| Some nodes in the local cluster have a cross-site view with the backup location, other nodes in the local cluster do not have a cross-site view. The response indicates status for each node.
|===

[id='rest_v2_cache_manager_take_offline']
= Taking Backup Locations Offline
Take backup locations offline with the `?action=take-offline` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/{siteName}?action=take-offline
----

[id='rest_v2_cache_manager_bring_online']
= Bringing Backup Locations Online
Bring backup locations online with the `?action=bring-online` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/{siteName}?action=bring-online
----

[id='rest_v2_cache_manager_get_state_transfer_mode']
= Retrieving the State Transfer Mode
Check the state transfer mode with `GET` requests.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/caches/{cacheName}/x-site/backups/{site}/state-transfer-mode
----

[id='rest_v2_cache_manager_set_state_transfer_mode']
= Setting the State Transfer Mode
Configure the state transfer mode with the `?action=set` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/caches/{cacheName}/x-site/backups/{site}/state-transfer-mode?action=set&mode={mode}
----

[id='rest_v2_cache_manager_start_push']
= Starting State Transfer
Push state of all caches to remote sites with the `?action=start-push-state` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/{siteName}?action=start-push-state
----


[id='rest_v2_cache_manager_cancel_push']
= Canceling State Transfer
Cancel ongoing state transfer operations with the `?action=cancel-push-state` parameter.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/{siteName}?action=cancel-push-state
----
