[id='authz_role_mappers-{context}']
= Role Mappers
{brandname} includes a `PrincipalRoleMapper` API that maps security Principals
in a Subject to authorization roles. There are three role mappers available by
default:

IdentityRoleMapper:: Uses the Principal name as the role name.
+
* Java class: `org.infinispan.security.mappers.IdentityRoleMapper`
* Declarative configuration: `<identity-role-mapper />`

CommonNameRoleMapper:: Uses the Common Name (CN) as the role name if the
Principal name is a Distinguished Name (DN). For example the
`cn=managers,ou=people,dc=example,dc=com` DN maps to the `managers` role.
+
* Java class: `org.infinispan.security.mappers.CommonRoleMapper`
* Declarative configuration: `<common-name-role-mapper />`

ClusterRoleMapper:: A dynamic mapper which uses a persistent replicated cache to store principal-to-role mappings.
By default, if mappings have not been provided, this mapper behaves like the *IdentityRoleMapper*.
It also implements the `org.infinispan.security.MutableRoleMapper` which exposes methods to manipulate the mappings at runtime.
The CLI `user roles grant` and `user roles deny` commands can be used to change the role mappings.
+
* Java class: `org.infinispan.security.mappers.ClusterRoleMapper`
* Declarative configuration: `<cluster-role-mapper />`

You can also use custom role mappers that implement the
`org.infinispan.security.PrincipalRoleMapper` interface. To configure custom
role mappers declaratively, use: `<custom-role-mapper class="my.custom.RoleMapper" />`

.Reference

* link:{javadocroot}/org/infinispan/security/package-summary.html[{brandname} Security API]
* link:{javadocroot}/org/infinispan/security/PrincipalRoleMapper.html[org.infinispan.security.PrincipalRoleMapper]
