[[rest_v2_api]]
= REST v2 API

{brandname} provides a REST v2 (version 2) API that improves upon the REST v1 API. The REST v2 API gives you all the features of the v1 API in addition to support for resources beyond caching.

[[rest_v2_cache_operations]]
== Working with Caches

Use the REST API to create and manage caches on your {brandname} cluster and interact with cached entries.

[[rest_v2_create_cache]]
=== Creating Caches

To create a named cache across the {brandname} cluster, invoke a `POST` request.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/caches/{cacheName}
----

To configure the cache, you supply the configuration in XML or JSON format as part of the payload.

XML Configuration::
If you supply the {brandname} configuration in XML format, it must conform to the schema and include the `<infinispan>` root element and a
`<cache-container>` definition, as in the following example:
+
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/infinispan_distributed_cache.xml[]
----

JSON Configuration::
If you supply the {brandname} configuration in a JSON payload, it requires only the cache definition.
However, the JSON payload must follow the structure of an XML configuration.
XML elements become JSON objects.
XML attributes become JSON fields.
+
For example, the preceding XML configuration is represented in JSON as follows:
+
[source,json,options="nowrap",subs=attributes+]
----
{
  "distributed-cache": {
    "mode": "SYNC",
    "memory": {
      "object": {
        "size": 20
      }
    }
  }
}
----

.Headers
|===
|Header |Required or Optional |Parameter

|`Content-Type`
|REQUIRED
|Sets the https://en.wikipedia.org/wiki/Media_type[MediaType] for the
{brandname} configuration payload; either `application/xml` or
`application/json`.
|===

[[rest_v2_create_cache_template]]
==== Creating with Templates

To create a cache across the {brandname} cluster based on a pre-defined template, invoke a `POST` request with no payload and an extra request parameter:

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/caches/{cacheName}?template={templateName}
----

[[rest_v2_cache_configuration]]
=== Retrieving Cache Configuration

To retrieve a {brandname} cache configuration, invoke a `GET` request.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/configurations/{name}
----

.Headers
|===
|Header |Required or Optional |Parameter

|`Accept`
|OPTIONAL
|Sets the required format to return content. Supported formats are `application/xml` and `application/json`. The default is `application/json`. See link:#rest_accept[Accept] for more information.
|===

[[rest_v2_add_entries]]
=== Adding Entries

To add entries to a named cache, invoke a `POST` request.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/caches/{cacheName}/{cacheKey}
----

The preceding request places the payload, or request body, in the `cacheName`
cache with the `cacheKey` key.
The request replaces any data that already exists and updates the `Time-To-Live` and `Last-Modified` values, if they apply.

If the specified key has an existing value, the request returns an HTTP
`CONFLICT` status and the value is not updated.
In this case, you should use a `PUT` request.
See link:#rest_v2_replace_entries[Replacing Entries].

.Headers
|===
|Header |Required or Optional |Parameter

|`Key-Content-Type`
|OPTIONAL
|Sets the content type for the key in the request. See link:#rest_key_content_type[Key-Content-Type] for more information.

|`Content-Type`
|OPTIONAL
|Sets the https://en.wikipedia.org/wiki/Media_type[MediaType] of the value for the key.

|`timeToLiveSeconds`
|OPTIONAL
|Sets the number of seconds before the entry is automatically deleted. If you do not set this parameter, {brandname} uses the default value from the configuration. If you set a negative value, the entry is never deleted.

|`maxIdleTimeSeconds`
|OPTIONAL
|Sets the number of seconds that entries can be idle. If a read or write operation does not occur for an entry after the maximum idle time elapses, the entry is automatically deleted. If you do not set this parameter, {brandname} uses the default value from the configuration. If you set a negative value, the entry is never deleted.
|===

[NOTE]
====
If both `timeToLiveSeconds` and `maxIdleTimeSeconds` have a value of `0`, {brandname} uses the default `lifespan` and `maxIdle` values from the configuration.

If _only_ `maxIdleTimeSeconds` has a value of `0`, {brandname} uses:

* the default `maxIdle` value from the configuration.
* the value for `timeToLiveSeconds` that you pass as a request parameter or a value of `-1` if you do not pass a value.

If _only_ `timeToLiveSeconds` has a value of `0`, {brandname} uses:

* the default `lifespan` value from the configuration.
* the value for `maxIdle` that you pass as a request parameter or a value of `-1` if you do not pass a value.
====

[[rest_v2_replace_entries]]
=== Replacing Entries

To replace entries in a named cache, invoke a `PUT` request.

[source,options="nowrap",subs=attributes+]
----
PUT /rest/v2/caches/{cacheName}/{cacheKey}
----

The preceding request is the same as a `POST` request to add entries to the cache.
However, if the entry already exists, the `PUT` request replaces it instead of returning an HTTP `CONFLICT` status.

[[rest_v2_retrieve_cache]]
=== Retrieving Caches By Keys

To retrieve data for a specific key in a cache, invoke a `GET` request.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/caches/{cacheName}/{cacheKey}
----

The preceding request returns data from the given cache, `cacheName`, under the given key, `cacheKey`, as the response body.
Responses contain a `Content-Type` headers that correspond to the MediaType negotiation.

[NOTE]
====
Browsers can also access caches directly, for example as a content delivery network (CDN). {brandname} returns a unique link:http://en.wikipedia.org/wiki/HTTP_ETag[ETag] for each entry along with the `Last-Modified` and `Expires` header fields.
These fields provide information about the state of the data that is returned in your request.
ETags allow browsers and other clients to request only data that has changed, which conserves bandwidth.
====

.Headers
|===
|Header |Required or Optional |Parameter

|`Key-Content-Type`
|OPTIONAL
|Sets the content type for the key in the request. The default is `application/x-java-object; type=java.lang.String`. See link:#rest_key_content_type[Key-Content-Type] for more information.

|`Accept`
|OPTIONAL
|Sets the required format to return content. See link:#rest_accept[Accept] for more information.
|===

[TIP]
====
Append the `extended` parameter to the query string to get additional information.

[source,options="nowrap",subs=attributes+]
----
GET /cacheName/cacheKey?extended
----

The preceding request returns custom headers:

* `Cluster-Primary-Owner` returns the node name that is the primary owner of the key.
* `Cluster-Node-Name` returns the JGroups node name of the server that handled the request.
* `Cluster-Physical-Address` returns the physical JGroups address of the server that handled the request.
====

[[rest_v2_check_entries]]
=== Checking if Entries Exist

To check if a specific entry exists in a cache, invoke a `HEAD` request.

[source,options="nowrap",subs=attributes+]
----
HEAD /rest/v2/caches/{cacheName}/{cacheKey}
----

The preceding request returns only the header fields and the same content that you stored with the entry.
For example, if you stored a String, the request returns a String.
If you stored binary, base64-encoded, blobs or serialized Java objects, {brandname} does not de-serialize the content in the request.

As with `GET` requests, `HEAD` requests also support the `extended` parameter.

.Headers
|===
|Header |Required or Optional |Parameter

|`Key-Content-Type`
|OPTIONAL
|Sets the content type for the key in the request. The default is `application/x-java-object; type=java.lang.String`. See link:#rest_key_content_type[Key-Content-Type] for more information.
|===

[[rest_v2_delete_entries]]
=== Deleting Entries

To delete entries from a cache, invoke a `DELETE` request.

[source,options="nowrap",subs=attributes+]
----
DELETE /rest/v2/caches/{cacheName}/{cacheKey}
----

The preceding request removes the entry under `cacheKey` name from the cache.

.Headers
|===
|Header |Required or Optional |Parameter

|`Key-Content-Type`
|OPTIONAL
|Sets the content type for the key in the request. The default is `application/x-java-object; type=java.lang.String`. See link:#rest_key_content_type[Key-Content-Type] for more information.
|===

[[rest_v2_remove_cache]]
=== Removing Caches

To remove caches, invoke a `DELETE` request.

[source,options="nowrap",subs=attributes+]
----
DELETE /rest/v2/caches/{cacheName}
----

The preceding request deletes all data and removes the cache named `cacheName` from the cluster.

[[rest_v2_clear_cache]]
=== Clearing Caches

To delete all data from a cache, invoke a `GET` request with the `?action=clear` parameter.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/caches/{cacheName}?action=clear
----

[[rest_v2_cache_size]]
=== Getting the size of Caches

To obtain the size of the cache across the entire cluster, invoke a `GET` request with the `?action=size` parameter.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/caches/{cacheName}?action=size
----

[[rest_v2_query_cache]]
=== Querying Caches

Invoke a `GET` request to perform and Ickle query on a given cache, as follows:

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/caches/{cacheName}?action=search&query={ickle query}
----

The preceding request returns a `JSON` document that contains one or more query hits, for example:

[source,json]
----
{
  "total_results" : 150,
  "hits" : [ {
    "hit" : {
      "name" : "user1",
      "age" : 35
    }
  }, {
    "hit" : {
       "name" : "user2",
       "age" : 42
    }
  }, {
    "hit" : {
       "name" : "user3",
       "age" : 12
    }
  } ]
}
----

* `total_results` displays the total number of results from the query.
* `hits` is an array of matches from the query.
* `hit` is an object that matches the query.
Each hit can contain all fields or a subset of fields if you use a `Select` clause.

.Request Parameters
|===
|Parameter |Required or Optional |Value

|`query`
|REQUIRED
|Specifies the query string.

|`max_results`
|OPTIONAL
|Sets the number of results to return. The default is `10`.

|`offset`
|OPTIONAL
|Specifies the index of the first result to return. The default is `0`.

|`query_mode`
|OPTIONAL
|Specifies how the {brandname} server executes the query. Values are `FETCH` and `BROADCAST`. The default is `FETCH`.
|===

To use the body of the request instead of specifying query parameters, invoke a `POST` request.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/caches/{cacheName}?action=search
----

The following is an example of a query in the request body:

[source,json]
----
{
 "query":"from Entity where name:\"user1\"",
 "max_results":20,
 "offset":10
}
----

[[rest_v2_cache_manager_operations]]
== Cache Manager

Use the REST API to interact with the Cache Manager on your {brandname} and obtain cluster and usage statistics.

[[rest_v2_cache_manager_info]]
=== Basic Information

To obtain information about a cache manager, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}
----

The response will be a JSON document with the following information:

[source,json]
----
{
    "version":"10.0.0-SNAPSHOT",
    "name":"default",
    "coordinator":true,
    "cache_configuration_names":[
        "___protobuf_metadata",
        "cache2",
        "CacheManagerResourceTest",
        "cache1"
    ],
    "cluster_name":"ISPN",
    "physical_addresses":"[127.0.0.1:35770]",
    "coordinator_address":"CacheManagerResourceTest-NodeA-49696",
    "cache_manager_status":"RUNNING",
    "created_cache_count":"3",
    "running_cache_count":"3",
    "node_address":"CacheManagerResourceTest-NodeA-49696",
    "cluster_members":[
        "CacheManagerResourceTest-NodeA-49696",
        "CacheManagerResourceTest-NodeB-28120"
    ],
    "cluster_members_physical_addresses":[
        "127.0.0.1:35770",
        "127.0.0.1:60031"
    ],
    "cluster_size":2,
    "defined_caches":[
        {
            "name":"CacheManagerResourceTest",
            "started":true
        },
        {
            "name":"cache1",
            "started":true
        },
        {
            "name":"___protobuf_metadata",
            "started":true
        },
        {
            "name":"cache2",
            "started":true
        }
    ]

}
----

* `version` contains the {brandname} version
* `name` contains the name of the cache manager as defined in the configuration
* `coordinator` is true if the cache manager is the coordinator of the cluster
* `cache_configuration_names` contains an array of all caches configurations defined in the cache manager
* `cluster_name` contains the name of the cluster as defined in the configuration
* `physical_addresses` contains the physical network addresses associated with the cache manager
* `coordinator_address` contains the physical network addresses of the coordinator of the cluster
* `cache_manager_status` the lifecycle status of the cache manager.
For possible values, check the https://docs.jboss.org/infinispan/9.4/apidocs/org/infinispan/lifecycle/ComponentStatus.html[`org.infinispan.lifecycle.ComponentStatus`] documentation
* `created_cache_count` number of created caches, excludes all internal and private caches
* `running_cache_count` number of created caches that are running
* `node_address` contains the logical address of the cache manager
* `cluster_members` and `cluster_members_physical_addresses` an array of logical and physical addresses of the members of the cluster
* `cluster_size` number of members in the cluster
* `defined_caches` A list of all caches defined in the cache manager, excluding private caches but including internal caches that are accessible

[[rest_v2_cache_manager_health]]
=== Health

To retrieve information about the {brandname} cluster health, invoke a `GET` request.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/health
----

The response will be a JSON document with the following information:

[source,json]
----
{
    "cluster_health":{
        "cluster_name":"ISPN",
        "health_status":"HEALTHY",
        "number_of_nodes":2,
        "node_names":[
            "CacheManagerResourceTest-NodeA-36229",
            "CacheManagerResourceTest-NodeB-28703"
        ]
    },
    "cache_health":[
        {
            "status":"HEALTHY",
            "cache_name":"___protobuf_metadata"
        },
        {
            "status":"HEALTHY",
            "cache_name":"cache2"
        },
        {
            "status":"HEALTHY",
            "cache_name":"CacheManagerResourceTest"
        },
        {
            "status":"HEALTHY",
            "cache_name":"cache1"
        }
    ]

}
----

* `cluster_health` contains the health of the cluster
** `cluster_name` specifies the name of the cluster as defined in the configuration.
** `health_status` provides one of the following:
*** `UNHEALTHY` indicates at least one of the caches is in degraded mode.
*** `REBALANCING` indicates at least one cache is in the rebalancing state.
*** `HEALTHY` indicates all cache instances in the cluster are operating as expected.
** `number_of_nodes` displays the total number of cluster members.
Returns a value of `0` for non-clustered (standalone) servers.
** `node_names` is an array of all cluster members.
Empty for standalone servers.
* `cache_health` contains health information per-cache
** `status`  HEALTHY,UNHEALTHY or REBALANCING
** `cache_name` the name of the cache as defined in the configuration.

[[rest_v2_cache_manager_availability]]
=== Check Availability

To check that a {brandname} exists and is available, invoke a `HEAD` request in the health resource

[source,options="nowrap",subs=attributes+]
----
HEAD /rest/v2/cache-managers/{cacheManagerName}/health
----

If the preceding request returns a successful response code then the {brandname} REST server is running and serving requests.

[[rest_v2_cache_manager_config]]
=== Obtaining Configuration

To obtain the https://docs.jboss.org/infinispan/9.4/apidocs/org/infinispan/configuration/global/GlobalConfiguration.html[GlobalConfiguration] associated with the Cache Manager, invoke a `GET` request.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/config
----

.Headers
|===
|Header |Required or Optional |Parameter

|`link:#rest_accept[Accept]`
|OPTIONAL
|The required format to return the content. Supported formats are _application/json_ and _application/xml_. JSON is assumed if no header is provided.
|===

[[rest_v2_cache_manager_caches_config]]
=== Obtaining Caches Configuration

To obtain the configuration of all caches:

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/cache-configs
----

The response will contain a JSON array with each cache and its configuration.
Example:

[source,json]
----
[
  {
      "name":"cache1",
      "configuration":{
          "distributed-cache":{
              "mode":"SYNC",
              "partition-handling":{
                  "when-split":"DENY_READ_WRITES"
              },
              "statistics":true
          }
      }
  },
  {
      "name":"cache2",
      "configuration":{
          "distributed-cache":{
              "mode":"SYNC",
              "transaction":{
                  "mode":"NONE"
              }
          }
      }
  }
]
----

[[rest_v2_cache_manager_stats]]
=== Getting statistics

To obtain the statistics of the Cache Manager, invoke a `GET` request.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/stats
----

The response will be a JSON document with the following information:

[source,json]
----
{
    "statistics_enabled":true,
    "read_write_ratio":0.0,
    "time_since_start":1,
    "time_since_reset":1,
    "number_of_entries":0,
    "total_number_of_entries":0,
    "off_heap_memory_used":0,
    "data_memory_used":0,
    "misses":0,
    "remove_hits":0,
    "remove_misses":0,
    "evictions":0,
    "average_read_time":0,
    "average_read_time_nanos":0,
    "average_write_time":0,
    "average_write_time_nanos":0,
    "average_remove_time":0,
    "average_remove_time_nanos":0,
    "required_minimum_number_of_nodes":1,
    "hits":0,
    "stores":0,
    "current_number_of_entries_in_memory":0,
    "hit_ratio":0.0,
    "retrievals":0
}
----

* `statistics_enabled` will show `true` if the statistics collection was enabled in the Cache Manager
* `read_write_ratio` the read/write ratio across all caches
* `time_since_start` time in seconds since the Cache Manager start
* `time_since_reset` number of seconds since the Cache Manager statistics were last reset
* `number_of_entries` total number of entries currently in all caches from the Cache Manager.
It only returns the entries in the local cache instances
* `total_number_of_entries` the number of store operations performed across all caches from the Cache Manager
* `off_heap_memory_used` amount in bytes of off-heap memory used by this cache container
* `data_memory_used` amount in bytes the current eviction algorithm estimates is in use for data across all caches.
Returns 0 if memory eviction is not enabled
* `misses` number of `get() misses across all caches
* `remove_hits` number of removal hits across all caches
* `remove_misses` number of removal misses across all caches
* `evictions` number of evictions across all caches
* `average_read_time` average number of milliseconds taken for `get()` operations across all caches
* `average_read_time_nanos` same as above, but in nanoseconds
* `average_remove_time` average number of milliseconds for `remove()` operations across all caches
* `average_remove_time_nanos` same as above but in nanoseconds
* `required_minimum_number_of_nodes` the required minimum number of nodes to guarantee data consistency
* `hits` number of `get()` hits across all caches
* `stores` number of `put()` operations across all caches
* `current_number_of_entries_in_memory` total number of entries currently in all caches, excluding passivated entries
* `hit_ratio` total percentage hit/(hit+miss) ratio for all caches
* `retrievals` total number of `get()` operations

[[rest_server_counters]]
== Counter

Use the REST API to work with counters.

[[rest_server_counters_create]]
=== Creating a Counter

To create a counter, use a `POST` request with the configuration as payload.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/counters/{counterName}
----

The payload must contain a JSON configuration of the counter.
Example:

[source,json]
----
{
    "weak-counter":{
        "initial-value":5,
        "storage":"PERSISTENT",
        "concurrency-level":1
    }
}
----

[source,json]
----
{
    "strong-counter":{
        "initial-value":3,
        "storage":"PERSISTENT",
        "upper-bound":{
            "value":5
        }
    }
}
----

[[rest_server_counters_delete]]
=== Deleting a Counter

To delete a counter, send a `DELETE` request with the counter name.

[source,options="nowrap",subs=attributes+]
----
DELETE /rest/v2/counters/{counterName}
----

[[rest_server_counters_config]]
=== Retrieving Counters Configuration

The get the counter configuration, use a `GET` request with the counter name.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/counters/{counterName}/config
----

The result will be a JSON representation of the counter config.

[[rest_server_counters_add]]
=== Adding Values to Counters

To add a value to a named counter, invoke a `POST` request.

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/counters/{counterName}
----

If the request payload is empty, the counter is incremented by one, otherwise the payload is interpreted as a signed long and added to the counter.

Request responses depend on the type of counter, as follows:

* `WEAK` counters return empty responses.
* `STRONG` counters return their values after the operation is applied.

[NOTE]
====
This method processes only `plain/text` content.
====

[[rest_server_counters_get]]
=== Getting a Counter Value

To retrieve the value of a counter, invoke a `GET` request.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/counters/{counterName}
----

.Headers
|===
|Header |Required or Optional |Parameter

|`link:#rest_accept[Accept]`
|OPTIONAL
|The required format to return the content. Supported formats are _application/json_ and _text/plain_. JSON is assumed if no header is provided.
|===

[[rest_server_counters_reset]]
=== Reseting Counters

To reset counters, use a `GET` request with the `?action=reset` parameter.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/counters/{counterName}?action=reset
----

[[rest_server_counters_inc_weak]]
=== Incrementing Counters

To increment a Counter, use the `?action=increment` parameter.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/counters/{counterName}?action=increment
----

Request responses depend on the type of counter, as follows:

* `WEAK` counters return empty responses.
* `STRONG` counters return their values after the operation is applied.

[[rest_server_counters_add_weak]]
=== Adding a delta to Counters

To add an arbitrary amount to a Counter, use the params `?action=add` and `delta`.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/counters/{counterName}?action=add&delta={delta}
----

Request responses depend on the type of counter, as follows:

* `WEAK` counters return empty responses.
* `STRONG` counters return their values after the operation is applied.

[[rest_server_counters_dec_strong]]
=== Decrementing Counters

To increment a Counter, use the `?action=decrement` parameter.

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/counters/{counterName}?action=decrement
----

Request responses depend on the type of counter, as follows:

* `WEAK` counters return empty responses.
* `STRONG` counters return their values after the operation is applied.

[[rest_server_counters_cmpset]]
=== compareAndSet Strong Counters

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/counters/{counterName}?action=compareAndSet&expect={expect}&update={update}
----

Atomically sets the value to {update} if the current value is {expect}

Returns _true_ if successful.

[[rest_server_counters_cmpswp]]
=== compareAndSwap Strong Counter

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/counters/{counterName}?action=compareAndSwap&expect={expect}&update={update}
----

Atomically sets the value to {update} if the current value is {expect}.
Returns the previous value in the payload if the operation is successful.

[[rest_v2_server]]
== Server

Use the REST API to interact with the {brandname} server including runtime information and operations.

[[rest_v2_server_info]]
=== Basic Information

To obtain basic info about a server, invoke a `GET`:

[source,options="nowrap",subs=attributes+]
----
GET /v2/server
----

The response will contain the server name, codename and version:

[source,json]
----
{
  "version":"Infinispan 'Codename' 10.0.0.Final"
}
----

[[rest_v2_server_config]]
=== Obtaining Configuration

[source,options="nowrap",subs=attributes+]
----
GET /v2/server/config
----

The response will be a JSON document whose structure follows the link:https://github.com/infinispan/infinispan/blob/master/server/runtime/src/main/resources/schema/infinispan-server-10.0.xsd[Server Schema].

[source,json]
----
{
    "server":{
        "interfaces":{
            "interface":{
                "name":"public",
                "inet-address":{
                    "value":"127.0.0.1"
                }
            }
        },
        "socket-bindings":{
            "port-offset":0,
            "default-interface":"public",
            "socket-binding":[
                {
                    "name":"memcached",
                    "port":11221,
                    "interface":"memcached"
                }
            ]
        },
        "security":{
            "security-realms":{
                "security-realm":{
                    "name":"default"
                }
            }
        },
        "endpoints":{
            "socket-binding":"default",
            "security-realm":"default",
            "hotrod-connector":{
                "name":"hotrod"
            },
            "rest-connector":{
                "name":"rest"
            }
        }
    }
}
----

[[rest_v2_server_memory]]
=== Memory Info

The server resource exposes basic information about the Java Virtual Machine memory usage:

[source,options="nowrap",subs=attributes+]
----
GET /v2/server/memory
----

The output will be a JSON document exposing heap and non-heap memory statistics, direct memory usage, details about memory pools and garbage collection.

[[rest_v2_server_env]]
=== Environment

The obtain the environment variables used by the server, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/server/env
----

[[rest_v2_server_threads]]
=== Obtaining a thread dump

[source,options="nowrap",subs=attributes+]
----
GET /v2/server/threads
----

The output will be a `text/plain` document with the JVM's current thread dump

[rest_v2_server_stop]]
=== Stopping the server

To shutdown the server, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/server/stop
----

A response with code `200(OK)` will be returned, and after a small delay, the server will be stopped.

//-
