= REST V1 API

The REST V1 API supports basic cache capabilities including operations on keys and query, and is now deprecated. For a more powerful and comprehensive API, check the link:#rest_v2_api[REST V2 API].

HTTP PUT and POST methods are used to place data in the cache, with URLs to address the cache name and key(s) - the data being the body of the request (the data can be anything you like). Other headers are used to control the cache settings and behaviour.

== Putting data in

[[rest_server_put_request]]
=== `PUT /rest/{cacheName}/{cacheKey}`
A PUT request of the above URL form will place the payload (body) in the given cache, with the given key (the named cache must exist on the server). For example `http://someserver/hr/payRoll-3` (in which case `hr` is the cache name, and `payRoll-3` is the key). Any existing data will be replaced, and Time-To-Live and Last-Modified values etc will updated (if applicable).

[[rest_server_post_request]]
=== `POST /rest/{cacheName}/{cacheKey}`
Exactly the same as PUT, only if a value in a cache/key already exists, it will return a Http CONFLICT status (and the content will not be updated).

.Headers

*  link:#rest_key_content_type[Key-Content-Type]: OPTIONAL The content type for the Key present in the URL.

*  Content-Type : OPTIONAL The https://en.wikipedia.org/wiki/Media_type[MediaType] of the Value being sent.

*  timeToLiveSeconds : OPTIONAL number (the number of seconds before this entry will automatically be deleted). If no parameter is sent, {brandname} assumes configuration default value. Passing any negative value will create an entry which will live forever.

*  maxIdleTimeSeconds : OPTIONAL number (the number of seconds after last usage of this entry when it will automatically be deleted). If no  parameter is sent, {brandname} configuration default value. Passing any negative value will create an entry which will live forever.

.Passing 0 as parameter for timeToLiveSeconds and/or maxIdleTimeSeconds
*  If both `timeToLiveSeconds` and `maxIdleTimeSeconds` are 0, the cache will use the default `lifespan` and `maxIdle` values configured in XML/programmatically
*  If _only_ `maxIdleTimeSeconds` is 0, it uses the `timeToLiveSeconds` value passed as parameter (or -1 if not present), and default `maxIdle` configured in XML/programmatically
*  If _only_ `timeToLiveSeconds` is 0, it uses default `lifespan` configured in XML/programmatically, and `maxIdle` is set to whatever came as parameter (or -1 if not present)

[[rest_server_get_data]]
== Getting data back out
HTTP GET and HEAD are used to retrieve data from entries.

[[rest_server_get_request]]
=== `GET /rest/{cacheName}/{cacheKey}`
This will return the data found in the given cacheName, under the given key - as the body of the response. A Content-Type header will be present in the response according to the Media Type negotiation. Browsers can use the cache directly of course (eg as a CDN). An link:http://en.wikipedia.org/wiki/HTTP_ETag[ETag] will be returned unique for each entry, as will the Last-Modified and Expires headers field indicating the state of the data at the given URL. ETags allow browsers (and other clients) to ask for data only in the case where it has changed (to save on bandwidth) - this is standard HTTP and is honoured by {brandname}.

.Headers

*  link:#rest_key_content_type[Key-Content-Type]: OPTIONAL The content type for the Key present in the URL. When omitted, _application/x-java-object; type=java.lang.String_ is assumed
*  link:#rest_accept[Accept]: OPTIONAL The required format to return the content

It is possible to obtain additional information by appending the "extended" parameter on the query string, as follows:

`GET /rest/cacheName/cacheKey?extended`

This will return the following custom headers:

* Cluster-Primary-Owner: the node name of the primary owner for this key
* Cluster-Backup-Owners: the node names of the backup owners for this key
* Cluster-Node-Name: the JGroups node name of the server that has handled the request
* Cluster-Physical-Address: the physical JGroups address of the server that has handled the request.

[[rest_server_head_request]]
=== `HEAD /rest/{cacheName}/{cacheKey}`
The same as GET, only no content is returned (only the header fields). You will receive the same content that you stored. E.g., if you stored a String, this is what you get back. If you stored some XML or JSON, this is what you will receive. If you stored a binary (base 64 encoded) blob, perhaps a serialized; Java; object - you will need to; deserialize this yourself.

Similarly to the GET method, the HEAD method also supports returning extended information via headers. See above.

.Headers

*  link:#rest_key_content_type[Key-Content-Type]: OPTIONAL The content type for the Key present in the URL. When omitted, _application/x-java-object; type=java.lang.String_ is assumed

[[rest_server_list_keys]]
== Listing keys

[[rest_server_list_get]]
=== `GET /rest/{cacheName}`

This will return a list of keys present in the given cacheName as the body of the response. The format of the response can be controlled via the Accept header as follows:

* _application/xml_ - the list of keys will be returned in XML format.
* _application/json_ - the list of keys will be return in JSON format.
* _text/plain_ - the list of keys will be returned in plain text format, one key per line

If the cache identified by cacheName is distributed, only the keys owned by the node handling the request will be returned. To return all keys, append the "global" parameter to the query, as follows:

`GET /rest/cacheName?global`

[[rest_server_remove_data]]
== Removing data
Data can be removed at the cache key/element level, or via a whole cache name using the HTTP delete method.

[[rest_server_delete_keys]]
=== `DELETE /rest/{cacheName}/{cacheKey}`

Removes the given key name from the cache.

.Headers

*  link:#rest_key_content_type[Key-Content-Type]: OPTIONAL The content type for the Key present in the URL. When omitted, _application/x-java-object; type=java.lang.String_ is assumed

[[rest_server_delete_cache]]
=== `DELETE /rest/{cacheName}`
Removes ALL the entries in the given cache name (i.e., everything from that path down). If the operation is successful, it returns 200 code.

[[rest_server_query]]
== Querying

The REST server supports Ickle Queries in JSON format. It's important that the cache is configured with
_application/x-protostream_ for both Keys and Values. If the cache is indexed, no configuration is needed.

[[rest_server_query_get]]
=== `GET /rest/{cacheName}?action=search&query={ickle query}`

Will execute an Ickle query in the given cache name.

.Request parameters

* _query_: REQUIRED the query string
* _max_results_: OPTIONAL the number of results to return, default is _10_
* _offset_: OPTIONAL the index of the first result to return, default is _0_
* _query_mode_: OPTIONAL the execution mode of the query once it's received by server. Valid values are _FETCH_ and _BROADCAST_. Default is _FETCH_.

.Query Result

Results are JSON documents containing one or more hits. Example:

[source, json]
----
{
  "total_results" : 150,
  "hits" : [ {
    "hit" : {
      "name" : "user1",
      "age" : 35
    }
  }, {
    "hit" : {
       "name" : "user2",
       "age" : 42
    }
  }, {
    "hit" : {
       "name" : "user3",
       "age" : 12
    }
  } ]
}
----

* _total_results_: NUMBER, the total number of results from the query.
* _hits_: ARRAY, list of matches from the query
* _hit_: OBJECT, each result from the query. Can contain all fields or just a subset of fields in case a _Select_ clause is used.

[[rest_server_query_post]]
=== `POST /{cacheName}?action=search`

Similar to que query using GET, but the body of the request is used instead to specify the query parameters.

Example:

[source,json]
----
{
 "query":"from Entity where name:\"user1\"",
 "max_results":20,
 "offset":10
}
----
