[[rest_v2_api]]
= REST v2 (version 2) API

The {brandname} REST v2 API improves on the REST v1 API, offering the same features and capabilities in addition to supporting resources beyond caching.

[NOTE]
The REST v1 API is deprecated and will not be supported in the next version of {brandname}

[[rest_v2_cache_operations]]
== Working with Caches

Use the REST API to create and manage caches on your {brandname} cluster and interact with cached entries.

[[rest_v2_create_cache]]
=== Creating Caches

To create a named cache across the {brandname} cluster, invoke a `POST` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/post_v2_create_cache.adoc[]
----

To configure the cache, you supply the configuration in `XML` or `JSON` format
as part of the request payload.

//dnaro: single source with proc_cli_creating_caches_files.adoc
XML Configuration::
A configuration in `XML` format must conform to the schema and include:
+
* `<infinispan>` root element.
* `<cache-container>` definition.
+
The following example shows a valid `XML` configuration:
+
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/infinispan_distributed_cache.xml[]
----

JSON Configuration::
A configuration in `JSON` format payload:
+
* Requires the cache definition only.
* Must follow the structure of an `XML` configuration.
- `XML` elements become `JSON` objects.
- `XML` attributes become `JSON` fields.
+
The following example shows the previous `XML` configuration in `JSON` format:
+
[source,json,options="nowrap",subs=attributes+]
----
include::config_examples/infinispan_distributed_cache.json[]
----

.Headers
|===
|Header |Required or Optional |Parameter

|`Content-Type`
|REQUIRED
|Sets the https://en.wikipedia.org/wiki/Media_type[MediaType] for the
{brandname} configuration payload; either `application/xml` or
`application/json`.
| `Flags` | OPTIONAL | Used to set https://docs.jboss.org/infinispan/10.0/apidocs/org/infinispan/commons/api/CacheContainerAdmin.AdminFlag.html[AdminFlags]
|===

[[rest_v2_cache_exists]]
=== Checking if caches exist

To verify if a cache is defined in {brandname} cluster, invoke a `HEAD` request:

[source,options="nowrap",subs=attributes+]
----
HEAD /v2/caches/{cacheName}
----

[[rest_v2_create_cache_template]]
==== Creating Caches with Templates

To create caches across a {brandname} cluster with pre-defined templates,
invoke a `POST` request with no payload and an extra request parameter:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/post_v2_cache_template.adoc[]
----

[[rest_v2_cache_configuration]]
=== Retrieving Cache Configuration

To retrieve the configuration of a {brandname} cache, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_configuration.adoc[]
----

.Headers
|===
|Header |Required or Optional |Parameter

|`Accept`
|OPTIONAL
|Sets the required format to return content. Supported formats are `application/xml` and `application/json`. The default is `application/json`. See link:#rest_accept[Accept] for more information.
|===

[[rest_v2_cache_config_convert]]
=== Converting Cache Configurations

To convert a certain existing cache configuration that is in XML format to JSON, invoke:

[source,options="nowrap",subs=attributes+]
----
POST /rest/v2/caches?action=toJSON
----

The POST body must contain a valid cache XML configuration and the response will contain the equivalent JSON representation.

[[rest_v2_cache_detail]]
=== Retrieving All the details related to a cache

To retrieve the details of a {brandname} cache, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_all_details.adoc[]
----

{brandname} returns the detail of the cache in `JSON` format, for example:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_full_cache_detail.json[]
----

* `stats` current stats of the cache.
* `size` the estimated size for the cache.
* `configuration` the cache configuration.
* `rehash_in_progress` true when a rehashing is in progress.
* `indexing_in_progress` true when indexing is in progress.
* `bounded` when expiration is enabled
* `indexed` true if the cache is indexed
* `persistent` true if the cache is persisted
* `transactional` true if the cache is transactional
* `secured` true if the cache is secured
* `has_remote_backup` true if the cache has remote backups
+


[[rest_v2_add_entries]]
=== Adding Entries

To add entries to a named cache, invoke a `POST` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/post_v2_add_keys.adoc[]
----

The preceding request places the payload, or request body, in the `cacheName`
cache with the `cacheKey` key. The request replaces any data that already
exists and updates the `Time-To-Live` and `Last-Modified` values, if they apply.

If a value already exists for the specified key, the `POST` request returns an
HTTP `CONFLICT` status and does not modify the value. To update values, you
should use `PUT` requests. See link:#rest_v2_replace_entries[Replacing Entries].

.Headers
|===
|Header |Required or Optional |Parameter

|`Key-Content-Type`
|OPTIONAL
|Sets the content type for the key in the request. See link:#rest_key_content_type[Key-Content-Type] for more information.

|`Content-Type`
|OPTIONAL
|Sets the link:https://en.wikipedia.org/wiki/Media_type[MediaType] of the value for the key.

|`timeToLiveSeconds`
|OPTIONAL
|Sets the number of seconds before the entry is automatically deleted. If you do not set this parameter, {brandname} uses the default value from the configuration. If you set a negative value, the entry is never deleted.

|`maxIdleTimeSeconds`
|OPTIONAL
|Sets the number of seconds that entries can be idle. If a read or write operation does not occur for an entry after the maximum idle time elapses, the entry is automatically deleted. If you do not set this parameter, {brandname} uses the default value from the configuration. If you set a negative value, the entry is never deleted.

|`flags`
|OPTIONAL
|The flags used to add the entry. See https://docs.jboss.org/infinispan/10.0/apidocs/org/infinispan/context/Flag.html[Flag] for more information.

|===

[NOTE]
The `flags` header also applies to all other operations involving data manipulation on the cache,

[NOTE]
====
If both `timeToLiveSeconds` and `maxIdleTimeSeconds` have a value of `0`, {brandname} uses the default `lifespan` and `maxIdle` values from the configuration.

If _only_ `maxIdleTimeSeconds` has a value of `0`, {brandname} uses:

* the default `maxIdle` value from the configuration.
* the value for `timeToLiveSeconds` that you pass as a request parameter or a value of `-1` if you do not pass a value.

If _only_ `timeToLiveSeconds` has a value of `0`, {brandname} uses:

* the default `lifespan` value from the configuration.
* the value for `maxIdle` that you pass as a request parameter or a value of `-1` if you do not pass a value.
====

[[rest_v2_replace_entries]]
=== Replacing Entries

To replace entries in a named cache, invoke a `PUT` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/put_v2_replace_keys.adoc[]
----

If a value already exists for the specified key, the `PUT` request updates the
value. If you do not want to modify existing values, use `POST` requests that
return HTTP `CONFLICT` status instead of modifying values. See
link:#rest_v2_add_entries[Adding Values].

[[rest_v2_retrieve_cache]]
=== Retrieving Data By Keys

To retrieve data for a specific key in a cache, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_cache_keys.adoc[]
----

The server returns data from the given cache, `cacheName`, under the given key,
`cacheKey`, in the response body. Responses contain `Content-Type` headers that
correspond to the `MediaType` negotiation.

[NOTE]
====
Browsers can also access caches directly, for example as a content delivery
network (CDN). {brandname} returns a unique
link:http://en.wikipedia.org/wiki/HTTP_ETag[ETag] for each entry along with the
`Last-Modified` and `Expires` header fields.

These fields provide information about the state of the data that is returned
in your request. ETags allow browsers and other clients to request only data
that has changed, which conserves bandwidth.
====

.Headers
|===
|Header |Required or Optional |Parameter

|`Key-Content-Type`
|OPTIONAL
|Sets the content type for the key in the request. The default is `application/x-java-object; type=java.lang.String`. See link:#rest_key_content_type[Key-Content-Type] for more information.

|`Accept`
|OPTIONAL
|Sets the required format to return content. See link:#rest_accept[Accept] for more information.
|===

[TIP]
====
Append the `extended` parameter to the query string to get additional information:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_cache_key_extended.adoc[]
----

The preceding request returns custom headers:

* `Cluster-Primary-Owner` returns the node name that is the primary owner of the key.
* `Cluster-Node-Name` returns the JGroups node name of the server that handled the request.
* `Cluster-Physical-Address` returns the physical JGroups address of the server that handled the request.
====

[[rest_v2_check_entries]]
=== Checking if Entries Exist

To check if a specific entry exists in a cache, invoke a `HEAD` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/head_v2_cache_keys.adoc[]
----

The preceding request returns only the header fields and the same content that
you stored with the entry. For example, if you stored a String, the request
returns a String. If you stored binary, base64-encoded, blobs or serialized
Java objects, {brandname} does not de-serialize the content in the request.

`HEAD` requests also support the `extended` parameter.

.Headers
|===
|Header |Required or Optional |Parameter

|`Key-Content-Type`
|OPTIONAL
|Sets the content type for the key in the request. The default is `application/x-java-object; type=java.lang.String`. See link:#rest_key_content_type[Key-Content-Type] for more information.
|===

[[rest_v2_delete_entries]]
=== Deleting Entries

To delete entries from a cache, invoke a `DELETE` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/delete_v2_cache_keys.adoc[]
----

{brandname} removes the entry under `cacheKey` from the cache.

.Headers
|===
|Header |Required or Optional |Parameter

|`Key-Content-Type`
|OPTIONAL
|Sets the content type for the key in the request. The default is `application/x-java-object; type=java.lang.String`. See link:#rest_key_content_type[Key-Content-Type] for more information.
|===

[[rest_v2_remove_cache]]
=== Removing Caches

To remove caches, invoke a `DELETE` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/delete_v2_caches.adoc[]
----

{brandname} deletes all data and removes the cache named `cacheName` from the
cluster.

[[rest_v2_get_keys]]
=== Retrieving cache keys

To obtain all the keys from the cache in JSON format, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_keys.adoc[]
----

.Request Parameters
|===
|Parameter |Required or Optional |Value

|`batch-size`
|OPTIONAL
|Specifies the internal batch size when retrieving the keys. The default value is 1000.
|===

[[rest_v2_clear_cache]]
=== Clearing Caches

To delete all data from a cache, invoke a `GET` request with the
`?action=clear` parameter:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_clear.adoc[]
----

[[rest_v2_cache_size]]
=== Getting Cache Size

To obtain the size of a cache across the entire cluster, invoke a `GET`
request with the `?action=size` parameter:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_size.adoc[]
----

[[rest_v2_cache_stats]]
=== Getting Cache Statistics

To obtain runtime statistics of a cache invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_stats.adoc[]
----

[[rest_v2_querying_indexing]]
=== Indexing and Search

Use the REST API to search data, monitor and obtain stats about indexes and queries.

[[rest_v2_query_cache]]
==== Querying Caches

Invoke a `GET` request to perform and Ickle query on a given cache:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_query.adoc[]
----

{brandname} returns one or more query hits in `JSON` format, for example:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_query_results.json[]
----

* `total_results` displays the total number of results from the query.
* `hits` is an array of matches from the query.
* `hit` is an object that matches the query.
+
Hits can contain all fields or a subset of fields if you use a `Select` clause.

.Request Parameters
|===
|Parameter |Required or Optional |Value

|`query`
|REQUIRED
|Specifies the query string.

|`max_results`
|OPTIONAL
|Sets the number of results to return. The default is `10`.

|`offset`
|OPTIONAL
|Specifies the index of the first result to return. The default is `0`.

|`query_mode`
|OPTIONAL
|Specifies how the {brandname} server executes the query. Values are `FETCH` and `BROADCAST`. The default is `FETCH`.
|===

To use the body of the request instead of specifying query parameters, invoke a
`POST` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/post_v2_search.adoc[]
----

The following example shows a query in the request body:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_query_request_body.json[]
----

[[rest_v2_query_reindex]]
=== Reindexing data

To re-index all data in a cache, use a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET  /v2/caches/{cacheName}/search/indexes?action=mass-index?mode={mode}
----

The `mode` param can be:

* `sync`: a response with code `200` will be received only after the reindexing is finished
* `async`: a response with code `200` will be returned right away, and the reindexing will keep running in the cluster.
Use the link:#rest_v2_query_index_stats[Index Stats] REST call to check the status.

[[rest_v2_query_purge_index]]
=== Purging indexes

To delete all indexes from a cache, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET  /v2/caches/{cacheName}/search/indexes?action=clear
----

[[rest_v2_query_index_stats]]
=== Obtaining index stats

To obtain information about the indexes present in the cache, use a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/search/indexes/stats
----

The result will be a JSON document:

[source,json,options="nowrap",subs=attributes+]
----
{
    "indexed_class_names": ["org.infinispan.sample.User"],
    "indexed_entities_count": {
        "org.infinispan.sample.User": 4
    },
    "index_sizes": {
        "cacheName_protobuf": 14551
    },
    "reindexing": false
}
----

* `indexed_class_names`: The class names of the indexes present in the cache. For protobuf, this value will always be `org.infinispan.query.remote.impl.indexing.ProtobufValueWrapper`
* `indexed_entities_count`: The number of entities indexed per class
* `index_sizes`: The size in bytes per index present in the cache
* `reindexing`: If true, the MassIndexer was started in this cache

[[rest_v2_query_stats]]
=== Obtaining query stats

To obtain information about the queries executed, use a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/search/query/stats
----

The result will be a JSON document:

[source,json,options="nowrap",subs=attributes+]
----
{
    "search_query_execution_count":20,
    "search_query_total_time":5,
    "search_query_execution_max_time":154,
    "search_query_execution_avg_time":2,
    "object_loading_total_time":1,
    "object_loading_execution_max_time":1,
    "object_loading_execution_avg_time":1,
    "objects_loaded_count":20,
    "search_query_execution_max_time_query_string": "FROM entity"
}
----

* `search_query_execution_count`: Number of queries executed
* `search_query_total_time`: Total time spent on queries
* `search_query_execution_max_time`: Maximum time taken for a query
* `search_query_execution_avg_time`: Average query time
* `object_loading_total_time`: Total time spent loading objects from the cache after query execution
* `object_loading_execution_max_time`: Maximum time spent loading objects execution
* `object_loading_execution_avg_time`: Average time spent loading objects execution
* `objects_loaded_count`: Count of object loaded
* `search_query_execution_max_time_query_string`: Slowest query executed


[[rest_v2_query_stats_clear]]
=== Clearing query stats

The runtime stats above can be reset by sending a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/search/query/stats?action=clear
----

[[rest_v2_list_caches]]
=== Listing Caches

To obtain a list of caches available in a {brandname} cluster, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_list_caches.adoc[]
----

[[rest_v2_cache_xsite]]
=== Cross site replication

Use the REST API to monitor and control Cross Site (x-site) replication on your {brandname} cluster.
See link:../xsite/xsite.html[Cross Site replication] for more details about this feature.

==== Getting status of all backup sites

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/
----

The response contains each site followed by a description of the status.
Example:

[source,json,options="nowrap",subs=attributes+]
----
{
  "NYC": "online",
  "LON": "offline"
}
----

.Returned Status
|===
|Value |Description

|`online`
|All nodes in the backup site are online

|`offline`
|All node in the backup site are offline

|`mixed`
|Some nodes in the backup site are online and others offline. It will include in the status the nodes that are offline. E.g.: `mixed, offline on nodes: Node1, Node2`
|===

==== Getting status of a backup site

To obtain the status of a single backup site:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/{siteName}
----

The response contains each node in the backup site with the status.
Example:

[source,json,options="nowrap",subs=attributes+]
----
{
  "NodeA":"offline",
  "NodeB":"online"
}
----

.Returned Status
|===
|Value |Description

|`online`
|The node is online

|`offline`
|The node is offline

|`failed`
|Failed to obtain status, the remote cache could be shutting down or a network error occurred during the request
|===

==== Taking a backup site offline

To take a backup site `siteName` offline, for the cache `cacheName`, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/{siteName}?action=take-offline
----

==== Bringing a backup site online

To take a backup site `siteName` online, for the cache `cacheName`, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/{siteName}?action=bring-online
----

==== Starting a state push to a backup site

To start pushing state of a cache `cacheName` to a remote backup site `siteName`, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/{siteName}?action=start-push-state
----

==== Cancelling an ongoing state push to a backup site

To cancel a state push of the cache `cacheName` to a remote backup site `siteName`, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/{siteName}?action=cancel-push-state
----

==== Getting the status of a state push

To obtain the status of an ongoing state push of cache `cacheName` to backup `siteName` execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/{siteName}?action=cancel-push-state
----

The response will be a JSON document with each destination site name and the state transfer status.
Example:

[source,json,options="nowrap",subs=attributes+]
----
{
   "NYC":"CANCELED",
   "LON":"OK"
}
----

The possible statuses are `SENDING`, `OK`, `ERROR` and `CANCELLING`

==== Tuning the take offline parameters of a remote site

A remote site can be automatically marked as offline in case some conditions are met.
To check the configured parameters, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/{siteName}/take-offline-config
----

The response include two fields, `after_failures` and `min_wait`:

[source,json,options="nowrap",subs=attributes+]
----
{
  "after_failures": 2,
  "min_wait": 1000
}
----

To change those parameters, execute a PUT request:

[source,options="nowrap",subs=attributes+]
----
PUT /v2/caches/{cacheName}/x-site/backups/{siteName}/take-offline-config
----

with a body containing the new values, e.g.:

[source,json,options="nowrap",subs=attributes+]
----
{
  "after_failures": 4,
  "min_wait": 5000
}
----

==== Cancelling the receiving state on a site

The main use for this method is when the link between the sites is broken and the receiver site keeps it state transfer state forever.

To set the cluster to normal state in the scope of `cacheName` for state pushed from site `siteName` execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/backups/{siteName}?action=cancel-receive-state
----

==== Clearing the state transfer status of a pushing site

To clear the state transfer status of a (sending) site, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /v2/caches/{cacheName}/x-site/local?action=clear-push-state-status
----

[[rest_v2_cache_manager_operations]]
== Interacting with Cache Managers

The REST API lets you interact with {brandname} Cache Managers to cluster and
usage statistics.

[[rest_v2_cache_manager_info]]
=== Getting Basic Cache Manager Information

To obtain information about a cache manager, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_cache_managers.adoc[]
----

{brandname} responds with a `JSON` document such as the following:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_cache_manager_response.json[]
----

* `version` contains the {brandname} version
* `name` contains the name of the cache manager as defined in the configuration
* `coordinator` is true if the cache manager is the coordinator of the cluster
* `cache_configuration_names` contains an array of all caches configurations defined in the cache manager
* `cluster_name` contains the name of the cluster as defined in the configuration
* `physical_addresses` contains the physical network addresses associated with the cache manager
* `coordinator_address` contains the physical network addresses of the coordinator of the cluster
* `cache_manager_status` the lifecycle status of the cache manager.
For possible values, check the https://docs.jboss.org/infinispan/9.4/apidocs/org/infinispan/lifecycle/ComponentStatus.html[`org.infinispan.lifecycle.ComponentStatus`] documentation
* `created_cache_count` number of created caches, excludes all internal and private caches
* `running_cache_count` number of created caches that are running
* `node_address` contains the logical address of the cache manager
* `cluster_members` and `cluster_members_physical_addresses` an array of logical and physical addresses of the members of the cluster
* `cluster_size` number of members in the cluster
* `defined_caches` A list of all caches defined in the cache manager, excluding private caches but including internal caches that are accessible

[[rest_v2_cache_manager_health]]
=== Getting Cluster Health

To review health information for a {brandname} cluster, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_cluster_health.adoc[]
----

{brandname} responds with a `JSON` document such as the following:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_cache_health_response.json[]
----

* `cluster_health` contains the health of the cluster
** `cluster_name` specifies the name of the cluster as defined in the configuration.
** `health_status` provides one of the following:
*** `DEGRADED` indicates at least one of the caches is in degraded mode.
*** `HEALTHY_REBALANCING` indicates at least one cache is in the rebalancing state.
*** `HEALTHY` indicates all cache instances in the cluster are operating as expected.
** `number_of_nodes` displays the total number of cluster members.
Returns a value of `0` for non-clustered (standalone) servers.
** `node_names` is an array of all cluster members.
Empty for standalone servers.
* `cache_health` contains health information per-cache
** `status`  HEALTHY, DEGRADED or HEALTHY_REBALANCING
** `cache_name` the name of the cache as defined in the configuration.

[[rest_v2_cache_manager_health_status]]
==== Getting Cache Manager Health Status

To retrieve the health status of the cache managers, without the need for
authentication, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_health_status.adoc[]
----

{brandname} responds with one of the following in `text/plain`:

* `HEALTHY`
* `HEALTHY_REBALANCING`
* `DEGRADED`

[[rest_v2_cache_manager_availability]]
=== Checking REST Endpoint Availability

To check that a {brandname} server REST endpoint is available, invoke a `HEAD`
request in the health resource:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/head_v2_health.adoc[]
----

If the preceding request returns a successful response code then the
{brandname} REST server is running and serving requests.

[[rest_v2_cache_manager_config]]
=== Obtaining Global Configuration for Cache Managers

To obtain the
link:{javadocroot}/org/infinispan/configuration/global/GlobalConfiguration.html[GlobalConfiguration] associated with the Cache Manager, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_cache_manager_config.adoc[]
----

.Headers
|===
|Header |Required or Optional |Parameter

|`link:#rest_accept[Accept]`
|OPTIONAL
|The required format to return the content. Supported formats are _application/json_ and _application/xml_. JSON is assumed if no header is provided.
|===

[[rest_v2_cache_manager_caches_config]]
=== Obtaining Configuration for All Caches

To get the configuration for all caches, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_cache_configs.adoc[]
----

{brandname} responds with a `JSON` array that contains each cache and cache configuration:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_cache_config_response.json[]
----

[[rest_v2_cache_manager_cache_list]]
=== (Experimental) Obtaining caches with cache information

To get the list of all the caches of a cache manager with cache informations, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_caches.adoc[]
----

{brandname} responds with a `JSON` array that contains each cache and the cache information:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_caches_info_response.json[]
----

[[rest_v2_cache_manager_stats]]
=== Getting Cache Manager Statistics

To obtain the statistics of a Cache Manager, invoke a `GET` request.

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_cache_manager_stats.adoc[]
----

{brandname} responds with a `JSON` document that contains the following
information:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_cache_stats_response.json[]
----

* `statistics_enabled` is `true` if statistics collection is enabled for the Cache Manager.
* `read_write_ratio` displays the read/write ratio across all caches.
* `time_since_start` shows the time, in seconds, since the Cache Manager started.
* `time_since_reset` shows the number of seconds since the Cache Manager statistics were last reset.
* `number_of_entries` shows the total number of entries currently in all caches from the Cache Manager. This statistic returns entries in the local cache instances only.
* `total_number_of_entries` shows the number of store operations performed across all caches for the Cache Manager.
* `off_heap_memory_used` shows the amount, in `bytes[]`, of off-heap memory used by this cache container.
* `data_memory_used` shows the amount, in `bytes[]`, that the current eviction algorithm estimates is in use for data across all caches. Returns `0` if eviction is not enabled.
* `misses` shows the number of `get()` misses across all caches.
* `remove_hits` shows the number of removal hits across all caches.
* `remove_misses` shows the number of removal misses across all caches.
* `evictions` shows the number of evictions across all caches.
* `average_read_time` shows the average number of milliseconds taken for `get()` operations across all caches.
* `average_read_time_nanos` same as `average_read_time` but in nanoseconds.
* `average_remove_time` shows the average number of milliseconds for `remove()` operations across all caches.
* `average_remove_time_nanos` same as `average_remove_time` but in nanoseconds.
* `required_minimum_number_of_nodes` shows the required minimum number of nodes to guarantee data consistency.
* `hits` provides the number of `get()` hits across all caches.
* `stores` provides the number of `put()` operations across all caches.
* `current_number_of_entries_in_memory` shows the total number of entries currently in all caches, excluding passivated entries.
* `hit_ratio` provides the total percentage hit/(hit+miss) ratio for all caches.
* `retrievals` shows the total number of `get()` operations.

[[rest_v2_cache_manager_xsite]]
=== Managing Cross site replication

The REST API expose several operations to manage cross site replication for all the caches in a cache manager.

[[rest_v2_cache_manager_site_status]]
==== Retrieving backup statuses

To retrieve the statuses of all backup sites from the caches of `cacheManagerName`, do a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/
----

Example response:

[source,json,options="nowrap",subs=attributes+]
----
{
   "SFO-3":{
      "status":"online"
   },
   "NYC-2":{
      "status":"mixed",
      "online":[
         "CACHE_1"
      ],
      "offline":[
         "CACHE_2"
      ]
   }
}
----

The `status` field can assume the following values:

* `online`: all caches are online in the backup site.
* `offline`: all caches are offline in the backup site.
* `mixed`: some caches are online and others offline, and their names will be listed in the `online` and `offline` arrays respectively.


[[rest_v2_cache_manager_take_offline]]
==== Taking a backup site offline

To take all caches from `cacheManagerName` offline, for the backup site `siteName`, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/{siteName}?action=take-offline
----

[[rest_v2_cache_manager_bring_online]]
==== Bringing a backup site online

To bring all caches from `cacheManagerName` online, for the backup site `siteName`, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/{siteName}?action=bring-online
----

[[rest_v2_cache_manager_start_push]]
==== Starting a state push

To start pushing state of all caches of `cacheManagerName` to a backup site `siteName`, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/{siteName}?action=start-push-state
----

[[rest_v2_cache_manager_cancel_push]]
==== Cancelling an ongoing state push

To cancel an ongoing state push of all caches of `cacheManagerName` to a remote backup site `siteName`, execute a `GET` request:

[source,options="nowrap",subs=attributes+]
----
GET /rest/v2/cache-managers/{cacheManagerName}/x-site/backups/{siteName}?action=cancel-push-state
----

[[rest_server_counters]]
== Working with Counters

Use the REST API to create, delete, and modify counters.

[[rest_server_counters_create]]
=== Creating Counters

To create a counter, invoke a `POST` request with the configuration as payload:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/post_v2_counters.adoc[]
----

The payload must contain a configuration for the counter in `JSON` format, as in the following examples:

[source,json,options="nowrap",subs=attributes+]
----
include::json_examples/weak_counter.json[]
----

[source,json,options="nowrap",subs=attributes+]
----
include::json_examples/strong_counter.json[]
----

[[rest_server_counters_delete]]
=== Deleting Counters

To delete a counter, invoke a `DELETE` request with the counter name:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/delete_v2_counter.adoc[]
----

[[rest_server_counters_config]]
=== Retrieving Counter Configuration

The get the counter configuration, invoke a `GET` request with the counter name:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter_config.adoc[]
----

{brandname} responds with a `JSON` representation of the counter configuration.

[[rest_server_counters_add]]
=== Adding Values to Counters

To add a value to a named counter, invoke a `POST` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/post_v2_counter.adoc[]
----

If the request payload is empty, the counter is incremented by one, otherwise
the payload is interpreted as a signed long and added to the counter.

Request responses depend on the type of counter, as follows:

* `WEAK` counters return empty responses.
* `STRONG` counters return their values after the operation is applied.

[NOTE]
====
This method processes `plain/text` content only.
====

[[rest_server_counters_get]]
=== Getting Counter Values

To retrieve the value of a counter, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter.adoc[]
----

.Headers
|===
|Header |Required or Optional |Parameter

|`link:#rest_accept[Accept]`
|OPTIONAL
|The required format to return the content. Supported formats are _application/json_ and _text/plain_. JSON is assumed if no header is provided.
|===

[[rest_server_counters_reset]]
=== Resetting Counters

To reset counters, invoke a `GET` request with the `?action=reset` parameter:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter_reset.adoc[]
----

[[rest_server_counters_inc_weak]]
=== Incrementing Counters

To increment a counter, invoke a `GET` request with the `?action=increment`
parameter:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter_increment.adoc[]
----

Responses depend on the type of counter, as follows:

* `WEAK` counters return empty responses.
* `STRONG` counters return their values after the operation is applied.

[[rest_server_counters_add_weak]]
=== Adding Deltas to Counters

To add an arbitrary amount to a counter, invoke a `GET` request with the
`?action=add` and `delta` parameters:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter_add_delta.adoc[]
----

Request responses depend on the type of counter, as follows:

* `WEAK` counters return empty responses.
* `STRONG` counters return their values after the operation is applied.

[[rest_server_counters_dec_strong]]
=== Decrementing Counters

To decrement a counter, invoke a `GET` request with the `?action=decrement`
parameter:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter_decrement.adoc[]
----

Request responses depend on the type of counter, as follows:

* `WEAK` counters return empty responses.
* `STRONG` counters return their values after the operation is applied.

[[rest_server_counters_cmpset]]
=== compareAndSet Strong Counters

To atomically set the value of a strong counter with the `compareAndSet`
method, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter_compare_set.adoc[]
----

{brandname} atomically sets the value to `{update}` if the current value is
`{expect}`. If the operation is successful, {brandname} returns `_true_`.

[[rest_server_counters_cmpswp]]
=== compareAndSwap Strong Counters

To atomically set the value of a strong counter with the `compareAndSwap`
method, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter_compare_swap.adoc[]
----

{brandname} atomically sets the value to `{update}` if the current value is
`{expect}`. If the operation is successful, {brandname} returns the previous
value in the payload.

[[rest_server_counters_list]]
=== Listing Counters

To obtain a list of counters available in a {brandname} cluster, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_counter_list.adoc[]
----

[[rest_v2_server]]
== Interacting with {brandname} Servers

The REST API lets you interact with {brandname} servers to retrieve server
configuration and information, Java Virtual Machine (JVM) memory usage and
thread dumps. You can also perform operations to manage servers.

[[rest_v2_server_info]]
=== Retrieving Basic Server Information

To view basic information about a {brandname} server, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server.adoc[]
----

The response contains the server name, codename, and version in `JSON` format,
as in the following example:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_server_response.json[]
----

[[rest_v2_server_cm]]
=== Cache Managers

To obtain the list of the server's cache managers:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_cachemanagers.adoc[]
----

The response will contain an array with the names of the cache managers configured in the server.

[[rest_v2_cache_ignore]]
=== Ignoring caches

A cache can be excluded temporarily from receiving requests from clients,
returning a code 503 (service unavailable) for REST clients or
a Server Error (code 0x85) for Hot Rod clients.

To ignore a cache, use an empty `POST` request with the cache manager name and the cache name:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_cache_ignore_add.adoc[]
----

To remove the cache from the ignore list, use a `DELETE` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_cache_ignore_delete.adoc[]
----

Finally, to check the caches that are ignored, do a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_cache_ignore_list.adoc[]
----

TIP: Currently {brandname} only supports a single cache manager per server, but for future compatibility the
name must be provided in the requests above.

[[rest_v2_server_config]]
=== Obtaining Server Configuration

To get the configuration for a {brandname} server, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_config.adoc[]
----

//dnaro: server schema docs should use the configdocroot attribute? should we point to the generated html or the xsd?
//https://docs.jboss.org/infinispan/10.0/configdocs/infinispan-config-10.0.html
The server responds with the configuration in `JSON` format. The structure
follows the
link:https://github.com/infinispan/infinispan/blob/master/server/runtime/src/main/resources/schema/infinispan-server-10.1.xsd[server schema], as in the
following example:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_server_config_response.json[]
----

[[rest_v2_server_env]]
=== Getting Environment Variables

To get environment variables that the server uses, invoke a `GET` request:
//dnaro: is this all possible envs? or only envs the server currently has set?

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_env.adoc[]
----

//dnaro: add example response

[[rest_v2_server_memory]]
=== Getting JVM Memory Details

To get information about JVM memory usage, invoke a
`GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_memory.adoc[]
----

The server responds with heap and non-heap memory statistics, direct memory
usage, and information about memory pools and garbage collection in `JSON`
format.

[[rest_v2_server_threads]]
=== Getting JVM Thread Dumps

To get the current thread dump for the JVM, invoke a
`GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_threads.adoc[]
----

The response is the current thread dump in `text/plain` format.

[[rest_v2_server_stop]]
=== Stopping {brandname} Servers

To stop the {brandname} server, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_server_stop.adoc[]
----

The server responds with `200(OK)` and then stops running.

[[rest_v2_cluster]]
== Interacting with {brandname} Clusters

The REST API lets you interact with {brandname} clusters to retrieve cluster-wide
configuration and information. You can also perform operations to manage clusters.

[[rest_v2_cluster_stop]]
=== Stopping {brandname} Clusters

To gracefully stop {brandname} clusters, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_cluster_stop.adoc[]
----

The server responds with `200(OK)` and then the cluster performs a graceful shutdown.

You can also stop one or more specific servers by passing their names:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_cluster_stop_named.adoc[]
----

[[rest_v2_tasks]]
== Server-side tasks

The REST API lets you interact with {brandname} servers to retrieve server
configuration and information, Java Virtual Machine (JVM) memory usage and
thread dumps. You can also perform operations to manage servers.

[[rest_v2_tasks_list]]
=== Retrieving Tasks Information

To view information about available tasks, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_tasks_list.adoc[]
----

The response consists of a list of available tasks, including the name, the engine that handles the task, the
named parameters for the task, the execution mode (`ONE_NODE` or `ALL_NODES`) and the allowed security role in `JSON` format,
as in the following example:

[source,json,options="nowrap",subs=attributes+]
----
include::rest_examples/rest_tasks_response.json[]
----

[[rest_v2_tasks_list]]
=== Executing Tasks

To execute a task, invoke a `GET` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/get_v2_tasks_exec.adoc[]
----

The request includes the task name and any required parameters as request parameters prefixed by `param.`
The response will contain the task result.

[[rest_v2_tasks_upload]]
=== Uploading Script Tasks

To upload a script tasks, invoke a `PUT` or `POST` request:

[source,options="nowrap",subs=attributes+]
----
include::rest_examples/post_v2_tasks_upload.adoc[]
----

supplying as the content payload the script you wish to upload. The script can then be executed like any other task using the task execution action.
