== Security Concepts

=== Authorization

Just like embedded mode, the server supports cache authorization using the same configuration, e.g.:

[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/cache_authorization.xml[]
----

=== Server Realms

{brandname} Server security is built around the concept of security realms.
Security Realms are used by the server to provide identity, encryption, authentication and authorization information for the server endpoints.
A security realm is identified by a name and combines any number of identities and sub-realms, each one also identified by a name.
Bear in mind that the choice of authentication mechanism you select for the protocols limits the type of authentication sources, since the credentials must be in a format supported by the algorithm itself (e.g. pre-digested passwords for the digest algorithm).

==== Server identities

The {brandname} Server supports two kinds of identities:

* SSL identities, backed by a _keystore_.
* Kerberos identities, backed by a _keytab_ file.

[[security_hotrod_rest_encryption]]
===== SSL identities and endpoint encryption

A SSL identity is represented by a certificate (or a chain of certificates) stored within a _keystore_.
{brandname} Server automatically recognizes and supports multiple keystore formats: JKS, JCEKS, PKCS12, BKS, BCFKS and UBER.
When the server endpoint is configured with a realm which has an SSL identity it will automatically enable encryption.

.SSL Identity
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_ssl_identity.xml[]
----

The ideal server certificate is one which is signed by a trusted Certificate Authority (be it a Root or Intermediate CA), and configuring clients to trust that authority.
The following sequence of shell commands uses Java's `keytool` to create a CA certificate, a Server certificate signed by the CA and imports both into a keystore to be used by the server.

.Creating certificates with keytool
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/keytool.adoc[]
----

Place the `server.p12` file in the server configuration directory.

NOTE: To configure the client In order to connect to the server using the Hot Rod protocol, the client needs a trust store containing the public key
of the server(s) or of the CA that has signed the key of the server you are going to connect to, unless the key was signed by a Certification Authority (CA) trusted by
the JRE.

The following code snippet shows how to use the `client_truststore.p12` we generated above in your clients so that they will trust the server's certificate:

[source,java]
----
ConfigurationBuilder clientBuilder = new ConfigurationBuilder();
clientBuilder
    .addServer()
        .host("127.0.0.1")
        .port(11222)
     .security()
        .ssl()
           .trustStoreFileName("client_truststore.p12")
           .trustStorePassword("secret".toCharArray());
remoteCacheManager = new RemoteCacheManager(clientBuilder.build());
----

You can require that clients also present a certificate by adding `require-ssl-client-auth="true"` to the `endpoint` element:

.Requiring client certificates
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_endpoint_require_client_cert.xml[]
----

It is also possible to generate development certificates on server startup. In order to do this, just specify `generate-self-signed-certificate-host`
in the keystore element as shown below:

.Generating Keystore automatically
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_ssl_identity_generated.xml[]
----

[NOTE]
====
There are three basic principles that you should remember when using automatically generated keystores:

- They shouldn't be used on a production environment
- They are generated when necessary (e.g. while obtaining the first connection from the client)
- They also contain certificates so they might be used in a Hot Rod client directly
====

The SSL identity also defines the way in which the SSL engine is configured, in terms of available protocols and ciphers.
The default configuration should work for most scenarios, but it can be fine-tuned if necessary:

.SSL engine configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_ssl_identity_engine.xml[]
----

Make sure you have the correct ciphers for the protocol features you need (e.g. HTTP/2 ALPN)

===== Kerberos identities

A Kerberos identity is represented by a _keytab_ file which contains pairs of Kerberos principals and encrypted keys (derived from Kerberos password).
While a _keytab_ can contain both user and service account principals, in the context of a {brandname} server we only use the latter.
This allows the server to identify itself to clients as well as acting as an intermediary authentication service between the clients and the Kerberos server.
Since a Kerberos Service Account includes the name of the service in the principal, you usually need to supply one identity per service, i.e. one for HTTP and one for Hot Rod.
For example, you may have a `datagrid` server in the `INFINISPAN.ORG` domain, you'd need both a `hotrod/datagrid@INFINISPAN.ORG` service principal for Hot Rod (note the lowercase service name) and an `HTTP/datagrid@INFINISPAN.ORG` service principal for HTTP (note the uppercase service name).

.Kerberos service identities
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_identities_kerberos.xml[]
----

After creating the service principals in your Kerberos server, you will need to create the relevant _keytab_ files:

Linux::
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/keytab_nix_mit.adoc[]
----

Microsoft Windows::
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/keytab_win.adoc[]
----

Once you have obtained the keytab files, place them in the server's configuration directory.

==== Property realm

Property realms are the simplest type of realm that you can configure in {brandname}:

.Property Realm configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_properties_realm.xml[]
----

They use two property files:

* a users property file which maps user names to passwords. The latter can be either in plain text or hashed (recommended).
+
[source,options="nowrap",subs=attributes+]
----
include::config_examples/server_users.properties[]
----
+
* a groups property file which maps users to group names.
+
[source,options="nowrap",subs=attributes+]
----
include::config_examples/server_groups.properties[]
----
+

{brandname} Server comes with a `user-tool.sh` script (`user-tool.bat` for Windows) to ease the process of adding new user/role mappings to the above property files.
An example invocation for adding a user with an initial set of groups:

Linux::
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/user_tool_nix.adoc[]
----

Microsoft Windows::
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/user_tool_win.adoc[]
----

Property realms support the following authentication mechanisms:

* *SASL (Hot Rod)*: `PLAIN`, `+DIGEST-*+`, `+SCRAM-*+`
* *HTTP (REST)*: `Basic`, `Digest`

==== LDAP realm

LDAP realms connect to LDAP servers, such as OpenLDAP, Red Hat Directory Server, Apache Directory Server or Microsoft Active Directory, to authenticate users and obtain membership information.
Since the layout of entries in an LDAP server varies depending on the type and deployment, the LDAP realm configuration is quite articulate.
The following is an example

.LDAP Realm configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_ldap_realm.xml[]
----

The `ldap-realm` element specifies the LDAP connection url as well as a principal and credential to use.
The principal must be able to perform LDAP queries and access specific attributes, so it should have the necessary privileges.
You can also set additional properties which tune the connection, e.g. timeouts and pooling:

.LDAP Connection configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_ldap_realm_connection.xml[]
----

It is then necessary to provide a mapping from LDAP entries to identities using the `identity-mapping` element.
The first part is to find the user's entry based on a provided identifier, usually a username.
The `rdn-identifier` specifies the LDAP attribute which contains the username (e.g. `uid` or `sAMAccountName`).
It is also useful to limit the search only to the LDAP subtree which contains the user entries, otherwise it will search the entire tree.
This is achieved by passing a starting context in the `search-dn` attribute.

Then we need to decide how to verify a user's credentials. This can be done in two ways:

* by adding the `direct-verification="true"` attribute to the `ldap-realm` element, the realm will try to connect to the LDAP server using the supplied credentials. This is the recommended configuration.
* by adding a `user-password-mapper` element to the `identity-mapping` element specifying which attribute contains the password (e.g. `userPassword`)

Some authentication mechanisms (most notably the Kerberos-based ones: `GSSAPI`, `GS2-KRB5` and `Negotiate`) supply a username which needs to be _cleaned up_ before it can be used to search LDAP.
In these situation you should add a `name-rewriter` to the `ldap-realm` which extracts the username from the principal. For example, the following rewriter uses a regular expression and group capturing to remove the domain part:

.LDAP realm with principal rewriting
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_ldap_realm_rewriter.xml[]
----

Next, we will want to retrieve all the groups a user is a member of, since this information may not be stored as part of a user entry.
There are usually two ways in which this is implemented:

* Membership information is stored under group entries (which usually have class `groupOfNames`) in the `member` attribute (this is the typical layout in OpenLDAP). In this case you will need to use an attribute filter as follows:
+
`<attribute filter="(&amp;(objectClass=groupOfNames)(member={1}))" filter-dn="ou=Roles,dc=infinispan,dc=org" from="cn" to="Roles" />`
+
The above will search for entries matching the supplied `filter` (which matches groups with a `member` attribute equal to the user's DN) under the `filter-dn`.
It will then extract the group entry's CN (as specified by `from`) and add it to the user's `Roles`.
* Membership information is stored in the user entry in the `memberOf` attribute (typical in Microsoft Active Directory). In this case use an attribute reference as follows:
+
`<attribute-reference reference="memberOf" from="cn" to="Roles" />`
+
The above will get all `memberOf` attributes from the user and extract the CN (as specified by `from`) and add them to the user's `Roles`.


LDAP Realms support the following authentication mechanisms directly:

* *SASL (Hot Rod)*: `PLAIN`, `+DIGEST-*+`, `+SCRAM-*+`
* *HTTP (REST)*: `Basic`, `Digest`

LDAP Realms can also be used to _fill-in_ authorization information for users obtained through realms which don't provide this directly (e.g. Trust, Kerberos)

==== Trust Store realm

A Trust Store realm is backed by a keystore containing the public certificates of all the clients you want to allow to connect.
It is used with client-certificate authentication mechanisms (EXTERNAL for Hot Rod and CLIENT_CERT for HTTP) so it requires that the server's realm also includes an SSL server identity as well as requiring client certificate authentication on the endpoint.

.Trust Store realm configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_truststore_realm.xml[]
----

You should use `keytool` to import all of the client certificates into the trust store.

==== Token realm

The Token realm relies on external validation services to validate tokens.
It requires a provider compatible with RFC-7662 (OAuth2 Token Introspection), such as KeyCloak.

.Token realm configuration with OAuth introspection
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/server_token_realm_oauth.xml[]
----

The `auth-server-url` attribute on the realm specifies the URL of the authentication server.
The `oauth2-introspection` element specifies the `introspection-url` as well as a `client-id` and `client-secret` which will be used for interpreting the tokens.

Token realms support the following authentication mechanisms:

* *SASL (Hot Rod)*: `OAUTHBEARER`
* *HTTP (REST)*: `Bearer`

[[security_hotrod_auth]]
== Hot Rod Authentication

The Hot Rod protocol supports authentication by leveraging the SASL mechanisms.
The supported SASL mechanisms (usually shortened as mechs) are:

* `PLAIN` - This is the most insecure mech, since credentials are sent over the wire in plain-text format, however it is the simplest to get to work. In combination with encryption (i.e. TLS) it can be used safely. It is equivalent to the `BASIC` HTTP mechanism.
* `+DIGEST-*+` - This family of mechs hashes the credentials before sending them over the wire, so it is more secure than `PLAIN`. The supported implementations, which differ in the hashing algorithm, are: `DIGEST-MD5`, `DIGEST-SHA`, `DIGEST-SHA-256`, `DIGEST-SHA-384` and `DIGEST-SHA-512` ordered by increasing strength. These mechs are comparable to the `DIGEST` HTTP mechanism.
* `+SCRAM-*+` - This family of mechs is similar to `+DIGEST-*+`, but increases security by using an additional _salt_ for increased security. The supported implementations, which differ in the hashing algorithm, are: `SCRAM-SHA`, `SCRAM-SHA-256`, `SCRAM-SHA-384` and `SCRAM-SHA-512` ordered by increasing strength.
* `GSSAPI` - This mech uses Kerberos tickets, and therefore requires the presence of a properly configured Kerberos Domain Controller (such as Microsoft Active Directory), and a corresponding `kerberos` server identity in the realm. It is also usually used in combination with an `ldap-realm` for retrieving user membership information. These mechs are equivalent with the `SPNEGO` HTTP scheme.
* `GS2-KRB5` - An improvement over `GSSAPI`, it has the same requirements and is configured in the same way.
* `EXTERNAL` - This mech obtains credentials from the underlying transport (i.e. from a X.509 client certificate) and therefore requires encryption using client-certificates to be enabled. It is equivalent to the `CLIENT_CERT` HTTP mechanism.
* `OAUTHBEARER` - This mech enables the use of OAuth tokens as a way to. It requires a token realm. It is equivalent to the `BEARER_TOKEN` HTTP mechanism.

The following configuration enables authentication against the `default` realm, using various SCRAM and DIGEST SASL mechanisms and only enables the *auth* QoP (see link:#security_saslqop[SASL Quality of Protection]):

.Hot Rod connector configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/hotrod_connector_sasl.xml[]
----

Notice the server-name attribute: it is the name that the server declares to incoming clients and therefore the client configuration must match.
It is particularly important when using `GSSAPI` or `GS2-KRB5` mechs as it is equivalent to the Kerberos service name.
The Kerberos mechanisms also need to indicate the identity that will be used:

.Hot Rod connector configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/hotrod_connector_sasl_kerberos.xml[]
----

[[security_saslqop]]
=== SASL Quality of Protection

While the main purpose of SASL is to provide authentication, some mechanisms also support integrity and privacy protection, also known as Quality of Protection (or qop).
During authentication negotiation, ciphers are exchanged between client and server, and they can be used to add checksums and encryption to all subsequent traffic.
You can tune the required level of qop as follows:

[%header%autowidth]
|===
| QOP | Description
| auth | Authentication only
| auth-int | Authentication with integrity protection
| auth-conf | Authentication with integrity and privacy protection
|===

=== SASL Policies

You can further refine the way a mechanism is chosen by tuning the SASL policies.
This will effectively include / exclude mechanisms based on whether they match the desired policies.

[%header%autowidth]
|===
| Policy | Description
| forward-secrecy | Specifies that the selected SASL mechanism must support forward secrecy between sessions. This means that breaking into one session will not automatically provide information for breaking into future sessions.
| pass-credentials | Specifies that the selected SASL mechanism must require client credentials.
| no-plain-text | Specifies that the selected SASL mechanism must not be susceptible to simple plain passive attacks.
| no-active | Specifies that the selected SASL mechanism must not be susceptible to active (non-dictionary) attacks. The mechanism might require mutual authentication as a way to prevent active attacks.
| no-dictionary | Specifies that the selected SASL mechanism must not be susceptible to passive dictionary attacks.
| no-anonymous | Specifies that the selected SASL mechanism must not accept anonymous logins.
|===

Each policy's value is either "true" or "false".
If a policy is absent, then the chosen mechanism need not have that characteristic (equivalent to setting the policy to "false").
One notable exception is the *no-anonymous* policy which, if absent, defaults to true, thus preventing anonymous connections.

NOTE: It is possible to have mixed anonymous and authenticated connections to the endpoint, delegating actual access logic to cache
authorization configuration. To do so, set the *no-anonymous* policy to false and turn on cache authorization.

The following configuration selects all available mechanisms, but effectively only enables GSSAPI, since it is the only one that respects all chosen policies:

.Hot Rod connector policies
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/hotrod_connector_policies.xml[]
----

[[security_rest_auth]]
== REST Authentication

The REST connector supports authentication by leveraging the HTTP authentication schemes.
The supported mechanism names are:

* `BASIC` - This mechanism corresponds to the `Basic` HTTP scheme. This is the most insecure scheme, since credentials are sent over the wire in plain-text format, however it is the simplest to get to work. In combination with encryption (i.e. TLS) it can be used safely. It is comparable to the `PLAIN` SASL mechanism.
* `DIGEST` - This mechanism corresponds to the `Digest` HTTP scheme. It is more secure than `BASIC` because it uses hashing and a nonce to protect against replay attacks. The server supports multiple hashing algorithms: `SHA-512`, `SHA-256` and `MD5`. It is comparable to the `+DIGEST-*+` family of SASL mechanisms.
* `SPNEGO` - This mechanism corresponds to the `Negotiate` HTTP scheme and uses Kerberos tickets, and therefore requires the presence of a properly configured Kerberos Domain Controller (such as Microsoft Active Directory), and a corresponding `kerberos` server identity in the realm. It is also usually used in combination with an `ldap-realm` for retrieving user membership information. It is comparable to the `GSSAPI` and `GS2-KRB5` SASL mechanisms.
* `BEARER_TOKEN` - This mechanism corresponds to the `Bearer` HTTP scheme and enables the use of OAuth tokens as a way to authenticate users. It requires a token realm. It is equivalent to the `OAUTHBEARER` SASL mechanism.
* `CLIENT_CERT` - This is a pseudo-mechanism which relies on the client certificate to provide authentication information. It is equivalent to the `EXTERNAL` SASL mechanism.

The following configuration enables authentication against the `default` realm, using both `BASIC` and `DIGEST` mechanisms:

.REST authentication configuration
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/rest_connector_authentication.xml[]
----

The `SPNEGO` mechanism also needs to indicate the Kerberos identity that will be used:

.REST authentication configuration for SPNEGO
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/rest_connector_authentication_spnego.xml[]
----
