= Single-Port

Single-Port is a special type of router connector which allows exposing multiple protocols over the same TCP port.
This approach is very convenient because it reduces the number of ports required by a server, with advantages in security, configuration and management.
Protocol switching is handled in three ways:

* *HTTP/1.1 Upgrade header*: initiate an HTTP/1.1 connection and send an `Upgrade: protocol` header where protocol is the name assigned to the desired endpoint.
* *TLS/ALPN*: protocol selection is performed based on the SNI specified by the client.
* *Hot Rod header detection*: if a Hot Rod endpoint is present in the router configuration, then any attempt to send a Hot Rod header will be detected and the protocol will be switched automatically.

NOTE: The initial implementation supports only HTTP/1.1, HTTP/2 and Hot Rod protocols. The Memcached protocol is not supported.

== Single-Port router

Internally, Single-Port is based on the same router component used to enable multi-tenancy, and therefore it shares the same configuration.

[source,xml]
----

<!-- TLS/ALPN negotiation -->
<router-connector name="router-ssl" single-port-socket-binding="rest-ssl">
    <single-port security-realm="SSLRealm1">
        <hotrod name="hotrod" />
        <rest name="rest" />
    </single-port>
</router-connector>
<!-- HTTP 1.1/Upgrade procedure -->
<router-connector name="router" single-port-socket-binding="rest">
    <single-port>
        <hotrod name="hotrod" />
        <rest name="rest" />
    </single-port>
</router-connector>

----

With the configuration above, the Single-Port Router will operate on `rest` and `rest-ssl` socket
bindings. The router named `router` should typically operate on port `8080` and will use HTTP/1.1 Upgrade
(also known as _cleartext upgrade_) procedure. The other router instance (called `router-ssl`) should typically
operate on port `8443` and will use TLS/ALPN.

=== Testing the Single-Port router

A tool such as `curl` can be used to access cache using both _cleartext upgrade_ or TLS/ALPN. Here's an example:

[source,bash]
----

curl -v -k --http2-prior-knowledge https://127.0.0.1:8443/rest/default/test

----

The `--http2-prior-knowledge` can be exchanged with `--http2` switch allowing to control how the switch procedure
is being done (via Plain-Text Upgrade or TLS/ALPN).

== Hot Rod

The single-port router has built-in automatic detection of Hot Rod messages which trigger a transparent "upgrade" to the
Hot Rod protocol. This means that no changes are required on the client side to connect to a single-port endpoint.
It also means that older clients will also be able to function seamlessly.

=== TLS/ALPN protocol selection

Another supported way to select the protocol is to use TLS/ALPN which uses the link:https://tools.ietf.org/html/rfc7301[Application-Layer Protocol Negotiation] spec.
This feature requires that you have configured your endpoint to enable TLS. If you are using JDK 9 or greater, ALPN is
supported out-of-the-box. However, if you are using JDK 8, you will need to use
https://netty.io/wiki/forked-tomcat-native.html[Netty's BoringSSL] library, which leverages native libraries to enable ALPN.

[source,xml]
----

<dependencyManagement>
      <dependency>
         <groupId>io.netty</groupId>
         <artifactId>netty-bom</artifactId>
         <!-- Pulled from Infinispan BOM -->
         <version>${version.netty}</version>
         <type>pom</type>
         <scope>import</scope>
      </dependency>
   </dependencies>
</dependencyManagement>

<dependency>
   <groupId>io.netty</groupId>
   <artifactId>netty-tcnative-boringssl-static</artifactId>
   <!-- The version is defined in Netty BOM -->
</dependency>

----

After adding the library, configure your trust store accordingly:

[source,java]
----

ConfigurationBuilder builder = new ConfigurationBuilder()
      .addServers("127.0.0.1:8443");

builder.security().ssl().enable()
      .trustStoreFileName("truststore.pkcs12")
      .trustStorePassword(DEFAULT_TRUSTSTORE_PASSWORD.toCharArray());

RemoteCacheManager remoteCacheManager = new RemoteCacheManager(builder.build());
RemoteCache<String, String> cache = remoteCacheManager.getCache("default"");

----
