= Spring Boot Starter for {brandname}
The {brandname} starter provides a set of managed transitive dependencies that include everything your Spring Boot project needs to seamlessly interact with {brandname} in one of two modes:

* Embedded Mode runs {brandname} inside your application.
* Remote Client/Server Mode connects your application to an {brandname} cluster.

[TIP]
====
The {brandname} Spring Boot starter gives you a convenient way to get started with Spring Boot but is optional. To use {brandname} with Spring Boot you can simply add the dependencies you want.
====

= Setting Up Your Project

To set up your project, add one of the following to your `pom.xml` file:

.Embedded Mode
[source,xml,options="nowrap",subs=attributes+]
----
include::dependencies_maven/sb_embedded.xml[]
----

.Remote Client/Server Mode
[source,xml,options="nowrap",subs=attributes+]
----
include::dependencies_maven/sb_remote.xml[]
----

= Enforcing {brandname} Versions

This starter uses a high-level API to ensure compatibility between major versions of {brandname}. However you can enforce a specific version of {brandname} with the `infinispan-bom` module.

Add `infinispan-bom` to your `pom.xml` file before the starter dependencies, as follows:

[source,xml,options="nowrap",subs=attributes+]
----
include::dependencies_maven/sb_bom.xml[]
----

= Running in Embedded Mode

. Add `infinispan-spring-boot-starter-embedded` to your project's classpath to enable Embedded mode.
+
This starter operates in Remote Client/Server mode with `infinispan-spring-boot-starter-remote` on the classpath by default.
+
. Use the Spring `@Autowired` annotation to include an `EmbeddedCacheManager` bean in your Java configuration classes, as in the following example:
+
[source,java,options="nowrap"]
----
include::code_examples/AutowiredEmbeddedCacheManager.java[]
----
+
You are now ready to use {brandname} in Embedded Mode. Here is a simple example:
+
[source,java,options="nowrap"]
----
include::code_examples/CacheManagerGetCache.java[]
----

== Customizing the Cache Manager

Customize the cache manager with the following configuration beans:

* `InfinispanGlobalConfigurer`
* `InfinispanCacheConfigurer`
* `Configuration`
* `InfinispanConfigurationCustomizer`
* `InfinispanGlobalConfigurationCustomizer`
+
[NOTE]
====
You can create one `InfinispanGlobalConfigurer` bean only. However you can create multiple configurations with the other beans.
====

.InfinispanCacheConfigurer Bean
[source,java,options="nowrap"]
----
include::code_examples/InfinispanCacheConfigurer.java[]
----

.Configuration Bean
Link the bean name to the cache that it configures, as follows:
[source,java,options="nowrap"]
----
include::code_examples/CacheConfigurationBean.java[]
----

.Customizer Beans
[source,java,options="nowrap"]
----
include::code_examples/ConfigurationCustomizerBean.java[]
----

== Enabling Spring Cache Support

Add the `@EnableCaching` annotation to your application to enable Spring Cache support.

When this starter detects the `EmbeddedCacheManager` bean, it instantiates a new `SpringEmbeddedCacheManager`, which provides an implementation of
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html[Spring Cache].

== Configuration Properties

Include the following properties in the `application.properties` or `application.yml` file to configure your project:

[source,yaml,options="nowrap"]
----
infinispan.embedded.enabled = # Enables Data Grid capabilities in your application. The value is true (default) or false.
infinispan.embedded.machineId = # Sets the Spring state machine ID.
infinispan.embedded.clusterName = # Sets the name of the Data Grid cluster.
infinispan.embedded.configXml = # Specifies a XML configuration file.
----

[NOTE]
====
If you specify a {brandname} configuration with the `infinispan.embedded.configXml` property, it takes priority over the global configuration bean or any configuration customizer.
====

= Running in Remote Client/Server Mode

. Provide the location for the {brandname} server so the starter can create the `RemoteCacheManager` bean.
+
This starter first attempts to locate the server from the `hotrod-client.properties` file on the classpath. If not found, the starter then attempts to locate the server from your `application.properties` file.
+
* `hotrod-client.properties`:
+
[source,text,options=nowrap]
----
infinispan.client.hotrod.server_list=127.0.0.1:6667
----
+
* `application.properties`:
+
[source,text,options=nowrap]
----
infinispan.remote.server-list=127.0.0.1:11222
----
+
. Use the Spring `@Autowired` annotation to include your own custom cache manager class in your application:
+
[source,java,options="nowrap"]
----
include::code_examples/AutowiredRemoteCacheManager.java[]
----

== Customizing the Cache Manager

Customize the cache manager with the following configuration beans:

* `InfinispanRemoteConfigurer`
* `Configuration`
* `InfinispanRemoteCacheCustomizer`
+
[NOTE]
====
You can create one `InfinispanRemoteConfigurer` bean only. However you can create multiple configurations with the other beans.
====

.InfinispanRemoteConfigurer Bean
[source,java,options="nowrap"]
----
include::code_examples/InfinispanRemoteConfigurer.java[]
----

.Configuration Bean
[source,java,options="nowrap"]
----
include::code_examples/HotRodConfigurationBean.java[]
----

.InfinispanRemoteCacheCustomizer Bean
[source,java,options="nowrap"]
----
include::code_examples/InfinispanRemoteCacheCustomizer.java[]
----

[TIP]
====
Use the `@Ordered` annotation to apply customizers in a specific order.
====

== Enabling Spring Cache Support

Add the `@EnableCaching` annotation to your application to enable Spring Cache support.

When the {brandname} starter detects the `RemoteCacheManager` bean, it instantiates a new `SpringRemoteCacheManager`, which provides an implementation of
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html[Spring Cache].

== Enabling Spring Session Support

{brandname} Spring Session support is built on
`SpringRemoteCacheManager` and `SpringEmbeddedCacheManager`. This starter produces those beans by default.

To use Spring Session in your project, do the following:

. Add this starter to your project.
. Add Spring Session to the classpath.
. Add the following annotations to your configuration:
- `@EnableCaching`
- `@EnableInfinispanRemoteHttpSession`
- `@EnableInfinispanEmbeddedHttpSession`

== Configuration Properties

Include the following properties in the `application.properties` or `application.yml` file to configure your project:

[source,yaml,options="nowrap"]
----
infinispan.remote.clientProperties = # Specifies a custom filename for Hot Rod client properties.
infinispan.remote.enabled = # Enables Data Grid capabilities in your application. The value is true (default) or false.
infinispan.remote.serverList = # Defines a comma-separated list of Data Grid  servers in this format: `host1[:port],host2[:port]`.
infinispan.remote.socketTimeout = # Sets a timeout value, in milliseconds, for socket connections.
infinispan.remote.connectTimeout = # Sets a timeout value for initializing connections with Data Grid servers.
infinispan.remote.maxRetries = # Sets the maximum number of attempts to connect to Data Grid servers.
----

= Exposing {brandname} Statistics

{brandname} supports the Spring Boot Actuator to expose cache statistics as metrics.

To use the Actuator, add the following to your `pom.xml` file:

[source,xml,options="nowrap",subs=attributes+]
----
include::dependencies_maven/sb_actuator.xml[]
----

You must then activate statistics for the appropriate cache instances, either programmatically or declaratively.

.Programmatically
[source,java,options="nowrap"]
----
include::code_examples/EnableJmxStatisticsSpringBoot.java[]
----

.Declaratively
[source,xml,options="nowrap",subs=attributes+]
----
include::config_examples/jmx_statistics.xml[]
----

The Spring Boot Actuator registry binds cache instances when your application starts. If you create caches dynamically, you should use the `CacheMetricsRegistrar` bean to bind caches to the Actuator registry, as follows:

[source,java,options="nowrap"]
----
include::code_examples/CacheMetricsRegistrar.java[]
----
