apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: infinispan-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - daemonsets
      - replicasets
      - statefulsets
      - statefulsets/finalizers
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - infinispan.org
    resources:
      - '*'
    verbs:
      - '*'

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: infinispan-operator

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infinispan-operator
subjects:
  - kind: ServiceAccount
    name: infinispan-operator
roleRef:
  kind: Role
  name: infinispan-operator
  apiGroup: rbac.authorization.k8s.io
