[[sid-68355087]]

==  Listeners and Notifications

Infinispan offers a listener API, where clients can register for and get notified when events take place.  This annotation-driven API applies to 2 different levels: cache level events and cache manager level events.

 Events trigger a notification which are dispatched to listeners.   Listeners are simple link:$$http://en.wikipedia.org/wiki/Plain_Old_Java_Object$$[POJO] s annotated with link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/notifications/Listener.html$$[@Listener] and registered using the methods defined in the link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/notifications/Listenable.html$$[Listenable] interface. 


----
Both Cache and CacheManager implement Listenable, which means you can attach listeners to either a cache or a cache manager, to receive either cache-level or cache manager-level notifications.

----

 For example, the following class defines a listener to print out some information every time a new entry is added to the cache: 


----
@Listener
public class PrintWhenAdded {

  @CacheEntryCreated
  public void print(CacheEntryCreatedEvent event) {
    System.out.println("New entry " + event.getKey() + " created in the cache");
  }

}

----

 For more comprehensive examples, please see the link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/notifications/Listener.html$$[Javadocs for @Listener] . 

[[sid-68355087_ListenersandNotifications-Cachelevelnotifications]]


=== Cache-level notifications

Cache-level events occur on a per-cache basis, and is global and cluster-wide.  Examples of cache-level events are entries being added, removed, modified, etc.  These events trigger notifications to listeners registered to a specific cache.

 Please see the link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/notifications/cachelistener/annotation/package-summary.html$$[Javadocs on the org.infinispan.notifications.cachelistener.annotation package] for a comprehensive list of all cache-level notifications, and their respective method-level annotations. 


----
NOTE: In Infinispan 5.0, additional events were added.  Please refer to the <a href="http://docs.jboss.org/infinispan/5.0/apidocs/org/infinispan/notifications/cachelistener/annotation/package-summary.html">Javadocs on the org.infinispan.notifications.cachelistener.annotation package</a> for Infinispan 5.0 for the list of cache-level notifications available in Infinispan 5.0.

----

[[sid-68355087_ListenersandNotifications-Cachemanagerlevelnotifications]]


=== Cache manager-level notifications

Cache manager-level events occur on a cache manager.  These too are global and  cluster-wide, but involve events that affect all caches created by a single cache manager.  Examples of cache manager-level events are nodes joining or leaving a cluster, or caches starting or stopping.

 Please see the link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/notifications/cachemanagerlistener/annotation/package-summary.html$$[Javadocs  on the org.infinispan.notifications.cachemanagerlistener.annotation package] for a comprehensive list of all cache manager-level notifications,  and their respective method-level annotations. 

[[sid-68355087_ListenersandNotifications-Synchronicity]]


=== Synchronicity

 By default, all notifications are dispatched in the same thread that generates the event.  This means that you _must_ write your listener such that it does not block or do anything that takes too long, as it would prevent the thread from progressing.  Alternatively, you could annotate your listener as _asynchronous_ , in which case a separate thread pool will be used to dispatch the notification and prevent blocking the event originating thread.  To do this, simply annotate your listener such: 


----
@Listener (sync = false)
public class MyAsyncListener { .... }

----

[[sid-68355087_ListenersandNotifications-Asynchronousthreadpool]]


==== Asynchronous thread pool

 To tune the thread pool used to dispatch such asynchronous notifications, use the link:$$http://docs.jboss.org/infinispan/4.0/apidocs/config.html#ce_global_asyncListenerExecutor$$[&lt;asyncListenerExecutor /&gt;] XML element in your configuration file. 

[[sid-68355087_ListenersandNotifications-ListenersonRemoteCacheManager]]


=== Listeners on RemoteCacheManager

 At the moment there is no support for registering listeners for the link:$$http://docs.jboss.org/infinispan/4.1/apidocs/org/infinispan/client/hotrod/RemoteCacheManager.html$$[RemoteCacheManager] . Whenever calling one of the add/remove/getListener methods on the link:$$http://docs.jboss.org/infinispan/4.1/apidocs/org/infinispan/client/hotrod/RemoteCacheManager.html$$[RemoteCacheManager] an UnsupportedOperationException will be thrown. There are plans to support remote listeners in future versions; in order to be notified when this feature will be added you can watch/vote for link:$$https://issues.jboss.org/browse/ISPN-374$$[ISPN-374] . 

