[[sid-68355117]]

==  Data Versioning

[[sid-68355117_DataVersioning-Overview]]


=== Overview

Infinispan will offer three forms of data versioning, including simple, partition aware and external.  Each case is described in detail below.

[[sid-68355117_DataVersioning-Simpleversioning]]


==== Simple versioning

The purpose of simple versioning is to provide a reliable mechanism of write skew checks when using optimistic transactions, REPEATABLE_READ and a clustered cache.  Write skew checks are performed at prepare-time to ensure a concurrent transaction hasn't modified an entry while it was read and potentially updated based on the value read.

When operating in LOCAL mode, write skew checks rely on Java object references to compare differences and this is adequate to provide a reliable write-skew check, however this technique is useless in a cluster and a more reliable form of versioning is necessary to provide reliable write skew checks.

 Simple versioning is an implementation of the proposed EntryVersion interface, backed by a long that is incremented each time the entry is updated. 

[[sid-68355117_DataVersioning-Partitionawareversioning]]


==== Partition-aware versioning

 This versioning scheme makes use of link:$$http://en.wikipedia.org/wiki/Vector_clock$$[vector clocks] to provide a network partition resilient form of versioning. 

Unlike simple versioning, which is maintained per entry, a vector clock's node counter is maintained per-node.

[[sid-68355117_DataVersioning-Externalversioning]]


==== External versioning

This scheme is used to encapsulate an external source of data versioning within Infinispan, such as when using Infinispan with Hibernate which in turn gets it's data version information directly from a database.

 In this scheme, a mechanism to pass in the version becomes necessary, and overloaded versions of put() and putForExternalRead() will be provided in AdvancedCache to take in an external data version.  This is then stored on the InvocationContext and applied to the entry at commit time. 

Write skew checks cannot and will not be performed in the case of external data versioning.

[[sid-68355117_DataVersioning-Tombstones]]


==== Tombstones

 To deal with deletions of entries, tombstones will be maintained as null entries that have been deleted, so that version information of the deleted entry can be maintained and write skews can still be detected.  However this is an expensive thing to do, and as such, is a configuration option, disabled by default. Further, tombstones will follow a strict lifespan and will be cleared from the system after a specific amount of time. 

[[sid-68355117_DataVersioning-Configuration]]


=== Configuration

 By default versioning will be _disabled_ .  This will mean write skew checks when using transactions and _$$REPEATABLE_READ$$_ as an isolation level will be unreliable when used in a cluster.  Note that this doesn't affect single-node, LOCAL mode usage. 

[[sid-68355117_DataVersioning-ViaXML]]


==== Via XML


----

<versioning enabled="false" type="SIMPLE|PARTITION_AWARE|EXTERNAL" useTombstones="false" tombstoneLifespan="60000"/>

----

[[sid-68355117_DataVersioning-ViatheprogrammaticAPI]]


==== Via the programmatic API


----

fluent().versioning().type(SIMPLE).useTombstones(true).tombstoneLifespan(1, TimeUnit.MINUTES);


----

