[[sid-68355051]]

==  Configuration Migration Tools

Infinispan has a number of scripts for importing configurations from other cache products. Currently we have scripts to import configurations from:


* JBoss Cache 3.x


* EHCache 1.x


* Coherence 3.x

 JBoss Cache 3.x itself supports configuration link:$$http://jbosscache.blogspot.com/2008/07/configuration-changes-in-jboss-cache-3.html$$[migration] from previous (2.x) versions, so JBoss Cache 2.x configurations can be migrated indirectly. 


----
If you wish to help write conversion tools for other caching systems, please contact <a href="https://lists.jboss.org/mailman/listinfo/infinispan-dev">infinispan-dev</a>.  
----

There is a single scripts for importing configurations: ${INFINISPAN_HOME}/bin/importConfig.sh and an equivalent .BAT script for Windows. Just run it and you should get a help message to assist you with the import:


----
C:\infinispan\bin> importConfig.bat
Missing 'source', cannot proceed
Usage:
importConfig [-source <the file to be transformed>]
[-destination <where to store resulting XML>]
[-type <the type of the source, possible values being: [JBossCache3x, Ehcache1x, Coherence35x] >]

C:\infinispan\bin>

----

Here is how a JBoss Cache 3.x configuration file is imported:


----
C:\infinispan\bin>importConfig.bat -source in\jbosscache_all.xml -destination out.xml -type JBossCache3x

WARNING! Preload elements cannot be automatically transformed, please do it manually!

WARNING! Please configure cache loader props manually!

WARNING! Singleton store was changed and needs to be configured manually!

IMPORTANT: Please take a look at the generated file 
for (possible) TODOs about the elements that couldn't be converted automatically!

---

New configuration file [out.xml] successfully created.

---

C:\infinispan\bin>

----

 Please read all warning messages _carefully_ and inspect the generated XML for potential TODO statements that indicate the need for manual intervention. In the case of JBoss Cache 3.x this would usually have to do with custom extensions, such as custom CacheLoaders that cannot be automatically migrated. 

For EHCache and Coherence these may also contain suggestions and warnings for configuration options that may not have direct equivalents in Infinispan.

