[[sid-68355094]]

==  Write-Through And Write-Behind Caching

[[sid-68355094_Write-ThroughAndWrite-BehindCaching-Introduction]]


=== Introduction

Infinispan can optionally be configured with one or several cache stores allowing it to store data in a persistent location such as shared JDBC database, a local filesystem...etc. Infinispan can handle updates to the cache store in two different ways:


* Write-Through (Synchronous)


* Write-Behind (Asynchronous)

[[sid-68355094_Write-ThroughAndWrite-BehindCaching-WriteThrough%28Synchronous%29]]


=== Write-Through (Synchronous)

In this mode, which is supported in version 4.0, when clients update a cache entry, i.e. via a Cache.put() invocation, the call will not return until Infinispan has gone to the underlying cache store and has updated it. Normally, this means that updates to the cache store are done within the boundaries of the client thread.

The main advantage of this mode is that the cache store is updated at the same time as the cache, hence the cache store is consistent with the cache contents. On the other hand, using this mode reduces performance because the latency of having to access and update the cache store directly impacts the duration of the cache operation.

Configuring a write-through or synchronous cache store does not require any particular configuration option. By default, unless marked explicitly as write-behind or asynchronous, all cache stores are write-through or synchronous. Please find below a sample configuration file of a write-through unshared local file cache store:


----
<?xml version="1.0" encoding="UTF-8"?>
<infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns="urn:infinispan:config:5.0">
  <global />
  <default />
  <namedCache name="persistentCache">
    <loaders shared="false">
      <loader 
          class="org.infinispan.loaders.file.FileCacheStore" 
          fetchPersistentState="true" ignoreModifications="false"
          purgeOnStartup="false">
        <properties>
          <property name="location" value="${java.io.tmpdir}" />
        </properties>
      </loader>
    </loaders>
  </namedCache>
</infinispan>

----

[[sid-68355094_Write-ThroughAndWrite-BehindCaching-WriteBehind%28Asynchronous%29]]


=== Write-Behind (Asynchronous)

In this mode, updates to the cache are asynchronously written to the cache store. Normally, this means that updates to the cache store are done by a separate thread to the client thread interacting with the cache.

One of the major advantages of this mode is that the performance of a cache operation does not get affected by the update of the underlying store. On the other hand, since the update happens asynchronously, there's a time window during the which the cache store can contain stale data compared to the cache. Even within write-behind, there are different strategies that can be used to store data:

[[sid-68355094_Write-ThroughAndWrite-BehindCaching-UnscheduledWriteBehindStrategy]]


=== Unscheduled Write-Behind Strategy

In this mode, which is supported in version 4.0, Infinispan tries to store changes as quickly as possible by taking the pending changes and applying them in paralel. Normally, this means that there are several threads waiting for modifications to occur and once they're available, they apply them to underlying cache store.

This strategy is suited for cache stores with low latency and cheap operation cost. One such example would a local unshared file based cache store, where the cache store is local to the cache itself. With this strategy, the window of inconsistency between the contents of the cache and the cache store are reduced to the lowest possible time. Please find below a sample configuration file of this strategy:


----
<?xml version="1.0" encoding="UTF-8"?>
<infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns="urn:infinispan:config:5.0">
  <global />
  <default />
  <namedCache name="persistentCache">
    <loaders shared="false">
      <loader 
          class="org.infinispan.loaders.file.FileCacheStore" 
          fetchPersistentState="true" ignoreModifications="false"
          purgeOnStartup="false">
        <properties>
          <property name="location" value="${java.io.tmpdir}" />
        </properties>
        <!-- write-behind configuration starts here -->
        <async enabled="true" threadPoolSize="10" />
        <!-- write-behind configuration ends here -->
      </loader>
    </loaders>
  </namedCache>
</infinispan>

----

[[sid-68355094_Write-ThroughAndWrite-BehindCaching-ScheduledWriteBehindStrategy]]


=== Scheduled Write-Behind Strategy

 First of all, please note that this strategy is not included in version 4.0 but it will be implemented at a later stage. link:$$https://jira.jboss.org/jira/browse/ISPN-328$$[ISPN-328] has been created to track this feature request. If you want it implemented, please link:$$https://jira.jboss.org/jira/secure/ViewIssue.jspa?id=12402022&amp;vote=true$$[vote for it] and don't forget to link:$$https://jira.jboss.org/jira/secure/ViewIssue.jspa?id=12402022&amp;watch=true$$[watch it] to be notified of any changes. The following explanation refers to how we envision it to work. 

In this mode, Infinispan would periodically store changes to the underlying cache store. The periodicity could be defined in seconds, minutes, days...etc.

Since this strategy is oriented at cache stores with high latency or expensive operation cost, it makes sense to coalesce changes, so that if there are multiple operations queued on the same key, only the latest value is applied to cache store. With this strategy, the window of inconsistency between the contents of the cache and the cache store depends on the delay or periodicity configured. The higher the periodicity, the higher the chance of inconsistency.

