[[sid-68355105]]

==  Multiple Tiers of Caches

[[sid-68355105_MultipleTiersofCaches-Introduction]]


=== Introduction

 The introduction of link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=9470083$$[HotRod] protocol and link:$$http://community.jboss.org/docs/DOC-14893?uniqueTitle=false#Remote_cache_loader$$[RemoteCacheLoader] opened the way for a set of new architectures in Infinispan, where layers of caches can exists and interact. This article takes a look at such an layered architecture. 

[[sid-68355105_MultipleTiersofCaches-Buildingblocks]]


=== Building blocks

 link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=9470083$$[HotRod] is a binary protocol defined for exposing an Infinispan cluster as an caching server to multiple platforms. It has support for load balancing and smart routing. 

 link:$$http://community.jboss.org/docs/DOC-14893?uniqueTitle=false#Remote_cache_loader$$[RemoteCacheLoader] is a cache loader that knows how to read/store data in a remote infinispan cluster. For that it makes use of the java hotrod client. 

[[sid-68355105_MultipleTiersofCaches-Samplearchitecture%2Fnearcaching]]


=== Sample architecture/near caching

 
.TODO InformalFigure image title empty
image::[]

 

 The diagram above shows an Infinispan server cluster running 3 hotrod servers. This cluster is accessed remotely, through HotRod, by another infinispan cluster:  client cluster (upper part of the image). All the nodes in the server cluster are configured to run HotRod servers, so requests from remote loader are being balanced between them. The client cluster is configured with invalidation as cluster mode and a <<sid-68355053,RemoteCacheLoader>> to acess data stored in the server cluster. Application data is held on the server cluster which runs in DIST mode for scalability. 

 In this deployment the client code, running in same address space with the client cluster,  holds all its data in the server cluster. Client cluster acts as an _near-cache_ for frequently accessed entries. 

[[sid-68355105_MultipleTiersofCaches-Wanttoknowmore%3F]]


=== Want to know more?

 On the link:$$http://community.jboss.org/infinispan$$[documentation  main page] : 


* cache loaders are described in the "Cache loaders" section


* Hotrod's specification, server and client in the "Hot Rod" section

