[[sid-68355101]]

==  Local mode cache

 _Introduction_ 

 Even though Infinispan's biggest potential is as distributed, in-memory data grid platform, one aspect of it often gets overlooked - it can be used as a standalone cache node. But why would anyone use Infinispan over, say, a link:$$http://java.sun.com/javase/6/docs/api/java/util/concurrent/ConcurrentHashMap.html$$[ConcurrentHashMap] ? Here are some reasons: _$$__$$_ 


*  _Eviction._ Built-in eviction ensures you don't run out of memory. 


*  _Write-through and write-behind caching._ Going beyond memory and onto disk (or any other pluggable link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/loaders/CacheStore.html$$[CacheStore] ) means that your state survives restarts, and preloaded hot caches can be configured. 


*  _JTA support and XA compliance._ Participate in ongoing transactions with any link:$$http://java.sun.com/javaee/technologies/jta/index.jsp$$[JTA] -compliant transaction manager. 


*  _MVCC-based concurrency._ Highly optimized for fast, non-blocking readers. 


*  _Manageability._ link:$$http://docs.jboss.org/infinispan/4.0/apidocs/jmxComponents.html$$[Simple JMX] or rich GUI management console via link:$$http://community.jboss.org/docs/DOC-13721$$[JOPR] , you have a choice. 


*  _Not just for the JVM._ link:$$http://community.jboss.org/docs/DOC-14095$$[RESTful API] , and upcoming link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3736765$$[client/server modules] speaking Memcached and link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=9470083$$[HotRod] protocols help non-JVM platforms use Infinispan. 


*  _Cluster-ready._ Should the need arise. _$$__$$_ So how do you get started with Infinispan in local mode? The simplest configuration file containing just 


----
<infinispan/>

----

 is enough to get you started, or you can create DefaultCacheManager with _no_ - _argument_ constructor. Either approach creates local default cache. 

 All the features above are exposed via an easy-to-use link:$$http://docs.jboss.org/infinispan/4.0/apidocs/org/infinispan/Cache.html$$[Cache] interface, which extends link:$$http://java.sun.com/javase/6/docs/api/java/util/concurrent/ConcurrentMap.html$$[ConcurrentMap] and is compatible with many other cache systems. Infinispan even ships with link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737098$$[migration tools] to help you move off other cache solutions onto Infinispan, whether you need a cache to store data retrieved remotely or simply as a link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=3737110$$[2nd level cache for Hibernate] . 

 _Performance_ 

 In the process of testing and tuning Infinispan on very large clusters, we have started to put together a link:$$http://cachebenchfwk.sourceforge.net/$$[benchmarking framework] . As a part of this framework, we have the ability to measure cache performance in standalone, local mode. We compared Infinispan 4.0 in local mode against the latest JBoss Cache release (3.2.2.GA) and EHCache (1.7.2). Some background on the tests: 


*  Used a latest snapshot of the link:$$http://cachebenchfwk.sourceforge.net/$$[CacheBenchFwk] 


*  Run on a link:$$http://www.redhat.com/rhel/$$[RHEL] 5 server with 4 Intel Xeon cores, 4GB of RAM 


* Sun JDK 1.6.0_18, with -Xms1g -Xmx1g


* Test run on a single node, with 25 concurrent threads, using randomly generated Strings as keys and values and a 1kb payload for each entry, with a 80/20 read/write ratio.


* Performance measured in transactions per second (higher = better).

 
.TODO InformalFigure image title empty
image::[]

 

 
.TODO InformalFigure image title empty
image::[]

 In summary, what we have here is that when run in local mode, Infinispan is a high-performance standalone caching engine which offers a rich set of features while still being trivially simple to configure and use. 

