[[eviction_anchor]]
==  Eviction and Data Container

{brandname} supports eviction of entries, such that you do not run out of memory.
Eviction is typically used in conjunction with a cache store, so that entries are
not permanently lost when evicted, since eviction only removes entries from
memory and not from cache stores or the rest of the cluster.

{brandname} supports storing data in a few different formats.  Data can be
stored as the object iself, binary as a byte[], and off-heap which stores the
byte[] in native memory.

TIP:  Passivation is also a popular option when using eviction, so that only a
single copy of an entry is maintained - either in memory or in a cache store,
but not both. The main benefit of using passivation over a regular cache store
is that updates to entries which exist in memory are cheaper since the update
doesn't need to be made to the cache store as well.

IMPORTANT: Eviction occurs on a _local_ basis, and is not cluster-wide.  Each
node runs an eviction thread to analyse the contents of its in-memory container
and decide what to evict. Eviction does not take into account the amount of free
memory in the JVM as threshold to  starts evicting entries. You have to set `size`
attribute of the eviction element to be greater than zero in order for eviction
to be turned on. If size is too large you can run out of memory. The `size`
attribute will probably take some tuning in each use case.

=== Enabling Eviction

Eviction is configured by adding the
link:http://docs.jboss.org/infinispan/{infinispanversion}/configdocs/infinispan-config-{infinispanversion}.html[`<memory />`]
element to your `<*-cache />` configuration sections or using
link:{javadocroot}/org/infinispan/configuration/cache/MemoryConfigurationBuilder.html[MemoryConfigurationBuilder]
API programmatic approach.

All cache entry are evicted by piggybacking on user threads that are hitting the cache.

==== Eviction strategy

Strategies control how the eviction is handled.

The possible choices are

.`NONE`
Eviction is not enabled and it is assumed that the user will not invoke evict directly
on the cache. If passivation is enabled this will cause aa warning message to be
emitted. This is the default strategy.

.`MANUAL`
This strategy is just like <b>NONE</b> except that it asssumes the user will be
invoking evict directly. This way if passivation is enabled no warning message
is logged.

.`REMOVE`
This strategy will actually evict "old" entries to make room for incoming ones.

Eviction is handled by link:https://github.com/ben-manes/caffeine[Caffeine] utilizing
the TinyLFU algorithm with an additional admission window.  This was chosen as
provides high hit rate while also requiring low memory overhead.  This provides a
better hit ratio than LRU while also requiring less memory than LIRS.

.`EXCEPTION`
This strategy actually prevents new entries from being created by throwing
a `ContainerFullException`. This strategy only works with transactional caches
that always run with 2 phase commit, that is no 1 phase commit or synchronization
optimizations allowed.

==== Eviction types

Eviction type applies only when the size is set to something greater than 0.
The eviction type below determines when the container will decide to remove
entries.

.`COUNT`
This type of eviction will remove entries based on how many there are in the
cache.  Once the count of entries has grown larger than the `size` then an
entry will be removed to make room.

.`MEMORY`
This type of eviction will estimate how much each entry will take up in memory
and will remove an entry when the total size of all entries is larger than
the configured `size`.  This type does not work with `OBJECT` storage type
below.

==== Storage type

{brandname} allows the user to configure in what form their data is stored.  Each
form supports the same features of {brandname}, however eviction can be limited
for some forms.  There are currently three storage formats that {brandname}
provides, they are:

.`OBJECT`
Stores the keys and values as objects in the Java heap  Only `COUNT` eviction
type is supported.

.`BINARY`
Stores the keys and values as a byte[] in the Java heap.  This will use the configured
marshaller for the cache if there is one.  Both `COUNT` and
`MEMORY` eviction types are supported.

.`OFF-HEAP`
Stores the keys and values in native memory outside of the
Java heap as bytes.  The configured marshaller will be used if the cache has one.
Both `COUNT` and `MEMORY` eviction types are supported.

WARNING: Both `BINARY` and `OFF-HEAP` violate equality and hashCode that they are
dictated by the resulting byte[] they generate instead of the object instance.

==== More defaults

By default when no `<memory />` element is specified, no eviction takes place,
`OBJECT` storage type is used, and a strategy of `NONE` is assumed.

In case there is an memory element, this table describes the behaviour of eviction
based on information provided in the xml configuration ("-" in Supplied size or
Supplied strategy column means that the attribute wasn't supplied)

[options="header"]
|===============
|Supplied size|Example|Eviction behaviour
|-| `<memory />` |no eviction as an object
|-| `<memory strategy="MANUAL">` |no eviction as an object and won't log warning if passivation is enabled
|&gt; 0| `<memory> <object size="100" /> </memory>` |eviction takes place and stored as objects
|&gt; 0| `<memory> <binary size="100" eviction="MEMORY"/> </memory>` |eviction takes place and stored as a binary removing to make sure memory doens't go higher than 100
|&gt; 0| `<memory> <off-heap size="100" /> </memory>` |eviction takes place and stored in off-heap
|&gt; 0| `<memory> <off-heap size="100" strategy="EXCEPTION" /> </memory>` |entries are stored in off-heap and if 100 entries are in container exceptions will be thrown for additional
|0| `<memory> <object size="0" /> </memory>` | no eviction
|&lt; 0| `<memory> <object size="-1" /> </memory>` | no eviction

|===============

=== Expiration

Similar to, but unlike eviction, is expiration. Expiration allows you to attach
lifespan and/or maximum idle times to entries. Entries that exceed these times
are treated as invalid and are removed. When removed expired entries are not
passivated like evicted entries (if passivation is turned on).

TIP: Unlike eviction, expired entries are removed globally - from memory, cache
stores, and cluster-wide.

By default entries created are immortal and do not have a lifespan or maximum
idle time.  Using the cache API, mortal entries can be created with lifespans
and/or maximum idle times.  Further, default lifespans and/or maximum idle
times can be configured by adding the
link:http://docs.jboss.org/infinispan/{infinispanversion}/configdocs/infinispan-config-{infinispanversion}.html[&lt;expiration /&gt;]
element to your `<*-cache />`  configuration sections.

When an entry expires it will reside in the data container or cache store
until it is accessed again by a user request.  There is also an optional
expiration reaper that can run at a given configurable interval of
milliseconds which will check for expired entries and remove them. Expiration reaper
is always enabled when a cache store is present. It is highly recommended to always enable
the reaper when using max idle in a clustered cache.

==== Difference between Eviction and Expiration

Both Eviction and Expiration are means of cleaning the cache of unused entries
and thus guarding the heap against OutOfMemory exceptions, so now a brief
explanation of the difference.

With _eviction_ you set _maximal number of entries_ you want to keep in the cache
and if this limit is exceeded, some candidates are found to be removed according
to a choosen _eviction strategy_ (LRU, LIRS, etc...). Eviction can be setup to
work with passivation (evicting to a cache store).

With _expiration_ you set _time criteria_ for entries, _how long you want to keep them_
in cache. Either you set maximum _lifespan_ of the entry - time it is allowed to
stay in the cache or _maximum idle time_ , time it's allowed to be untouched
(no operation performed with given key).

===  Expiration details

.  _Expiration_ is a top-level construct, represented in the configuration as well as in the cache API.
.  While eviction is _local to each cache instance_ , expiration is _cluster-wide_ .  Expiration lifespans and maxIdle values are replicated along with the cache entry.
.  Max idle requires additional network messages to work in a cluster.  As such using maxIdle in a clustered cache will cause some operations to be slower at times.
.  Expiration lifespan and maxIdle are also persisted in CacheStores, so this information survives eviction/passivation.


==== Max Idle Details

Max idle expiration occurs when an entry has not been accessed within a given time frame. This poses a more interesting problem than lifespan, which is very simple. Thus this type of expiration behaves slightly different in a local versus cluster cache.

===== Local Max Idle

Max idle is pretty straightforward in a non clustered cache. It removes expired entries when accessed directly (ie. Cache.get), also removes expired entries entries when iterated upon (ie. Cache.size) or via expiration reaper.

===== Cluster Max Idle

Max idle in a cluster is quite a bit more complicated. Since each node can have a different access time, an entry is not removed until all owners of said entry say it hasn't been accessed in the given amount of time.

This check is done when a given node finds an entry has expired via maxIdle. It then will ask all the other owners what their last access time was (if it hasn't expired). If all owners say that the entry has expired, then it will not be returned to the user and removed based on the operation.

WARN: Clustered caches should always enable reaper when using max idle expiration due to some limitations listed in the section below.

When using max idle, it is important to keep the following points in mind:

. A Cache.get in a clustered cache will return the "expired" entry if at least one owner finds that this entry is not expired. The last access time for the given entry will be updated to the current time.
. When an entry is found to have expired due to max idle in the expiration reaper, instead of updating the last access time to current time, it will update all nodes to the most recent access of all owners.
. Iteration in a clustered cache *will* return entries that this node thinks are expired via max idle. This is to ensure performance as no remote invocations are done. The entry is not refreshed and may be removed by the reaper or get access.
. A clustered transactional cache does *NOT* remove entries expired via max idle on a get. These entries are only removed via reaper. This is prevented as doing so can cause deadlocking.

WARN: Care should be used when utilizing max idle expiration and exception based eviction since expired entries that aren't removed still will count towards container sizing

INFO: Entries transferred via state transfer will be created on the new node with a last access time equal to the current time, essentially refreshing any of these entries

==== Configuration

Eviction and Expiration may be configured using the programmatic or declarative XML configuration. This configuration is on a per-cache basis. Valid eviction/expiration-related configuration elements are:

[source,xml]
----
<!-- Eviction -->
<memory>
   <object size="2000"/>
</memory>
<!-- Expiration -->
<expiration lifespan="1000" max-idle="500" interval="1000" />

----

Programmatically, the same would be defined using:

[source,java]
----
Configuration c = new ConfigurationBuilder()
               .memory().size(2000)
               .expiration().wakeUpInterval(5000l).lifespan(1000l).maxIdle(500l)
               .build();

----

==== Memory Based Eviction Configuration

Memory based eviction may require some additional configuration options if you
are using your own custom types (as {brandname} is normally used).  In this case
{brandname} cannot estimate the memory usage of your classes and as such you are
required to use `storeAsBinary` when memory based eviction is used.

[source,xml]
----
<!-- Enable memory based eviction with 1 GB/>
<memory>
   <binary size="1000000000" eviction="MEMORY"/>
</memory>
----

[source,java]
----
Configuration c = new ConfigurationBuilder()
               .memory()
               .storageType(StorageType.BINARY)
               .evictionType(EvictionType.MEMORY)
               .size(1_000_000_000)
               .build();
----

==== Default values

Eviction is disabled by default. Default values are used:

* size: -1 is used if not specified, which means unlimited entries.
* 0 means no entries, and the eviction thread will strive to keep the cache empty.

Expiration lifespan and maxIdle both default to -1, which means that entries will be created immortal by default. This can be overridden per entry with the API.

==== Using expiration

Expiration allows you to set either a lifespan or a maximum idle time on each key/value pair stored in the cache.  This can either be set cache-wide using the configuration, as described above, or it can be defined per-key/value pair using the Cache interface.  Any values defined per key/value pair overrides the cache-wide default for the specific entry in question.

For example, assume the following configuration:

[source,xml]
----
<expiration lifespan="1000" />

----

[source,java]
----
// this entry will expire in 1000 millis
cache.put("pinot noir", pinotNoirPrice);

// this entry will expire in 2000 millis
cache.put("chardonnay", chardonnayPrice, 2, TimeUnit.SECONDS);

// this entry will expire 1000 millis after it is last accessed
cache.put("pinot grigio", pinotGrigioPrice, -1,
          TimeUnit.SECONDS, 1, TimeUnit.SECONDS);

// this entry will expire 1000 millis after it is last accessed, or
// in 5000 millis, which ever triggers first
cache.put("riesling", rieslingPrice, 5,
          TimeUnit.SECONDS, 1, TimeUnit.SECONDS);

----


=== Expiration designs

Central to expiration is an ExpirationManager.

The purpose of the ExpirationManager is to drive the expiration thread which
periodically purges items from the DataContainer.  If the expiration thread is
disabled (wakeupInterval set to -1) expiration can be kicked off manually
using ExprationManager.processExpiration(), for example from another
maintenance thread that may run periodically in your application.

The expiration manager processes expirations in the following manner:

. Causes the data container to purge expired entries
. Causes cache stores (if any) to purge expired entries

