[[eviction_anchor]]
==  Eviction and Data Container

Infinispan supports eviction of entries, such that you do not run out of memory.
Eviction is typically used in conjunction with a cache store, so that entries are
not permanently lost when evicted, since eviction only removes entries from
memory and not from cache stores or the rest of the cluster.

Infinispan supports storing data in a few different formats.  Data can be
stored as the object iself, binary as a byte[], and off-heap which stores the
byte[] in native memory.

TIP:  Passivation is also a popular option when using eviction, so that only a
single copy of an entry is maintained - either in memory or in a cache store,
but not both. The main benefit of using passivation over a regular cache store
is that updates to entries which exist in memory are cheaper since the update
doesn't need to be made to the cache store as well.

IMPORTANT: Eviction occurs on a _local_ basis, and is not cluster-wide.  Each
node runs an eviction thread to analyse the contents of its in-memory container
and decide what to evict. Eviction does not take into account the amount of free
memory in the JVM as threshold to  starts evicting entries. You have to set `size`
attribute of the eviction element to be greater than zero in order for eviction
to be turned on. If size is too large you can run out of memory. The `size`
attribute will probably take some tuning in each use case.

=== Enabling Eviction

Eviction is configured by adding the
link:http://docs.jboss.org/infinispan/{infinispanversion}/configdocs/infinispan-config-{infinispanversion}.html[`<memory />`]
element to your `<*-cache />` configuration sections or using
link:{javadocroot}/org/infinispan/configuration/cache/MemoryConfigurationBuilder.html[MemoryConfigurationBuilder]
API programmatic approach.

All cache entry are evicted by piggybacking on user threads that are hitting the cache.

==== Eviction strategy

Eviction is handled by link:https://github.com/ben-manes/caffeine[Caffeine] utilizing
the TinyLFU algorithm with an additional admission window.  This was chosen as
provides high hit rate while also requiring low memory overhead.  This provides a
better hit ratio than LRU while also requiring less memory than LIRS.

==== Eviction types

.`COUNT`
This type of eviction will remove entries based on how many there are in the
cache.  Once the count of entries has grown larger than the `size` then an
entry will be removed to make room.

.`MEMORY`
This type of eviction will estimate how much each entry will take up in memory
and will remove an entry when the total size of all entries is larger than
the configured `size`.  This type only works with primitive wrapper, String
and byte[] types, thus if custom types are desired you must enable
storeAsBinary.  Also MEMORY based eviction only works with LRU policy.

==== Storage type

Infinispan allows the user to configure in what form their data is stored.  Each
form supports the same features of Infinispan, however eviction can be limited
for some forms.  There are currently three storage formats that Infinispan
provides, they are:

.`OBJECT`
Stores the keys and values as objects in the Java heap  Only `COUNT` eviction
type is supported.

.`BINARY`
Stores the keys and values as a byte[] in the Java heap.  This will use the configured
marshaller for the cache if there is one.  Both `COUNT` and
`MEMORY` eviction types are supported.

.`OFF-HEAP`
Stores the keys and values in native memory outside of the
Java heap as bytes.  The configured marshaller will be used if the cache has one.
Both `COUNT` and `MEMORY` eviction types are supported.

WARNING: Both `BINARY` and `OFF-HEAP` violate equality in that equality is dictated
by equivalence of the resulting byte[] they generate instead of the object instance.

==== More defaults

By default when no `<memory />` element is specified, no eviction takes place and
`OBJECT` storage type is used.

In case there is an memory element, this table describes the behaviour of eviction
based on information provided in the xml configuration ("-" in Supplied size or
Supplied strategy column means that the attribute wasn't supplied)

[options="header"]
|===============
|Supplied size|Example|Eviction behaviour
|-| `<memory />` |no eviction as an object
|&gt; 0| `<memory> <object size="100" /> </memory>` |eviction takes place and stored as objects
|&gt; 0| `<memory> <off-heap size="100" /> </memory>` |eviction takes place and stored in off-heap
|0| `<memory> <object size="0" /> </memory>` | no eviction
|&lt; 0| `<memory> <object size="-1" /> </memory>` | no eviction

|===============

=== Expiration

Similar to, but unlike eviction, is expiration. Expiration allows you to attach
lifespan and/or maximum idle times to entries. Entries that exceed these times
are treated as invalid and are removed. When removed expired entries are not
passivated like evicted entries (if passivation is turned on).

TIP: Unlike eviction, expired entries are removed globally - from memory, cache
stores, and cluster-wide.

By default entries created are immortal and do not have a lifespan or maximum
idle time.  Using the cache API, mortal entries can be created with lifespans
and/or maximum idle times.  Further, default lifespans and/or maximum idle
times can be configured by adding the
link:http://docs.jboss.org/infinispan/{infinispanversion}/configdocs/infinispan-config-{infinispanversion}.html[&lt;expiration /&gt;]
element to your `<*-cache />`  configuration sections.

When an entry expires it will reside in the data container or cache store
until it is accessed again by a user request.  There is also an optional
expiration reaper that can run at a given configurable interval of
milliseconds which will check for expired entries and remove them.

==== Difference between Eviction and Expiration

Both Eviction and Expiration are means of cleaning the cache of unused entries
and thus guarding the heap against OutOfMemory exceptions, so now a brief
explanation of the difference.

With _eviction_ you set _maximal number of entries_ you want to keep in the cache
and if this limit is exceeded, some candidates are found to be removed according
to a choosen _eviction strategy_ (LRU, LIRS, etc...). Eviction can be setup to
work with passivation (evicting to a cache store).

With _expiration_ you set _time criteria_ for entries, _how long you want to keep them_
in cache. Either you set maximum _lifespan_ of the entry - time it is allowed to
stay in the cache or _maximum idle time_ , time it's allowed to be untouched
(no operation performed with given key).

===  Expiration details

.  _Expiration_ is a top-level construct, represented in the configuration as well as in the cache API.
.  While eviction is _local to each cache instance_ , expiration is _cluster-wide_ .  Expiration lifespans and maxIdle values are replicated along with the cache entry.
.  While maxIdle is replicated, expiration due to maxIdle is not cluster wide, only lifespan.  As such it is not recommended to use maxIdle in a clustered cache.
.  Expiration lifespan and maxIdle are also persisted in CacheStores, so this information survives eviction/passivation.

==== Configuration

Eviction may be configured using the Configuration bean or the XML file.  Eviction configuration is on a per-cache basis.  Valid eviction-related configuration elements are:

[source,xml]
----
<memory>
   <object size="2000"/>
</memory>
<expiration lifespan="1000" max-idle="500" interval="1000" />

----

Programmatically, the same would be defined using:

[source,java]
----
Configuration c = new ConfigurationBuilder()
               .memory().size(2000)
               .expiration().wakeUpInterval(5000l).lifespan(1000l).maxIdle(500l)
               .build();

----

==== Memory Based Eviction Configuration

Memory based eviction may require some additional configuration options if you
are using your own custom types (as Infinispan is normally used).  In this case
Infinispan cannot estimate the memory usage of your classes and as such you are
required to use `storeAsBinary` when memory based eviction is used.

[source,xml]
----
<!-- Enable memory based eviction with 1 GB/>
<memory>
   <binary size="1000000000" eviction="MEMORY"/>
</memory>
----

[source,java]
----
Configuration c = new ConfigurationBuilder()
               .memory()
               .storageType(StorageType.BINARY)
               .evictionType(EvictionType.MEMORY)
               .size(1_000_000_000)
               .build();
----

==== Default values

Eviction is disabled by default. Default values are used:

* size: -1 is used if not specified, which means unlimited entries.
* 0 means no entries, and the eviction thread will strive to keep the cache empty.

Expiration lifespan and maxIdle both default to -1.

==== Using expiration

Expiration allows you to set either a lifespan or a maximum idle time on each key/value pair stored in the cache.  This can either be set cache-wide using the configuration, as described above, or it can be defined per-key/value pair using the Cache interface.  Any values defined per key/value pair overrides the cache-wide default for the specific entry in question.

For example, assume the following configuration:

[source,xml]
----
<expiration lifespan="1000" />

----

[source,java]
----
// this entry will expire in 1000 millis
cache.put("pinot noir", pinotNoirPrice);

// this entry will expire in 2000 millis
cache.put("chardonnay", chardonnayPrice, 2, TimeUnit.SECONDS);

// this entry will expire 1000 millis after it is last accessed
cache.put("pinot grigio", pinotGrigioPrice, -1,
          TimeUnit.SECONDS, 1, TimeUnit.SECONDS);

// this entry will expire 1000 millis after it is last accessed, or
// in 5000 millis, which ever triggers first
cache.put("riesling", rieslingPrice, 5,
          TimeUnit.SECONDS, 1, TimeUnit.SECONDS);

----


=== Expiration designs

Central to expiration is an ExpirationManager.

The purpose of the ExpirationManager is to drive the expiration thread which
periodically purges items from the DataContainer.  If the expiration thread is
disabled (wakeupInterval set to -1) expiration can be kicked off manually
using ExprationManager.processExpiration(), for example from another
maintenance thread that may run periodically in your application.

The expiration manager processes expirations in the following manner:

. Causes the data container to purge expired entries
. Causes cache stores (if any) to purge expired entries

