//RHDG only: Productized Spring Boot starter
ifdef::productized[]
[[rhdg_spring_boot_starter]]
=== Using the Spring Boot Starter
Quickly get your Spring Boot project up and running with {brandname}.

The {brandname} starter provides a set of managed transitive dependencies that include everything your Spring Boot project needs to seamlessly interact with {brandname} in one of two modes:

* Embedded Mode runs {brandname} inside your application.
* Remote Client/Server Mode connects your application to an {brandname} cluster.

[NOTE]
====
The {brandname} Spring Boot starter gives you a convenient way to get started with Spring Boot but is optional. To use {brandname} with Spring Boot you can simply add the dependencies you want.
====

To set up your project, add one of the following to your `pom.xml` file:

.Embedded Mode
include::topics/dependencies/sb_embedded.adoc[]

.Remote Client/Server Mode
include::topics/dependencies/sb_remote.adoc[]

==== Enforcing {brandname} Versions

This starter uses a high-level API to ensure compatibility between major versions of {brandname}. However you can enforce a specific version of {brandname} with the `infinispan-bom` module.

Add `infinispan-bom` to your `pom.xml` file before the starter dependenices, as follows:

include::topics/dependencies/sb_bom.adoc[]

==== Running in Embedded Mode

. Add `{sb_starter_embedded}` to your project's classpath to enable Embedded mode.
+
This starter operates in Remote Client/Server mode with `{sb_starter_remote}` on the classpath by default.
+
. Use the Spring `@Autowired` annotation to include an `EmbeddedCacheManager` bean in your Java configuration classes, as in the following example:
+
[source,java,options="nowrap"]
----
private final EmbeddedCacheManager cacheManager;

@Autowired
public YourClassName(EmbeddedCacheManager cacheManager) {
    this.cacheManager = cacheManager;
}
----
+
You are now ready to use {brandname} in Embedded Mode. Here is a simple example:
+
[source,java,options="nowrap"]
----
cacheManager.getCache("testCache").put("testKey", "testValue");
System.out.println("Received value from cache: " + cacheManager.getCache("testCache").get("testKey"));
----

===== Customizing the Cache Manager

Customize the cache manager with the following configuration beans:

* `InfinispanGlobalConfigurer`
* `InfinispanCacheConfigurer`
* `Configuration`
* `InfinispanConfigurationCustomizer`
* `InfinispanGlobalConfigurationCustomizer`
+
[NOTE]
====
You can create one `InfinispanGlobalConfigurer` bean only. However you can create multiple configurations with the other beans.
====

.InfinispanCacheConfigurer Bean
[source,java,options="nowrap"]
----
@Bean
public InfinispanCacheConfigurer cacheConfigurer() {
	return manager -> {
		final Configuration ispnConfig = new ConfigurationBuilder()
                        .clustering()
                        .cacheMode(CacheMode.LOCAL)
                        .build();

		manager.defineConfiguration("local-sync-config", ispnConfig);
	};
}
----

.Configuration Bean
Link the bean name to the cache that it configures, as follows:
[source,java,options="nowrap"]
----
@Bean(name = "small-cache")
public org.infinispan.configuration.cache.Configuration smallCache() {
    return new ConfigurationBuilder()
        .read(baseCache)
        .memory().size(1000L)
        .memory().evictionType(EvictionType.COUNT)
        .build();
}

@Bean(name = "large-cache")
public org.infinispan.configuration.cache.Configuration largeCache() {
    return new ConfigurationBuilder()
        .read(baseCache)
        .memory().size(2000L)
        .build();
}
----

.Customizer Beans
[source,java,options="nowrap"]
----
@Bean
public InfinispanGlobalConfigurationCustomizer globalCustomizer() {
   return builder -> builder.transport().clusterName(CLUSTER_NAME);
}

@Bean
public InfinispanConfigurationCustomizer configurationCustomizer() {
   return builder -> builder.memory().evictionType(EvictionType.COUNT);
}
----

===== Enabling Spring Cache Support

Add the `@EnableCaching` annotation to your application to enable Spring Cache support.

When this starter detects the `EmbeddedCacheManager` bean, it instantiates a new `SpringEmbeddedCacheManager`, which provides an implementation of
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html[Spring Cache].

===== Configuration Properties

Include the following properties in the `application.properties` or `application.yml` file to configure your project:

[source,yaml,options="nowrap"]
----
infinispan.embedded.enabled = # Enables Data Grid capabilities in your application. The value is true (default) or false.
infinispan.embedded.machineId = # Sets the Spring state machine ID.
infinispan.embedded.clusterName = # Sets the name of the Data Grid cluster.
infinispan.embedded.configXml = # Specifies a XML configuration file.
----

[NOTE]
====
If you specify a {brandname} configuration with the `infinispan.embedded.configXml` property, it takes priority over the global configuration bean or any configuration customizer.
====

==== Running in Remote Client/Server Mode

. Provide the location for the {brandname} server so the starter can create the `RemoteCacheManager` bean.
+
This starter first attempts to locate the server from the `hotrod-client.properties` file on the classpath. If not found, the starter then attempts to locate the server from your `application.properties` file.
+
* `hotrod-client.properties`:
+
[source,text,options=nowrap]
----
infinispan.client.hotrod.server_list=127.0.0.1:6667
----
+
* `application.properties`:
+
[source,text,options=nowrap]
----
infinispan.remote.server-list=127.0.0.1:11222
----
+
. Use the Spring `@Autowired` annotation to include your own custom cache manager class in your application:
+
[source,java,options="nowrap"]
----
private final RemoteCacheManager cacheManager;

@Autowired
public YourClassName(RemoteCacheManager cacheManager) {
    this.cacheManager = cacheManager;
}
----

===== Customizing the Cache Manager

Customize the cache manager with the following configuration beans:

* `InfinispanRemoteConfigurer`
* `Configuration`
* `InfinispanRemoteCacheCustomizer`
+
[NOTE]
====
You can create one `InfinispanRemoteConfigurer` bean only. However you can create multiple configurations with the other beans.
====

.InfinispanRemoteConfigurer Bean
[source,java,options="nowrap"]
----
@Bean
public InfinispanRemoteConfigurer infinispanRemoteConfigurer() {
    return () -> new ConfigurationBuilder()
        .addServer()
        .host("127.0.0.1")
        .port(12345)
        .build();
}
----

.Configuration Bean
[source,java,options="nowrap"]
----
@Bean
public org.infinispan.client.hotrod.configuration.Configuration customConfiguration() {
    new ConfigurationBuilder()
        .addServer()
        .host("127.0.0.1")
        .port(12345)
        .build();
}
----

.InfinispanRemoteCacheCustomizer Bean
[source,java,options="nowrap"]
----
@Bean
public InfinispanRemoteCacheCustomizer customizer() {
    return b -> b.tcpKeepAlive(false);
}
----

[TIP]
====
Use the `@Ordered` annotation to apply customizers in a specific order.
====

===== Enabling Spring Cache Support

Add the `@EnableCaching` annotation to your application to enable Spring Cache support.

When the {brandname} starter detects the `RemoteCacheManager` bean, it instantiates a new `SpringRemoteCacheManager`, which provides an implementation of
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html[Spring Cache].

===== Enabling Spring Session Support

{brandname} Spring Session support is built on
`SpringRemoteCacheManager` and `SpringEmbeddedCacheManager`. This starter produces those beans by default.

To use Spring Session in your project, do the following:

. Add this starter to your project.
. Add Spring Session to the classpath.
. Add the following annotations to your configuration:
- `@EnableCaching`
- `@EnableInfinispanRemoteHttpSession`
- `@EnableInfinispanEmbeddedHttpSession`

===== Configuration Properties

Include the following properties in the `application.properties` or `application.yml` file to configure your project:

[source,yaml,options="nowrap"]
----
infinispan.remote.clientProperties = # Specifies a custom filename for Hot Rod client properties.
infinispan.remote.enabled = # Enables Data Grid capabilities in your application. The value is true (default) or false.
infinispan.remote.serverList = # Defines a comma-separated list of Data Grid  servers in this format: `host1[:port],host2[:port]`.
infinispan.remote.socketTimeout = # Sets a timeout value, in milliseconds, for socket connections.
infinispan.remote.connectTimeout = # Sets a timeout value for initializing connections with Data Grid servers.
infinispan.remote.maxRetries = # Sets the maximum number of attempts to connect to Data Grid servers.
----

// End productized content.
endif::productized[]

[[spring_integration]]
=== Using {brandname} with Spring
{brandname} integrates with the Spring Framework to make it easy to add caching capabilities to your applications.

[[spring_boot_starter]]
//Infinispan only: Refer to GitHub.
ifndef::productized[]
==== Spring Boot Starter
Check out the {brandname} link:https://github.com/infinispan/infinispan-spring-boot[Spring Boot Starter on GitHub] to quickly get up and running.
endif::productized[]

[[spring_cache_provider]]
==== Setting Up {brandname} as a Spring Cache Provider
{brandname} implements the Spring SPI to offer high-performance, in-memory caching capabilities.

[[spring_add_support]]
===== Adding Spring Cache Support
The link:http://spring.io/[Spring Framework] offers a link:https://docs.spring.io/spring/docs/5.1.3.RELEASE/spring-framework-reference/integration.html#cache[cache abstraction] with two simple annotations:

* `@Cacheable` adds entries to the cache.
* `@CacheEvict` removes entries from the cache.

To add caching support to your application, do the following:

. Enable cache annotations in your application context either declaratively or programmatically.
+
* *Declaratively:* Add `<cache:annotation-driven/>` to your application context.
+
[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:cache="http://www.springframework.org/schema/cache"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/cache http://www.springframework.org/schema/cache/spring-cache.xsd">

        <cache:annotation-driven />

</beans>
----
+
* *Programmatically:* Enable cache support as follows:
+
[source,java,options=nowrap]
----
@EnableCaching @Configuration
public class Config {
}
----
+
. Add {brandname} and the Spring integration module to your `pom.xml`.
+
* Embedded mode: `infinispan-spring5-embedded`
* Remote client-server mode: `infinispan-spring5-remote`
+
.pom.xml for Spring 4 (embedded mode)
[source,xml]
----
    <dependencies>
        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-spring5-embedded</artifactId>
            <version>${version.infinispan}</version>
        </dependency>
        <!-- Use the Spring Boot Starter
        instead of spring-boot. -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${version.spring}</version>
        </dependency>
    </dependencies>
----

[[spring_configure_cache_provider]]
===== Configuring {brandname} as the Spring Cache Provider
The Spring cache provider SPI has two interfaces through which it interacts with {brandname}: `org.springframework.cache.CacheManager` and `org.springframework.cache.Cache`. The `CacheManager` interface acts as a factory for named `Cache` instances.

At runtime Spring looks for a `CacheManager` implementation that has a bean named `cacheManager` in the application context.

You can configure your application context either declaratively or programmatically.

* *Declaratively:*
+
[source,xml,options=nowrap]
----

<!-- Infinispan cache manager -->
<bean id="cacheManager"
          class="org.infinispan.spring.embedded.provider.SpringEmbeddedCacheManagerFactoryBean"
          p:configurationFileLocation="classpath:/org/infinispan/spring/embedded/provider/sample/books-infinispan-config.xml" />
----
* *Programmatically:*
+
[source,xml,options=nowrap]
----
@EnableCaching
@Configuration
public class Config {

   @Bean
   public CacheManager cacheManager() {
      return new SpringEmbeddedCacheManager(infinispanCacheManager());
   }

   private EmbeddedCacheManager infinispanCacheManager() {
      return new DefaultCacheManager();
   }

}
----

[[spring_add_caching]]
==== Adding Caching to Your Application
Add the `@Cacheable` and `@CacheEvict` annotations to your application code.

[[spring_add_entries]]
===== Adding Cache Entries
The `@Cacheable` annotation adds returned values to a defined cache.

For instance, you have a data access object (DAO) for books. You want book instances to be cached after they have been loaded from the underlying database using `BookDao#findBook(Integer bookId)`.

Annotate the `findBook(Integer bookId)` method with `@Cacheable` as follows:

[source,java,options=nowrap]
----
@Transactional
@Cacheable(value = "books", key = "#bookId")
public Book findBook(Integer bookId) {...}
----

Any `Book` instances returned from `findBook(Integer bookId)` are stored in a cache named `books`, using `bookId` as the key.

Note that "#bookId" is an expression in the link:http://static.springsource.org/spring/docs/current/spring-framework-reference/html/expressions.html[Spring Expression Language] that evaluates the `bookId` argument.

[IMPORTANT]
====
If your application needs to reference entries in the cache directly, you should include the `key` attribute. Without this attribute, Spring generates a hash from the supplied method arguments to use as the cache key.
====

[[spring_remove_entries]]
===== Deleting Cache Entries
The `@CacheEvict` annotation deletes entries from a defined cache.

Annotate the `deleteBook(Integer bookId)` method with `@CacheEvict` as follows:

[source,java,options=nowrap]
----
// Evict all entries in the "books" cache
@Transactional
@CacheEvict (value="books", key = "#bookId", allEntries = true)
public void deleteBookAllEntries() {...}

// Evict entries in the "books" cache that match #bookId
@Transactional
@CacheEvict (value="books", key = "#bookId")
public void deleteBook(Integer bookId) {...]}
----

[[spring_configure_timeouts]]
==== Configuring Timeouts for Cache Operations

The {brandname} Spring cache provider defaults to blocking behaviour when performing read and write operations. By default operations are synchronous and do not time out. However, you might want to set a maximum time to wait for operations before timing out in some situations. For example, timeouts are useful if you need to ensure that an operation completes within a certain time and you can ignore the cached value.

`infinispan.spring.operation.read.timeout`::
Specifies the time, in milliseconds, to wait for read operations to complete. The default is `0` which means unlimited wait time.
`infinispan.spring.operation.write.timeout`::
Specifies the time, in milliseconds, to wait for write operations to complete. The default is `0` which means unlimited wait time.

To configure timeouts for cache operations, set the properties in the context XML for your application on either of the following:

* link:{javadocroot}/org/infinispan/spring/provider/SpringEmbeddedCacheManagerFactoryBean.html[SpringEmbeddedCacheManagerFactoryBean]
* link:{javadocroot}/org/infinispan/spring/provider/SpringRemoteCacheManagerFactoryBean.html[SpringRemoteCacheManagerFactoryBean]

[TIP]
====
In remote client-server mode, you can also add these properties to `hotrod-client.properties`.
====

The following example shows the timeout properties in the context XML for `SpringRemoteCacheManagerFactoryBean`:

[source,xml,options=nowrap]
----
<bean id="springRemoteCacheManagerConfiguredUsingConfigurationProperties"
      class="org.infinispan.spring.remote.provider.SpringRemoteCacheManagerFactoryBean">
    <property name="configurationProperties">
        <props>
           <prop key="infinispan.spring.operation.read.timeout">500</prop>
           <prop key="infinispan.spring.operation.write.timeout">700</prop>
        </props>
    </property>
</bean>
----

[[spring_externalize_sessions]]
==== Externalizing Sessions Using Spring Session

link:http://docs.spring.io/spring-session/docs/current/reference/html5[Spring Session] lets you externalize user session information into {brandname}.

To configure Spring Session integration in your application, do the following:

. Add dependencies to your `pom.xml`.
+
* Embedded mode: `infinispan-spring5-embedded`
* Remote client-server mode: `infinispan-spring5-remote`
+
.pom.xml (embedded mode)
----
    <dependencies>
        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-spring5-embedded</artifactId>
            <version>${version.infinispan}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${version.spring}</version>
        </dependency>
        <dependency>
           <groupId>org.springframework</groupId>
           <artifactId>spring-session-core</artifactId>
           <version>${version.spring}</version>
       </dependency>
       <dependency>
           <groupId>org.springframework</groupId>
           <artifactId>spring-web</artifactId>
           <version>${version.spring}</version>
       </dependency>
    </dependencies>
----
+
. Specify the appropriate FactoryBean to expose a `CacheManager` instance.
+
* Embedded mode: `SpringEmbeddedCacheManagerFactoryBean`
* Remote client-server mode: `SpringRemoteCacheManagerFactoryBean`
+
. Enable Spring Session with the appropriate annotation.
+
* Embedded mode: `@EnableInfinispanEmbeddedHttpSession`
* Remote client-server mode: `@EnableInfinispanRemoteHttpSession`
+
There annotations have optional parameters:
+
- `maxInactiveIntervalInSeconds` sets session expiration time in seconds. The default is `1800`.
- `cacheName` specifies the name of the cache that stores sessions. The default is `sessions`.
- `executorPoolSize` specifies the size of the thread pool that will be used to make
calls to the cache from the remote listeners. The default is `4`.
- `executorMaxPoolSize` specifies the max pool size. The default is `4`.
- `executorThreadNamePrefix` specifies the prefix of the thread's names. The default is `infinispan_remote_task_executor_thread`.

The following example shows a complete, annotation-based configuration:

[source,java,options=nowrap]
----
@EnableInfinispanEmbeddedHttpSession
@Configuration
public class Config {

   @Bean
   public SpringEmbeddedCacheManagerFactoryBean springCacheManager() {
      return new SpringEmbeddedCacheManagerFactoryBean();
   }

   //An optional configuration bean responsible for replacing the default
   //cookie that obtains configuration.
   //For more information refer to the Spring Session documentation.
   @Bean
   public HttpSessionStrategy httpSessionStrategy() {
      return new HeaderHttpSessionStrategy();
   }
}
----
