=== JDBC String based Cache Store
A cache store which relies on the provided JDBC driver to load/store values in the underlying database.

Each key in the cache is stored in its own row in the database. In order to store each key in its own row, this store relies
on a (pluggable) bijection that maps the each key to a String object. The bijection is defined by the Key2StringMapper interface.
{brandname}s ships a default implementation (smartly named DefaultTwoWayKey2StringMapper) that knows how to handle primitive types.

NOTE: By default {brandname} shares are not stored, meaning that all nodes in the cluster will write to the underlying store upon each update.
If you wish for an operation to only be written to the underlying database once, you must configure the JDBC store to be shared.

==== Connection management (pooling)
In order to obtain a connection to the database the JDBC cache store relies on a link:http://docs.jboss.org/infinispan/{infinispanversion}/apidocs/org/infinispan/persistence/jdbc/connectionfactory/ConnectionFactory.html[ConnectionFactory]
implementation. The connection factory is specified programmatically using one of the connectionPool(), dataSource()
or simpleConnection() methods on the JdbcStringBasedStoreConfigurationBuilder class or declaratively using one of the
`<connectionPool />`, `<dataSource />` or `<simpleConnection />` elements.

{brandname} ships with three ConnectionFactory implementations:


*  link:http://docs.jboss.org/infinispan/{infinispanversion}/apidocs/org/infinispan/persistence/jdbc/connectionfactory/PooledConnectionFactory.html[PooledConnectionFactory]
is a factory based on link:https://github.com/brettwooldridge/HikariCP[HikariCP]. Additional properties for HikariCP can
be provided by a properties file, either via placing a `hikari.properties` file on the classpath or by specifying the
path to the file via `PooledConnectionFactoryConfiguration.propertyFile` or `properties-file` in the connection pool's
xml config. N.B. a properties file specified explicitly in the configuration is loaded instead of the `hikari.properties`
file on the class path and Connection pool characteristics which are explicitly set in PooledConnectionFactoryConfiguration
always override the values loaded from a properties file.

Refer to the official link:https://github.com/brettwooldridge/HikariCP[documentation] for details of all configuration properties.


*  link:http://docs.jboss.org/infinispan/{infinispanversion}/apidocs/org/infinispan/persistence/jdbc/connectionfactory/ManagedConnectionFactory.html[ManagedConnectionFactory]
is a connection factory that can be used within managed environments, such as application servers. It knows how to look
into the JNDI tree at a certain location (configurable) and delegate connection management to the DataSource.
Refer to javadoc link:http://docs.jboss.org/infinispan/{infinispanversion}/apidocs/org/infinispan/persistence/jdbc/connectionfactory/ManagedConnectionFactory.html[javadoc]
for details on how this can be configured.


*  link:http://docs.jboss.org/infinispan/{infinispanversion}/apidocs/org/infinispan/persistence/jdbc/connectionfactory/SimpleConnectionFactory.html[SimpleConnectionFactory]
is a factory implementation that will create database connection on a per invocation basis. Not recommended in production.

The `PooledConnectionFactory` is generally recommended for stand-alone deployments (i.e. not running within AS or servlet container).
`ManagedConnectionFactory` can be used when running in a managed environment where a `DataSource` is present, so that
connection pooling is performed within the `DataSource`.

==== Sample configurations

Below is a sample configuration for the link:http://docs.jboss.org/infinispan/{infinispanversion}/apidocs/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.html[JdbcStringBasedStore].
For detailed description of all the parameters used refer to the link:http://docs.jboss.org/infinispan/{infinispanversion}/apidocs/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.html[JdbcStringBasedStore].

[source,xml]
----
<persistence>
   <string-keyed-jdbc-store xmlns="urn:infinispan:config:store:jdbc:9.2" shared="true" fetch-state="false" read-only="false" purge="false">
      <connection-pool connection-url="jdbc:h2:mem:infinispan_string_based;DB_CLOSE_DELAY=-1" username="sa" driver="org.h2.Driver"/>
      <string-keyed-table drop-on-exit="true" create-on-start="true" prefix="ISPN_STRING_TABLE">
         <id-column name="ID_COLUMN" type="VARCHAR(255)" />
         <data-column name="DATA_COLUMN" type="BINARY" />
         <timestamp-column name="TIMESTAMP_COLUMN" type="BIGINT" />
      </string-keyed-table>
   </string-keyed-jdbc-store>
</persistence>

----

[source,java]
----

ConfigurationBuilder builder = new ConfigurationBuilder();
builder.persistence().addStore(JdbcStringBasedStoreConfigurationBuilder.class)
      .fetchPersistentState(false)
      .ignoreModifications(false)
      .purgeOnStartup(false)
      .shared(true)
      .table()
         .dropOnExit(true)
         .createOnStart(true)
         .tableNamePrefix("ISPN_STRING_TABLE")
         .idColumnName("ID_COLUMN").idColumnType("VARCHAR(255)")
         .dataColumnName("DATA_COLUMN").dataColumnType("BINARY")
         .timestampColumnName("TIMESTAMP_COLUMN").timestampColumnType("BIGINT")
      .connectionPool()
         .connectionUrl("jdbc:h2:mem:infinispan_string_based;DB_CLOSE_DELAY=-1")
         .username("sa")
         .driverClass("org.h2.Driver");

----

Finally, below is an example of a JDBC cache store with a managed connection factory, which is chosen implicitly by specifying a datasource JNDI location:

[source,xml]
----

<string-keyed-jdbc-store xmlns="urn:infinispan:config:store:jdbc:9.2" shared="true" fetch-state="false" read-only="false" purge="false">
   <data-source jndi-url="java:/StringStoreWithManagedConnectionTest/DS" />
   <string-keyed-table drop-on-exit="true" create-on-start="true" prefix="ISPN_STRING_TABLE">
      <id-column name="ID_COLUMN" type="VARCHAR(255)" />
      <data-column name="DATA_COLUMN" type="BINARY" />
      <timestamp-column name="TIMESTAMP_COLUMN" type="BIGINT" />
   </string-keyed-table>
</string-keyed-jdbc-store>

----

[source,java]
----

ConfigurationBuilder builder = new ConfigurationBuilder();
builder.persistence().addStore(JdbcStringBasedStoreConfigurationBuilder.class)
      .fetchPersistentState(false)
      .ignoreModifications(false)
      .purgeOnStartup(false)
      .shared(true)
      .table()
         .dropOnExit(true)
         .createOnStart(true)
         .tableNamePrefix("ISPN_STRING_TABLE")
         .idColumnName("ID_COLUMN").idColumnType("VARCHAR(255)")
         .dataColumnName("DATA_COLUMN").dataColumnType("BINARY")
         .timestampColumnName("TIMESTAMP_COLUMN").timestampColumnType("BIGINT")
      .dataSource()
         .jndiUrl("java:/StringStoreWithManagedConnectionTest/DS");

----

.Apache Derby users
NOTE: If you're connecting to an Apache Derby database, make sure you set dataColumnType to BLOB: `<data-column name="DATA_COLUMN" type="BLOB"/>`

==== JDBC Migrator
The JDBC Mixed and Binary stores have been removed in {brandname} 9.0.0 due to the poor performance associated with storing entries in buckets.
Storing entries in buckets is non-optimal as each read/write to the store requires an existing bucket for a given hash to be retrieved,
deserialised, updated, serialised and then re-inserted back into the db. To assist users, we have created a migration tool
`JDBCMigrator.java`, that reads data from an existing Mixed/Binary store and then stores it in a string keyed table via the
<<_JDBC_String_based_Cache_Store, JdbcStringBasedStore>>.

NOTE: The marshaller changes introduced in {brandname} 9 mean that existing stores that were populated by 8.x are no longer
compatible. The JDBCMigrator can be used to migrate existing JdbcStringBasedStores from the legacy 8.x marshaller to the latest
9.x compatible marshaller.

===== Usage
The Jdbc migrator `org.infinispan.tools.jdbc.migrator.JDBCMigrator` takes a single argument, the path to a
`.properties` file which must contain the configuration properties for both the source and target stores. An example
properties file containing all applicable configuration options can be found
link:https://github.com/infinispan/infinispan/blob/master/tools/src/main/resources/migrator.properties[here].

To use the migrator, you need the `infinispan-tools-{infinispanversion}.jar` as well as the jdbc drivers required by your
source and target databases on your classpath. An example maven pom, that will execute the migrator via `mvn exec:java`
is presented below:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.infinispan.example</groupId>
    <artifactId>jdbc-migrator-example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-tools</artifactId>
            <version>9.0.0-SNAPSHOT</version>
        </dependency>

        <!-- ADD YOUR REQUIRED JDBC DEPENDENCIES HERE -->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.2.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>org.infinispan.tools.jdbc.migrator.JDBCMigrator</mainClass>
                    <arguments>
                        <argument><!-- PATH TO YOUR MIGRATOR.PROPERTIES FILE --></argument>
                    </arguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
----

===== Properties
All migrator properties are configured within the context of a source or target store and so each properties must start
with either `source.` or `target.`.  All of the properties listed below are applicable to both source and target stores,
with the exception of `table.binary.*` properties as it is not possible to migrate to a binary table.

The property `*.marshaller.type` denotes whether the marshaller from infinispan 8.2x (LEGACY), 9.x (CURRENT) or a custom
marshaller should be utilised. Note, that the LEGACY marshaller can only be specified for the source store.

[options="header"]
|===============
|Property|Description|Example value|Required
|type | [STRING,BINARY,MIXED] | MIXED | TRUE
|cache_name | The name of the cache associated with the store | persistentMixedCache | TRUE
|dialect | The dialect of the underlying database | POSTGRES | TRUE
|marshaller.type | [LEGACY,CURRENT,CUSTOM] | CURRENT | TRUE
|marshaller.class | The class of the marshaller if type=CUSTOM | org.example.CustomMarshaller |
|marshaller.externalizers | A comma-separated list of custom AdvancedExternalizer implementations to load[id]:<Externalizer class> | 25:Externalizer1,org.example.Externalizer2 |
|connection_pool.connection_url | The JDBC connection url | jdbc:postgresql:postgres | TRUE
|connection_pool.driver_class | The class of the JDBC driver | org.postrgesql.Driver | TRUE
|connection_pool.username | Database username | | TRUE
|connection_pool.password | Database password | | TRUE
|db.major_version | Database major version | 9 |
|db.minor_version | Database minor version | 5 |
|db.disable_upsert | Disable db upsert | false |
|db.disable_indexing | Prevent table index being created | false |
|table.`<binary\|string>`.table_name_prefix | Additional prefix for table name | tablePrefix |
|table.`<binary\|string>`.`<id\|data\|timestamp>`.name | Name of the column | id_column | TRUE
|table.`<binary\|string>`.`<id\|data\|timestamp>`.type | Type of the column | VARCHAR | TRUE
|key_to_string_mapper | TwoWayKey2StringMapper Class | `org.infinispan.persistence.keymappers. DefaultTwoWayKey2StringMapper` |
|===============
