=== RocksDB Cache Store
The {brandname} Community

==== Introduction
link:http://rocksdb.org/[RocksDB] is a fast key-value filesystem-based storage from Facebook. It started as a fork of
Google's LevelDB, but provides superior performance and reliability, especially in highly concurrent scenarios.

==== Segmentation support
This store supports being segmented, as it will create a separate instance per
segment. This will create multiple directories under the configured directory
where each one is a number representing the given segment the data maps to.

It should be noted that rocks db currently uses a handful of files per database.
Thus if the number of configured segments is high, this can cause a large
amount of file pointers to be opened. Please be cognizant of this fact when
using a segmented rocksdb store.

===== Sample Usage
The RocksDB cache store requires 2 filesystem directories to be configured - each directory contains a RocksDB database:
one location is used to store non-expired data, while the second location is used to store expired keys pending purge.

[source,java]
----
Configuration cacheConfig = new ConfigurationBuilder().persistence()
				.addStore(RocksDBStoreConfigurationBuilder.class)
				.build();
EmbeddedCacheManager cacheManager = new DefaultCacheManager(cacheConfig);

Cache<String, User> usersCache = cacheManager.getCache("usersCache");
usersCache.put("raytsang", new User(...));

----

==== Configuration
===== Sample Programatic Configuration

[source,java]
----

Configuration cacheConfig = new ConfigurationBuilder().persistence()
				.addStore(RocksDBStoreConfigurationBuilder.class)
				.location("/tmp/rocksdb/data")
				.expiredLocation("/tmp/rocksdb/expired")
				.build();

----

[options="header"]
|===============
|Parameter|Description
|location|Directory to use for RocksDB to store primary cache store data.  The directory will be auto-created if it does not exit.
|expiredLocation| Directory to use for RocksDB to store expiring data pending to be purged permanently.  The directory will be auto-created if it does not exit.
| expiryQueueSize |Size of the in-memory queue to hold expiring entries before it gets flushed into expired RocksDB store
|clearThreshold| There are two methods to clear all entries in RocksDB.  One method is to iterate through all entries and remove each entry individually.  The other method is to delete the database and re-init.  For smaller databases, deleting individual entries is faster than the latter method.  This configuration sets the max number of entries allowed before using the latter method
| compressionType |Configuration for RocksDB for data compression, see CompressionType enum for options
| blockSize | Configuration for RocksDB - see link:$$https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide$$[documentation] for performance tuning
| cacheSize | Configuration for RocksDB - see link:$$https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide$$[documentation] for performance tuning

|===============


===== Sample XML Configuration

.infinispan.xml
[source,xml]
----

<local-cache name="vehicleCache">
   <persistence>
      <rocksdb-store path="/tmp/rocksdb/data">
         <expiration path="/tmp/rocksdb/expired"/>
      </rocksdb-store>
   </persistence>
</local-cache>

----

==== Additional References

Refer to the link:$$https://github.com/infinispan/infinispan/blob/master/persistence/rocksdb/src/test/java/org/infinispan/persistence/rocksdb/config/ConfigurationTest.java$$[test case] for code samples in action.

Refer to link:$$https://github.com/infinispan/infinispan/tree/master/persistence/rocksdb/src/test/resources/config/$$[test configurations] for configuration samples.

