name: Extract Maven Artifacts
description: Extract Maven Artifacts uploaded by the build-infinispan action
inputs:
  run-id:
    description: Run id if different than current run (i.e. using workflow_run)
    default: ""
runs:
  using: composite
  steps:
    - name: Download Infinispan Maven artifacts with run-id
      if: inputs.run-id != ''
      uses: actions/download-artifact@v4
      with:
        name: m2-infinispan.tzts
        run-id: ${{ inputs.run-id }}
        github-token: ${{ github.token }}

    - name: Download Infinispan Maven artifacts
      if: inputs.run-id == ''
      uses: actions/download-artifact@v4
      with:
        name: m2-infinispan.tzts

    - name: Extract Infinispan Maven artifacts
      shell: bash
      run: tar -C ~/ --use-compress-program="zstd -d" -xf m2-infinispan.tzts
