package org.infinispan.test.integration.as;

import org.hibernate.search.exception.AssertionFailure;
import org.jboss.shrinkwrap.api.Archive;
import org.jboss.shrinkwrap.api.asset.Asset;
import org.jboss.shrinkwrap.api.asset.StringAsset;
import org.jboss.shrinkwrap.descriptor.api.Descriptors;
import org.jboss.shrinkwrap.descriptor.api.spec.se.manifest.ManifestDescriptor;

/**
 * Helper class for integration testing of the JBoss Modules generated by the hibernate-search-modules Maven module.
 * <p/>
 * The slot version is set as a property in the parent pom, and passed to the JVM of Arquillian as a system property of
 * the Maven maven-failsafe-plugin.
 *
 * @since 5.0
 */
public class VersionTestHelper {

   private static final String wildflySearchModuleDependency = "org.hibernate.search.orm:" + getVersionString() + " services";

   private VersionTestHelper() {
      //not meant to be created
   }

   /**
    * @return the slot version of the Hibernate Search modules generated by this project
    */
   private static String getVersionString() {
      return getRequiredSystemProperty("hibernate.search.module.slot.version");
   }

   /**
    * @param optionalDependencies additional dependencies to include in the Manifest descriptor
    * @return the StringAsset to be used in a Manifest descriptor to enable the Hibernate-Search-ORM module
    */
   public static Asset moduleDependencyManifest(String... optionalDependencies) {
      String dependencies = wildflySearchModuleDependency;
      for (String dependency : optionalDependencies) {
         dependencies += ", " + dependency;
      }
      String manifest = Descriptors.create(ManifestDescriptor.class)
            .attribute("Dependencies", dependencies)
            .exportAsString();
      return new StringAsset(manifest);
   }

   /**
    * Adds the needed Manifest to a deployment to enable the Hibernate-Search-ORM module
    *
    * @param optionalDependencies additional dependencies to include in the Manifest descriptor
    * @param archive              it will contain the Manifest
    */
   public static void addDependencyToSearchModule(Archive<?> archive, String... optionalDependencies) {
      archive.add(VersionTestHelper.moduleDependencyManifest(optionalDependencies), "META-INF/MANIFEST.MF");
   }

   public static String getDependencyVersionLucene() {
      return getRequiredSystemProperty("dependency.version.Lucene");
   }

   public static String getDependencyVersionHibernateCommonsAnnotations() {
      return getRequiredSystemProperty("dependency.version.HibernateCommonsAnnotations");
   }

   private static String getRequiredSystemProperty(String property) {
      String systemProperty = System.getProperty(property);
      if (systemProperty == null) {
         throw new AssertionFailure(
               "The test setup requires the system property '" + property + "' to be set. Check your environment!"
         );
      }
      return systemProperty;
   }
}
