name: Backport branch reaper

on:
  pull_request_target:
    types:
      - closed
    branches:
      - '*.0.x'

jobs:
  remove_backport_branch:
    if: startsWith(github.event.pull_request.head.ref, 'bp-')
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR head branches
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          numbers: ${{github.event.pull_request.number}}
