name: Lint GitHub Actions Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    name: Lint GitHub Actions workflows
    
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: actionlint with reviewdog
        uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          fail_level: warning
          filter_mode: file
          level: warning
