name: Lint GitHub Actions Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    name: Lint GitHub Actions workflows
    
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: actionlint with reviewdog
        uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283 # v1.73.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-annotations
          fail_level: warning
          filter_mode: file
          level: warning
