name: Close Stale Issues

on:
  schedule:
    - cron: '23 1 * * *'  # Every day at 1:23 AM UTC
  workflow_dispatch:      # Optional: allows manual triggering
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Close stale issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 0
          days-before-pr-stale: -1
          days-before-pr-close: -1
          only-issue-labels: 'kind/flaky test'   # only affects issues with this label
          operations-per-run: 100
