name: Update Jira Flaky
on:
   workflow_run:
     workflows: [Test]
     types: [completed]
jobs:
   jiraForFlakyTest:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: Flaky Test To Jira
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install xmlstarlet tool
# xmlstarlet is needed by bin/jira/track_flaky_tests.sh
          shell: bash
          run: |
             sudo apt-get update
             sudo apt-get install -y xmlstarlet

# Downloading flaky artifact containing
# zip file with flaky test reports and file
# containing PR target branch
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
             name: flaky-test-report
             github-token: ${{ github.token }}
             run-id: ${{ github.event.workflow_run.id }}

        - if: steps.download-artifact.outputs.result == 'Flaky Found'
          name: Unzip artifact
          run: unzip flaky-test-report.zip

        - if: steps.download-artifact.outputs.result == 'Flaky Found'
          name: Create Jira
          env:
            TOKEN: ${{ secrets.JIRA_API_TOKEN }}
            RUNNER_DEBUG: 1
            FLAKY_TEST_GLOB: "**/target/*-reports*/**/TEST-*FLAKY.xml"
            PROJECT_KEY: "ISPN"
            TYPE: "Bug"
            JENKINS_JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow.id }}"
          run: |
            set +e
            cat target-branch.txt
            TARGET_BRANCH=$(cat target-branch.txt) bin/jira/track_flaky_tests.sh
            true

        - if: steps.download-artifact.outputs.result == 'Flaky Found'
          name: Get event name
          id: event_name
          uses: juliangruber/read-file-action@v1
          with:
            path: ./event-name.txt

        - if: steps.download-artifact.outputs.result == 'Flaky Found'
          name: Get PR number
          id: pr-number
          uses: juliangruber/read-file-action@v1
          with:
            path: ./pr-number.txt

        - if: >
            steps.download-artifact.outputs.result == 'Flaky Found' &&
            steps.event_name.outputs.content == 'pull_request'
          name: Comment PR
          uses: ./.github/actions/comment-pr-flaky-test
          with:
            pr-number: ${{ steps.pr-number.outputs.content }}

