name: PMD Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-pmd:
    name: Run PMD and comment with reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run PMD
        run: mvn -B pmd:pmd

      - name: Upload PMD Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-reports
          path: |
            **/target/site/pmd.html
            **/target/site/pmd.xml

      - name: Comment PMD violations using reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/reviewdog@v1
        with:
          name: pmd
          reporter: github-pr-review
          tool_name: pmd
          level: warning
          fail_on_error: false
          filter_mode: diff_context
          github_token: ${{ secrets.GITHUB_TOKEN }}
          format: pmd
          input: core/target/site/pmd.xml
