name: PMD Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-pmd:
    name: Run PMD and comment using reviewdog CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install all modules (skip tests)
        run: mvn -B clean install -DskipTests

      - name: Run PMD across all modules
        run: mvn -B pmd:pmd

      - name: Upload PMD Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-reports
          path: |
            **/target/site/pmd.html
            **/target/site/pmd.xml

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Comment PMD findings using reviewdog
        if: github.event_name == 'pull_request'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find . -name "pmd.xml" | while read file; do
            ./bin/reviewdog -f=pmd -name="PMD" -reporter=github-pr-review \
              -fail-on-error=false -level=warning < "$file"
          done
